<?php

declare(strict_types=1);

namespace App\Modules\SubcontractPayments\Repositories;

use App\Core\Database\Database;
use App\Modules\SubcontractPayments\DTOs\SubcontractPaymentData;
use App\Modules\SubcontractPayments\DTOs\SubcontractPaymentTableQuery;

final class SubcontractPaymentRepository
{
    public function __construct(private readonly Database $db) {}
    public function subcontract(int $id,bool $lock=false):?array{if($lock&&$this->one('SELECT id FROM subcontracts WHERE id=? FOR UPDATE',[$id])===null)return null;return$this->one('SELECT s.*,p.name project_name,v.name vendor_name FROM subcontracts s JOIN projects p ON p.id=s.project_id JOIN vendors v ON v.id=s.vendor_id WHERE s.id=? LIMIT 1',[$id]);}
    public function find(int $id,bool $lock=false):?array{if($lock&&$this->one('SELECT id FROM subcontract_payments WHERE id=? FOR UPDATE',[$id])===null)return null;return$this->one('SELECT py.*,s.subcontract_code,s.title subcontract_title,s.contract_value,s.status subcontract_status,v.name vendor_name,p.name project_name,cu.name created_by_name,pu.name posted_by_name,xu.name cancelled_by_name,pa.account_code current_payment_account_code,pa.name_ar current_payment_account_name FROM subcontract_payments py JOIN subcontracts s ON s.id=py.subcontract_id JOIN vendors v ON v.id=py.vendor_id JOIN projects p ON p.id=py.project_id JOIN users cu ON cu.id=py.created_by LEFT JOIN users pu ON pu.id=py.posted_by LEFT JOIN users xu ON xu.id=py.cancelled_by LEFT JOIN accounts pa ON pa.id=py.payment_account_id WHERE py.id=? LIMIT 1',[$id]);}
    public function create(string $code,SubcontractPaymentData $d,array $s,int $user):int{$this->db->execute("INSERT INTO subcontract_payments(payment_code,subcontract_id,vendor_id,project_id,payment_date,amount,payment_channel,payment_method,bank_payment_method,payment_account_id,reference_number,cheque_number,cheque_date,cheque_due_date,status,created_by,notes) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,'draft',?,?)",[$code,$d->subcontractId,(int)$s['vendor_id'],(int)$s['project_id'],$d->paymentDate,$d->amount,$d->paymentChannel,$d->legacyMethod(),$d->bankPaymentMethod,$d->paymentAccountId,$d->referenceNumber,$d->chequeNumber,$d->chequeDate,$d->chequeDueDate,$user,$d->notes]);return(int)$this->db->connection()->insert_id;}
    public function update(int$id,SubcontractPaymentData$d):void{$this->db->execute("UPDATE subcontract_payments SET payment_date=?,amount=?,payment_channel=?,payment_method=?,bank_payment_method=?,payment_account_id=?,reference_number=?,cheque_number=?,cheque_date=?,cheque_due_date=?,notes=? WHERE id=? AND status='draft'",[$d->paymentDate,$d->amount,$d->paymentChannel,$d->legacyMethod(),$d->bankPaymentMethod,$d->paymentAccountId,$d->referenceNumber,$d->chequeNumber,$d->chequeDate,$d->chequeDueDate,$d->notes,$id]);}
    public function paymentAccounts():array{$r=$this->db->execute("WITH RECURSIVE roots AS(SELECT s.mapping_key,a.id FROM accounting_setup s JOIN accounts a ON a.id=s.account_id WHERE s.mapping_key IN('cash_accounts_root','bank_accounts_root')),tree AS(SELECT mapping_key,id FROM roots UNION ALL SELECT t.mapping_key,a.id FROM tree t JOIN accounts a ON a.parent_id=t.id) SELECT a.id,a.account_code,a.name_ar,CASE WHEN t.mapping_key='cash_accounts_root' THEN 'cash' ELSE 'bank' END channel FROM tree t JOIN accounts a ON a.id=t.id WHERE a.is_active=1 AND a.is_postable=1 ORDER BY channel,a.account_code");return$r instanceof \mysqli_result?$r->fetch_all(MYSQLI_ASSOC):[];}
    public function paymentAccount(int$id,string$channel,bool$lock=false):?array{$sql="WITH RECURSIVE roots AS(SELECT s.mapping_key,a.id FROM accounting_setup s JOIN accounts a ON a.id=s.account_id WHERE s.mapping_key=?),tree AS(SELECT id FROM roots UNION ALL SELECT a.id FROM tree t JOIN accounts a ON a.parent_id=t.id) SELECT a.* FROM tree t JOIN accounts a ON a.id=t.id WHERE a.id=? AND a.is_active=1 AND a.is_postable=1".($lock?' FOR UPDATE':'');return$this->one($sql,[$channel==='cash'?'cash_accounts_root':'bank_accounts_root',$id]);}
    public function financialSummary(int$id):array{return$this->one("SELECT s.contract_value,COALESCE(c.cumulative_earned_value,0) approved_earned_value,CASE WHEN s.pricing_method='boq' THEN CASE WHEN s.contract_value>0 THEN ROUND(COALESCE(c.cumulative_earned_value,0)*100/s.contract_value,4) ELSE 0 END ELSE COALESCE(c.cumulative_progress_percentage,0) END approved_progress_percentage,COALESCE(p.posted_total,0) posted_payments_total,GREATEST(COALESCE(c.cumulative_earned_value,0)-COALESCE(p.posted_total,0),0) available_payment_amount,(COALESCE(p.posted_total,0)>COALESCE(c.cumulative_earned_value,0)) inconsistent FROM subcontracts s LEFT JOIN subcontract_progress_certificates c ON c.id=(SELECT c2.id FROM subcontract_progress_certificates c2 WHERE c2.subcontract_id=s.id AND c2.status='approved' ORDER BY c2.certificate_date DESC,c2.id DESC LIMIT 1) LEFT JOIN(SELECT subcontract_id,SUM(amount)posted_total FROM subcontract_payments WHERE status='posted' GROUP BY subcontract_id)p ON p.subcontract_id=s.id WHERE s.id=?",[$id])??[];}
    public function postedTotal(int $subcontractId):string{return(string)(($this->one("SELECT COALESCE(SUM(amount),0) total FROM subcontract_payments WHERE subcontract_id=? AND status='posted'",[$subcontractId])['total']??'0.00'));}
    public function availability(string$earned,string$posted):array{return$this->one('SELECT GREATEST(?-?,0) available,(?>?) inconsistent',[$earned,$posted,$posted,$earned])??['available'=>'0.00','inconsistent'=>1];}
    public function latestPosted(int$id):?array{return$this->one("SELECT id,payment_date FROM subcontract_payments WHERE subcontract_id=? AND status='posted' ORDER BY payment_date DESC,id DESC LIMIT 1",[$id]);}
    public function amountExceeds(string$amount,string$available):bool{return(int)(($this->one('SELECT ?>? exceeds',[$amount,$available])['exceeds']??1))===1;}
    public function post(int$id,int$user,array$f,array$a,int$journal):void{$this->db->execute("UPDATE subcontract_payments SET approved_progress_percentage_snapshot=?,approved_earned_value_snapshot=?,previous_payments_snapshot=?,available_payment_snapshot=?,payment_account_code_snapshot=?,payment_account_name_snapshot=?,journal_entry_id=?,status='posted',posted_at=NOW(),posted_by=? WHERE id=? AND status='draft'",[(string)$f['approved_progress_percentage'],(string)$f['approved_earned_value'],(string)$f['posted_payments_total'],(string)$f['available_payment_amount'],$a['account_code'],$a['name_ar'],$journal,$user,$id]);}
    public function cancel(int$id,int$user):void{$this->db->execute("UPDATE subcontract_payments SET status='cancelled',cancelled_at=NOW(),cancelled_by=? WHERE id=? AND status='draft'",[$user,$id]);}
    public function dataTable(SubcontractPaymentTableQuery$q):array{$w=['py.subcontract_id=?'];$p=[$q->subcontractId];if($q->search!==''){$s='%'.$q->search.'%';$w[]='(py.payment_code LIKE ? OR py.reference_number LIKE ? OR v.name LIKE ? OR p.name LIKE ?)';array_push($p,$s,$s,$s,$s);}foreach(['py.status'=>$q->status,'py.payment_method'=>$q->method]as$f=>$v)if($v!==null){$w[]="$f=?";$p[]=$v;}if($q->dateFrom!==null){$w[]='py.payment_date>=?';$p[]=$q->dateFrom;}if($q->dateTo!==null){$w[]='py.payment_date<=?';$p[]=$q->dateTo;}$c=' WHERE '.implode(' AND ',$w);$total=$this->one('SELECT COUNT(*) total FROM subcontract_payments WHERE subcontract_id=?',[$q->subcontractId]);$filtered=$this->one('SELECT COUNT(*) total FROM subcontract_payments py JOIN vendors v ON v.id=py.vendor_id JOIN projects p ON p.id=py.project_id'.$c,$p);$sort=['payment_code'=>'py.payment_code','payment_date'=>'py.payment_date','vendor_name'=>'v.name','project_name'=>'p.name','amount'=>'py.amount','payment_method'=>'py.payment_method','reference_number'=>'py.reference_number','approved_progress_percentage_snapshot'=>'py.approved_progress_percentage_snapshot','approved_earned_value_snapshot'=>'py.approved_earned_value_snapshot','status'=>'py.status','created_by_name'=>'cu.name','posted_by_name'=>'pu.name'];$r=$this->db->execute('SELECT py.id,py.payment_code,py.payment_date,py.amount,py.payment_method,py.reference_number,py.approved_progress_percentage_snapshot,py.approved_earned_value_snapshot,py.status,v.name vendor_name,p.name project_name,cu.name created_by_name,pu.name posted_by_name FROM subcontract_payments py JOIN vendors v ON v.id=py.vendor_id JOIN projects p ON p.id=py.project_id JOIN users cu ON cu.id=py.created_by LEFT JOIN users pu ON pu.id=py.posted_by'.$c.' ORDER BY '.($sort[$q->sortColumn]??'py.payment_date').' '.$q->sortDirection.',py.id '.$q->sortDirection.' LIMIT ? OFFSET ?',[...$p,$q->length,$q->start]);return['recordsTotal'=>(int)($total['total']??0),'recordsFiltered'=>(int)($filtered['total']??0),'rows'=>$r instanceof \mysqli_result?$r->fetch_all(MYSQLI_ASSOC):[]];}
    private function one(string$sql,array$params=[]):?array{$r=$this->db->execute($sql,$params);$x=$r instanceof \mysqli_result?$r->fetch_assoc():null;return is_array($x)?$x:null;}
}
