<?php $editing=is_array($project);$value=static fn(string $key):string=>(string)($project[$key]??'');$types=['interior_design'=>'تصميم داخلي','fit_out'=>'تجهيز وتشطيب','contracting'=>'مقاولات','renovation'=>'تجديد','maintenance'=>'صيانة','other'=>'أخرى'];?>
<div class="page-header mb-4"><div class="row"><div class="col"><div class="page-pretitle">المشاريع</div><h2 class="page-title"><?=e($title)?></h2></div></div></div>
<form class="card" method="post" action="<?=$editing?'/projects/'.(int)$project['id'].'/edit':'/projects'?>"><div class="card-body"><input type="hidden" name="_token" value="<?=e($csrfToken)?>"><div class="row g-3">
<?php if($editing):?><div class="col-md-4"><label class="form-label">كود المشروع</label><input class="form-control" value="<?=e($value('project_code'))?>" disabled></div><?php endif;?>
<div class="col-md-<?=$editing?'8':'12'?>"><label class="form-label required">اسم المشروع</label><input class="form-control" name="name" maxlength="190" required value="<?=e($value('name'))?>"></div>
<div class="col-md-4"><label class="form-label required">العميل</label><select class="form-select js-tom-select" id="client_id" name="client_id" required><option value="">اختر العميل</option><?php foreach($clients as $c):if(!$c['is_active']&&$value('client_id')!==(string)$c['id'])continue;?><option value="<?=(int)$c['id']?>" <?=$value('client_id')===(string)$c['id']?'selected':''?>><?=e($c['client_code'].' - '.$c['name'])?></option><?php endforeach;?></select></div>
<div class="col-md-4"><label class="form-label">جهة الاتصال الأساسية</label><select class="form-select js-tom-select" id="primary_contact_id" name="primary_contact_id"><option value="">بدون</option><?php foreach($contacts as $c):?><option value="<?=(int)$c['id']?>" <?=$value('primary_contact_id')===(string)$c['id']?'selected':''?>><?=e($c['name'].($c['job_title']?' - '.$c['job_title']:''))?></option><?php endforeach;?></select></div>
<div class="col-md-4"><label class="form-label">مدير المشروع</label><select class="form-select js-tom-select" name="project_manager_id"><option value="">بدون</option><?php foreach($managers as $m):?><option value="<?=(int)$m['id']?>" <?=$value('project_manager_id')===(string)$m['id']?'selected':''?>><?=e($m['name'].' ('.$m['username'].')')?></option><?php endforeach;?></select></div>
<div class="col-md-4"><label class="form-label required">نوع المشروع</label><select class="form-select" name="project_type" required><?php foreach($types as $k=>$v):?><option value="<?=$k?>" <?=$value('project_type')===$k?'selected':''?>><?=$v?></option><?php endforeach;?></select></div>
<?php foreach(['start_date'=>'تاريخ البدء','expected_end_date'=>'تاريخ الانتهاء المتوقع','actual_end_date'=>'تاريخ الانتهاء الفعلي'] as $k=>$v):?><div class="col-md-4"><label class="form-label"><?=$v?></label><input type="date" class="form-control" name="<?=$k?>" value="<?=e($value($k))?>"></div><?php endforeach;?>
<div class="col-md-6"><label class="form-label">المدينة</label><input class="form-control" name="city" maxlength="120" value="<?=e($value('city'))?>"></div><div class="col-md-6"><label class="form-label">المنطقة</label><input class="form-control" name="area" maxlength="120" value="<?=e($value('area'))?>"></div>
<div class="col-12"><label class="form-label">عنوان الموقع</label><textarea class="form-control" name="site_address" maxlength="500" rows="2"><?=e($value('site_address'))?></textarea></div>
<div class="col-12"><label class="form-label">الوصف</label><textarea class="form-control" name="description" maxlength="5000" rows="3"><?=e($value('description'))?></textarea></div>
<div class="col-12"><label class="form-label">ملاحظات</label><textarea class="form-control" name="notes" maxlength="5000" rows="3"><?=e($value('notes'))?></textarea></div>
</div></div><div class="card-footer text-end"><a class="btn btn-link" href="<?=$editing?'/projects/'.(int)$project['id']:'/projects'?>">إلغاء</a><button class="btn btn-primary"><i class="ti ti-device-floppy ms-2"></i>حفظ</button></div></form>
<script src="/assets/js/modules/project-form.js" defer></script>
