<div class="page-header mb-4"><div class="row align-items-center"><div class="col"><div class="page-pretitle">إدارة البيانات الأساسية</div><h2 class="page-title">المشاريع</h2></div><?php if($canCreate):?><div class="col-auto"><a class="btn btn-primary" href="/projects/create"><i class="ti ti-plus ms-2"></i>إضافة مشروع</a></div><?php endif;?></div></div>
<div class="card" id="projects-table-card" data-can-edit="<?=$canEdit?'1':'0'?>" data-can-status="<?=$canChangeStatus?'1':'0'?>">
<div class="card-body border-bottom"><div class="row g-3">
<div class="col-md-3"><label class="form-label">العميل</label><select id="project-client-filter" class="form-select js-tom-select"><option value="">الكل</option><?php foreach($clients as $c):?><option value="<?=(int)$c['id']?>"><?=e($c['name'])?></option><?php endforeach;?></select></div>
<div class="col-md-3"><label class="form-label">النوع</label><select id="project-type-filter" class="form-select"><option value="">الكل</option><?php foreach(['interior_design'=>'تصميم داخلي','fit_out'=>'تجهيز وتشطيب','contracting'=>'مقاولات','renovation'=>'تجديد','maintenance'=>'صيانة','other'=>'أخرى'] as $k=>$v):?><option value="<?=$k?>"><?=$v?></option><?php endforeach;?></select></div>
<div class="col-md-3"><label class="form-label">الحالة</label><select id="project-status-filter" class="form-select"><option value="">الكل</option><?php foreach(['planning'=>'تخطيط','active'=>'نشط','on_hold'=>'معلق','completed'=>'مكتمل','cancelled'=>'ملغي'] as $k=>$v):?><option value="<?=$k?>"><?=$v?></option><?php endforeach;?></select></div>
<div class="col-md-3"><label class="form-label">مدير المشروع</label><select id="project-manager-filter" class="form-select js-tom-select"><option value="">الكل</option><?php foreach($managers as $m):?><option value="<?=(int)$m['id']?>"><?=e($m['name'])?></option><?php endforeach;?></select></div>
</div></div><div class="table-responsive p-3"><table id="projects-table" class="table table-vcenter card-table w-100"><thead><tr><th>كود المشروع</th><th>اسم المشروع</th><th>العميل</th><th>النوع</th><th>مدير المشروع</th><th>تاريخ البدء</th><th>الانتهاء المتوقع</th><th>الحالة</th><th>الإجراءات</th></tr></thead></table></div></div>
<script src="/assets/js/modules/projects.js" defer></script>
