<?php $id=(int)$project['id'];$types=['interior_design'=>'تصميم داخلي','fit_out'=>'تجهيز وتشطيب','contracting'=>'مقاولات','renovation'=>'تجديد','maintenance'=>'صيانة','other'=>'أخرى'];$statuses=['planning'=>'تخطيط','active'=>'نشط','on_hold'=>'معلق','completed'=>'مكتمل','cancelled'=>'ملغي'];?>
<div class="page-header mb-4"><div class="row align-items-center"><div class="col"><div class="page-pretitle"><?=e($project['project_code'])?></div><h2 class="page-title"><?=e($project['name'])?></h2></div><div class="col-auto d-flex gap-2"><?php if($canEdit):?><a class="btn btn-primary" href="/projects/<?=$id?>/edit"><i class="ti ti-edit ms-2"></i>تعديل</a><?php endif;?><a class="btn" href="/projects">العودة</a></div></div></div>
<div class="row g-4"><div class="col-lg-8"><div class="card"><div class="card-header"><h3 class="card-title">بيانات المشروع</h3></div><div class="card-body"><dl class="row mb-0">
<?php foreach(['project_code'=>'كود المشروع','name'=>'اسم المشروع','client_name'=>'العميل','contact_name'=>'جهة الاتصال','manager_name'=>'مدير المشروع','project_type'=>'النوع','start_date'=>'تاريخ البدء','expected_end_date'=>'الانتهاء المتوقع','actual_end_date'=>'الانتهاء الفعلي','city'=>'المدينة','area'=>'المنطقة','site_address'=>'عنوان الموقع'] as $k=>$label):?><dt class="col-sm-4 mb-2"><?=$label?></dt><dd class="col-sm-8 mb-2"><?=e($k==='project_type'?($types[$project[$k]]??'—'):($project[$k]?:'—'))?></dd><?php endforeach;?>
</dl><?php if($project['description']):?><hr><h4>الوصف</h4><p class="text-secondary"><?=nl2br(e($project['description']))?></p><?php endif;?><?php if($project['notes']):?><h4>ملاحظات</h4><p class="text-secondary"><?=nl2br(e($project['notes']))?></p><?php endif;?></div></div></div>
<div class="col-lg-4"><div class="card"><div class="card-header"><h3 class="card-title">حالة المشروع</h3></div><div class="card-body"><span class="badge bg-blue-lt mb-3"><?=e($statuses[$project['status']]??$project['status'])?></span>
<?php if($canChangeStatus&&$transitions!==[]):?><form class="js-project-status-form" method="post" action="/projects/<?=$id?>/status"><input type="hidden" name="_token" value="<?=e($csrfToken)?>"><label class="form-label required">الحالة الجديدة</label><select class="form-select mb-3" name="status" required><?php foreach($transitions as $s):?><option value="<?=$s?>"><?=e($statuses[$s])?></option><?php endforeach;?></select><button class="btn btn-primary w-100">تغيير الحالة</button></form><?php elseif($transitions===[]):?><p class="text-secondary mb-0">هذه حالة نهائية ولا تتوفر انتقالات أخرى.</p><?php endif;?>
</div></div></div></div>
<script src="/assets/js/modules/project-status.js" defer></script>
<?php if($canViewCosts):?><div class="card mt-4"><div class="card-body d-flex align-items-center"><div class="flex-fill"><h3 class="card-title mb-1">التكاليف الفعلية</h3><div class="text-secondary">عرض سجل التكلفة الفعلية المعتمدة للمشروع.</div></div><a class="btn btn-primary" href="/projects/<?=$id?>/costs">فتح سجل التكاليف</a></div></div><?php endif;?>
