<?php
declare(strict_types=1);
namespace App\Modules\SupplierInvoices\Services;
use App\Core\Auth\Auth;
use App\Core\Database\Database;
use App\Core\Exceptions\BusinessRuleException;
use App\Modules\SupplierInvoices\DTOs\SupplierInvoiceData;
use App\Modules\SupplierInvoices\DTOs\SupplierInvoiceTableQuery;
use App\Modules\SupplierInvoices\Repositories\SupplierInvoiceRepository;
use App\Shared\Numbering\NumberGeneratorService;
final class SupplierInvoiceService
{
    private const PROJECT_STATUSES=['planning','active','on_hold','completed'];
    public function __construct(private readonly SupplierInvoiceRepository $invoices,private readonly NumberGeneratorService $numbers,private readonly Database $database,private readonly Auth $auth) {}
    public function find(int $id):array{return $this->invoices->find($id)??throw new BusinessRuleException('فاتورة المورد غير موجودة.');}
    public function details(int $id):array{return ['invoice'=>$this->find($id),'lines'=>$this->invoices->lines($id),'displayTotal'=>$this->invoices->total($id)];}
    public function save(SupplierInvoiceData $data,?int $id=null):int{return $this->database->transaction(function()use($data,$id){$old=$id===null?null:$this->invoices->find($id,true);if($id!==null&&$old===null)throw new BusinessRuleException('فاتورة المورد غير موجودة.');if($old!==null&&$old['status']!=='draft')throw new BusinessRuleException('يمكن تعديل مسودة الفاتورة فقط.');if($old!==null&&$this->year((string)$old['invoice_code'])!==substr($data->invoiceDate,0,4))throw new BusinessRuleException('لا يمكن تغيير سنة تاريخ الفاتورة. ألغِ المسودة وأنشئ فاتورة جديدة.');$this->validateMasters($data,false);$this->validatePurchaseOrder($data,false);if($this->invoices->numberExists($data->vendorId,$data->invoiceNumber,$id))throw new BusinessRuleException('رقم الفاتورة مستخدم بالفعل لهذا المورد.');if($id===null)$id=$this->invoices->create($this->numbers->nextSupplierInvoiceCode((int)substr($data->invoiceDate,0,4)),$data,$this->user());else $this->invoices->update($id,$data);$this->invoices->syncLines($id,$data->lines);$this->assertTotalFits($id);return $id;});}
    public function approve(int $id):void
    {
        $probe=$this->find($id);$expectedPurchaseOrderId=$probe['purchase_order_id']===null?null:(int)$probe['purchase_order_id'];
        $this->database->transaction(function()use($id,$probe,$expectedPurchaseOrderId){$projectId=(int)$probe['project_id'];$project=$this->invoices->project($projectId,true)??throw new BusinessRuleException('المشروع غير موجود.');$invoice=$this->invoices->findForProject($id,$projectId,true)??throw new BusinessRuleException('تغير مشروع الفاتورة أثناء العملية. أعد المحاولة.');if((int)$invoice['project_id']!==$projectId)throw new BusinessRuleException('تغير مشروع الفاتورة أثناء العملية. أعد المحاولة.');$currentPurchaseOrderId=$invoice['purchase_order_id']===null?null:(int)$invoice['purchase_order_id'];if($currentPurchaseOrderId!==$expectedPurchaseOrderId)throw new BusinessRuleException('تغير ربط أمر الشراء أثناء العملية. أعد المحاولة.');if($invoice['status']!=='draft')throw new BusinessRuleException('يمكن اعتماد مسودة الفاتورة فقط.');$vendor=$this->invoices->vendor((int)$invoice['vendor_id'],true)??throw new BusinessRuleException('المورد غير موجود.');if(!(bool)$vendor['is_active']||!in_array($vendor['vendor_type'],['supplier','both'],true))throw new BusinessRuleException('المورد غير نشط أو غير مصنف كمورد.');if(!in_array($project['status'],self::PROJECT_STATUSES,true))throw new BusinessRuleException('حالة المشروع لا تسمح باعتماد فاتورة مورد.');
            $purchaseOrder=null;if($currentPurchaseOrderId!==null){$purchaseOrder=$this->invoices->purchaseOrder($currentPurchaseOrderId,true)??throw new BusinessRuleException('أمر الشراء المرتبط غير موجود.');$this->assertPurchaseOrderMatches($purchaseOrder,(int)$invoice['vendor_id'],(int)$invoice['project_id']);}
            $lines=$this->invoices->lines($id,true);if($lines===[])throw new BusinessRuleException('لا يمكن اعتماد فاتورة بلا بنود.');$ids=array_values(array_unique(array_map('intval',array_column($lines,'cost_code_id'))));sort($ids);$masters=$this->invoices->costCodes($ids,true);$byId=array_column($masters,null,'id');if(count($byId)!==count($ids))throw new BusinessRuleException('أحد أكواد التكلفة غير موجود.');$summary=$this->assertTotalFits($id);foreach($lines as $line){$master=$byId[$line['cost_code_id']]??null;if($master===null||!(bool)$master['cost_code_active']||!(bool)$master['section_active'])throw new BusinessRuleException('أحد أكواد التكلفة أو أقسام الأعمال غير نشط.');if($this->invoices->sourceCostExists($id,(int)$line['id']))throw new BusinessRuleException('تم إنشاء تكلفة لأحد بنود الفاتورة مسبقًا.');}if($summary['total']==='0.00')throw new BusinessRuleException('إجمالي الفاتورة يجب أن يكون أكبر من صفر.');$user=$this->user();foreach($lines as $line){$master=$byId[$line['cost_code_id']];$this->invoices->createCost($this->numbers->nextProjectActualCostCode((int)substr((string)$invoice['invoice_date'],0,4)),$invoice,$line,$master,$user);$this->invoices->freezeLine((int)$line['id'],$master);}$this->invoices->approve($id,$summary['total'],$vendor,$project,$purchaseOrder===null?null:(string)$purchaseOrder['po_code'],$user);$verified=$this->invoices->find($id,true);if(($verified['status']??null)!=='approved')throw new \RuntimeException('Supplier invoice approval failed.');
        });
    }
    public function cancel(int $id):void{$probe=$this->find($id);$this->database->transaction(function()use($id,$probe){$projectId=(int)$probe['project_id'];$this->invoices->project($projectId,true)??throw new BusinessRuleException('المشروع غير موجود.');$invoice=$this->invoices->findForProject($id,$projectId,true)??throw new BusinessRuleException('تغير مشروع الفاتورة أثناء العملية. أعد المحاولة.');if((int)$invoice['project_id']!==$projectId)throw new BusinessRuleException('تغير مشروع الفاتورة أثناء العملية. أعد المحاولة.');if($invoice['status']!=='draft')throw new BusinessRuleException('يمكن إلغاء مسودة الفاتورة فقط.');$this->invoices->cancel($id,$this->user());});}
    private function validateMasters(SupplierInvoiceData $data,bool $lock):void{$vendor=$this->invoices->vendor($data->vendorId,$lock);if($vendor===null||!(bool)$vendor['is_active']||!in_array($vendor['vendor_type'],['supplier','both'],true))throw new BusinessRuleException('اختر موردًا نشطًا ومصنفًا كمورد.');$project=$this->invoices->project($data->projectId,$lock);if($project===null||!in_array($project['status'],self::PROJECT_STATUSES,true))throw new BusinessRuleException('اختر مشروعًا صالحًا غير ملغي.');$ids=array_values(array_unique(array_map('intval',array_column($data->lines,'cost_code_id'))));sort($ids);$codes=$this->invoices->costCodes($ids,$lock);if(count($codes)!==count($ids))throw new BusinessRuleException('أحد أكواد التكلفة غير موجود.');foreach($codes as $code)if(!(bool)$code['cost_code_active']||!(bool)$code['section_active'])throw new BusinessRuleException('اختر أكواد تكلفة نشطة ضمن أقسام نشطة.');}
    private function validatePurchaseOrder(SupplierInvoiceData $data,bool $lock):void{if($data->purchaseOrderId===null)return;$purchaseOrder=$this->invoices->purchaseOrder($data->purchaseOrderId,$lock)??throw new BusinessRuleException('أمر الشراء المحدد غير موجود.');$this->assertPurchaseOrderMatches($purchaseOrder,$data->vendorId,$data->projectId);}
    private function assertPurchaseOrderMatches(array $purchaseOrder,int $vendorId,int $projectId):void{if($purchaseOrder['status']!=='approved')throw new BusinessRuleException('يمكن ربط فاتورة المورد بأمر شراء معتمد فقط.');if((int)$purchaseOrder['vendor_id']!==$vendorId)throw new BusinessRuleException('مورد أمر الشراء لا يطابق مورد الفاتورة.');if((int)$purchaseOrder['project_id']!==$projectId)throw new BusinessRuleException('مشروع أمر الشراء لا يطابق مشروع الفاتورة.');}
    /** @return array{total:string,fits:bool} */
    private function assertTotalFits(int $id):array{$summary=$this->invoices->totalSummary($id);if(!$summary['fits'])throw new BusinessRuleException('إجمالي فاتورة المورد يتجاوز الحد الأقصى المسموح DECIMAL(18,2).');return $summary;}
    public function purchaseOrderPrefill(int $id):array{$purchaseOrder=$this->invoices->purchaseOrder($id)??throw new BusinessRuleException('أمر الشراء غير موجود.');if($purchaseOrder['status']!=='approved')throw new BusinessRuleException('يمكن إنشاء فاتورة من أمر شراء معتمد فقط.');return $purchaseOrder;}
    private function year(string $code):string{return preg_match('/^SINV-(\d{4})-/',$code,$matches)?$matches[1]:'';}
    private function user():int{return $this->auth->id()??throw new BusinessRuleException('تعذر تحديد المستخدم الحالي.');}
    public function references():array{return $this->invoices->references();}
    public function dataTable(SupplierInvoiceTableQuery $query):array{$result=$this->invoices->dataTable($query);return ['draw'=>$query->draw,'recordsTotal'=>$result['recordsTotal'],'recordsFiltered'=>$result['recordsFiltered'],'data'=>$result['rows']];}
}
