<?php $editing=is_array($contract);$locked=$editing&&$contract['status']!=='draft';$v=static fn(string $k):string=>(string)($contract[$k]??'');$methods=['cost_plus'=>'تكلفة فعلية + نسبة','boq'=>'جدول كميات','lump_sum'=>'مقطوعية'];?>
<div class="page-header mb-4"><h2 class="page-title"><?=e($title)?></h2></div><?php if($locked):?><div class="alert alert-info">العقد معتمد تجاريًا؛ الحقول التجارية محمية، ويمكن تعديل البيانات الإدارية فقط.</div><?php endif;?>
<form class="card" method="post" action="<?=$editing?'/contracts/'.(int)$contract['id'].'/edit':'/contracts'?>" id="contract-form"><div class="card-body"><input type="hidden" name="_token" value="<?=e($csrfToken)?>"><?php if($editing):?><div class="row mb-3"><div class="col-md-6"><label class="form-label">الكود الداخلي</label><input class="form-control" disabled value="<?=e($v('contract_code'))?>"></div><div class="col-md-6"><label class="form-label">الحالة</label><input class="form-control" disabled value="<?=e($v('status'))?>"></div></div><?php endif;?><div class="row g-3">
<div class="col-md-6"><label class="form-label required">المشروع</label><select class="form-select js-tom-select" id="contract-project" name="project_id" <?=$editing?'disabled':''?> required><option value="">اختر المشروع</option><?php foreach($projects as $p):?><option value="<?=(int)$p['id']?>" data-client-id="<?=(int)$p['client_id']?>" data-client-name="<?=e($p['client_code'].' - '.$p['client_name'])?>" <?=$v('project_id')===(string)$p['id']?'selected':''?>><?=e($p['project_code'].' - '.$p['name'])?></option><?php endforeach;?></select><?php if($editing):?><input type="hidden" name="project_id" value="<?=e($v('project_id'))?>"><?php endif;?></div>
<div class="col-md-6"><label class="form-label required">العميل</label><input id="contract-client-name" class="form-control" readonly value="<?=e($editing?$v('client_code').' - '.$v('client_name'):'')?>"><input type="hidden" id="contract-client-id" name="client_id" value="<?=e($v('client_id'))?>"></div>
<div class="col-md-6"><label class="form-label">جهة الاتصال</label><select class="form-select js-tom-select" id="contract-contact" name="client_contact_id"><option value="">بدون</option><?php foreach($contacts as $c):?><option value="<?=(int)$c['id']?>" <?=$v('client_contact_id')===(string)$c['id']?'selected':''?>><?=e($c['name'].($c['job_title']?' - '.$c['job_title']:''))?></option><?php endforeach;?></select></div>
<div class="col-md-6"><label class="form-label required">عنوان العقد</label><input class="form-control" name="title" maxlength="190" required value="<?=e($v('title'))?>" <?=$locked?'readonly':''?>></div>
<div class="col-md-4"><label class="form-label">رقم العقد التجاري</label><input class="form-control" name="contract_number" maxlength="100" value="<?=e($v('contract_number'))?>" <?=$locked?'readonly':''?>><small class="text-secondary">اختياري للمسودة ومطلوب قبل التفعيل.</small></div>
<div class="col-md-4"><label class="form-label required">طريقة التسعير</label><select class="form-select" id="pricing-method" name="pricing_method" <?=$locked?'disabled':''?> required><?php foreach($methods as $key=>$label):?><option value="<?=$key?>" <?=$v('pricing_method')===$key?'selected':''?>><?=$label?></option><?php endforeach;?></select><?php if($locked):?><input type="hidden" name="pricing_method" value="<?=e($v('pricing_method'))?>"><?php endif;?></div>
<div class="col-md-4"><label class="form-label required">تاريخ العقد</label><input type="date" class="form-control" name="contract_date" required value="<?=e($v('contract_date'))?>" <?=$locked?'readonly':''?>></div>
<div class="col-md-4"><label class="form-label">تاريخ البدء</label><input type="date" class="form-control" name="start_date" value="<?=e($v('start_date'))?>"></div><div class="col-md-4"><label class="form-label">تاريخ الانتهاء المتوقع</label><input type="date" class="form-control" name="expected_end_date" value="<?=e($v('expected_end_date'))?>"></div>
<div class="col-md-4"><label class="form-label">قيمة العقد</label><input type="number" step="0.01" min="0" class="form-control" id="contract-value" name="contract_value" value="<?=e($v('contract_value'))?>" <?=$locked?'readonly':''?>></div><div class="col-md-4"><label class="form-label">نسبة الزيادة %</label><input type="number" step="0.0001" min="0.0001" class="form-control" id="markup-percentage" name="markup_percentage" value="<?=e($v('markup_percentage'))?>" <?=$locked?'readonly':''?>></div>
<div class="col-12"><label class="form-label">الوصف</label><textarea class="form-control" name="description" maxlength="5000" rows="3" <?=$locked?'readonly':''?>><?=e($v('description'))?></textarea></div><div class="col-12"><label class="form-label">الشروط</label><textarea class="form-control" name="terms" maxlength="10000" rows="5" <?=$locked?'readonly':''?>><?=e($v('terms'))?></textarea></div><div class="col-12"><label class="form-label">ملاحظات</label><textarea class="form-control" name="notes" maxlength="5000" rows="3"><?=e($v('notes'))?></textarea></div>
</div></div><div class="card-footer text-end"><a class="btn btn-link" href="<?=$editing?'/contracts/'.(int)$contract['id']:'/contracts'?>">إلغاء</a><button class="btn btn-primary">حفظ</button></div></form><script src="/assets/js/modules/client-contract-form.js" defer></script>
