<?php $editing=is_array($statement??null);$isBoq=$contract['pricing_method']==='boq';?>
<div class="page-header mb-4"><div class="row"><div class="col"><div class="page-pretitle"><?=e($contract['contract_code'])?></div><h2 class="page-title"><?=$editing?'تعديل مسودة المستخلص':'إنشاء مستخلص عميل'?></h2></div></div></div>
<form method="post" action="<?=$editing?'/client-progress-statements/'.(int)$statement['id'].'/edit':'/client-contracts/'.(int)$contract['id'].'/progress-statements'?>" id="cps-form" data-method="<?=e($contract['pricing_method'])?>" data-markup="<?=e((string)$contract['markup_percentage'])?>"><input type="hidden" name="_token" value="<?=e($csrfToken)?>">
<div class="card mb-4"><div class="card-header"><h3 class="card-title">بيانات المستخلص</h3></div><div class="card-body"><div class="row g-3"><div class="col-md-4"><label class="form-label">العقد</label><input class="form-control" value="<?=e($contract['contract_code'].' - '.$contract['title'])?>" disabled></div><div class="col-md-4"><label class="form-label">المشروع</label><input class="form-control" value="<?=e($contract['project_code'].' - '.$contract['project_name'])?>" disabled></div><div class="col-md-4"><label class="form-label">العميل</label><input class="form-control" value="<?=e($contract['client_name'])?>" disabled></div><div class="col-md-3"><label class="form-label required">تاريخ المستخلص</label><input class="form-control" type="date" name="statement_date" value="<?=e((string)($statement['statement_date']??date('Y-m-d')))?>" required></div><div class="col-md-3"><label class="form-label">من</label><input class="form-control" type="date" name="period_from" value="<?=e((string)($statement['period_from']??''))?>"></div><div class="col-md-3"><label class="form-label">إلى</label><input class="form-control" type="date" name="period_to" value="<?=e((string)($statement['period_to']??''))?>"></div><div class="col-md-3"><label class="form-label">رقم المستخلص</label><input class="form-control" name="statement_number" maxlength="100" value="<?=e((string)($statement['statement_number']??''))?>"></div><div class="col-12"><label class="form-label">ملاحظات</label><textarea class="form-control" name="notes" rows="2"><?=e((string)($statement['notes']??''))?></textarea></div></div></div></div>
<?php if($isBoq):?>
<div class="card mb-4"><div class="card-header"><h3 class="card-title">بنود جدول الكميات المعتمد</h3></div><div class="table-responsive"><table class="table table-vcenter"><thead><tr><th>البند</th><th>الوحدة</th><th>كمية العقد</th><th>السابق</th><th>الحالي</th><th>التراكمي</th><th>سعر الوحدة</th><th>قيمة الحالي</th></tr></thead><tbody><?php $lastSection=null;foreach($boqItems as$item):?><?php if($lastSection!==$item['section_code']):$lastSection=$item['section_code'];?><tr class="table-active"><th colspan="8"><?=e($item['section_code'].' - '.$item['section_title'])?></th></tr><?php endif;?><tr><td><?=e(($item['item_code']?$item['item_code'].' - ':'').$item['description'])?></td><td><?=e(trim((string)($item['unit_name']??'').' '.(string)($item['unit_symbol']??''))?:'—')?></td><td class="cps-contract-qty"><?=e((string)$item['contract_quantity'])?></td><td class="cps-previous-qty"><?=e((string)$item['display_previous_quantity'])?></td><td><input class="form-control cps-boq-quantity" type="text" inputmode="decimal" name="boq_quantities[<?=(int)$item['contract_boq_item_id']?>]" value="<?=e((string)$item['current_quantity'])?>" data-rate="<?=e((string)$item['unit_rate'])?>"></td><td class="cps-cumulative-qty">—</td><td><?=decimal_format($item['unit_rate'])?></td><td class="cps-current-amount">0.00</td></tr><?php endforeach;?><?php if(!$boqItems):?><tr><td colspan="8" class="text-center text-secondary py-4">لا توجد بنود في جدول كميات معتمد.</td></tr><?php endif;?></tbody></table></div></div>
<?php else:?>
<div class="card mb-4"><div class="card-header d-flex"><h3 class="card-title">التكاليف الفعلية المستحقة</h3><button type="button" class="btn btn-sm me-auto" id="select-all-costs">تحديد كل المؤهل</button></div><div class="table-responsive"><table class="table table-vcenter"><thead><tr><th></th><th>التاريخ</th><th>القسم / الكود</th><th>المورد</th><th>الوصف</th><th>المرجع</th><th>المبلغ</th></tr></thead><tbody><?php foreach($costs as$x):?><tr><td><input class="form-check-input cps-cost" type="checkbox" name="cost_ids[]" value="<?=(int)$x['id']?>" data-amount="<?=e($x['amount'])?>" <?=!empty($x['selected'])?'checked':''?>></td><td><?=e($x['cost_date'])?></td><td><?=e($x['section_code'].' / '.$x['cost_code'])?></td><td><?=e($x['vendor_name']??'—')?></td><td><?=e($x['description'])?></td><td><?=e($x['reference_number']??'—')?></td><td><?=decimal_format($x['amount'])?></td></tr><?php endforeach;?></tbody></table></div></div>
<?php endif;?>
<div class="card mb-4"><div class="card-header"><h3 class="card-title">الأعمال الإضافية / التعديلات المعتمدة</h3></div><div class="table-responsive"><table class="table table-vcenter"><thead><tr><th>التعديل</th><th>الأثر</th><th>المعتمد</th><th>السابق</th><th>المتبقي</th><th>الحالي</th></tr></thead><tbody><?php foreach($variations as$v):?><tr><td><?=e($v['variation_code'].' - '.$v['title'])?></td><td><?=$v['amount_effect']==='increase'?'زيادة':'خصم'?></td><td><?=decimal_format($v['amount'])?></td><td><?=decimal_format($v['previous_billed_amount'])?></td><td><?=decimal_format($v['remaining_amount'])?></td><td><input class="form-control cps-variation" type="text" inputmode="decimal" name="variations[<?=(int)$v['id']?>]" value="<?=e((string)($v['current_billed_amount']??''))?>" data-effect="<?=e($v['amount_effect'])?>"></td></tr><?php endforeach;?></tbody></table></div></div>
<div class="card mb-4 bg-blue-lt"><div class="card-body"><h3>الملخص التقديري</h3><div class="row g-3"><div class="col-md"><div class="text-secondary"><?=$isBoq?'قيمة BOQ الحالية':'التكاليف الحالية'?></div><strong id="sum-cost">0.00</strong></div><?php if(!$isBoq):?><div class="col-md"><div class="text-secondary">Markup</div><strong id="sum-markup">0.00</strong></div><?php endif;?><div class="col-md"><div class="text-secondary">التعديلات</div><strong id="sum-variations">0.00</strong></div><div class="col-md"><div class="text-secondary">المستخلص الحالي</div><strong id="sum-total">0.00</strong></div></div><div class="small text-secondary mt-3">المعاينة إرشادية؛ حساب الخادم باستخدام DECIMAL عند الاعتماد هو المرجع المالي.</div></div></div>
<div class="d-flex gap-2"><button class="btn btn-primary" type="submit">حفظ المسودة</button><a class="btn" href="<?=$editing?'/client-progress-statements/'.(int)$statement['id']:'/client-contracts/'.(int)$contract['id'].'/progress-statements'?>">رجوع</a></div></form>
<script src="/assets/js/modules/client-progress-statement-form.js" defer></script>
