<?php
declare(strict_types=1);
namespace App\Modules\ClientContracts\Repositories;
use App\Core\Database\Database;use App\Modules\ClientContracts\DTOs\ClientContractData;use App\Modules\ClientContracts\DTOs\ClientContractTableQuery;
final class ClientContractRepository
{
 public function __construct(private readonly Database $db){}
 public function find(int $id):?array{$sql="SELECT cc.*,p.project_code,p.name project_name,COALESCE(c.company_name,c.name) client_name,c.client_code,ct.name contact_name FROM client_contracts cc JOIN projects p ON p.id=cc.project_id JOIN clients c ON c.id=cc.client_id LEFT JOIN client_contacts ct ON ct.id=cc.client_contact_id WHERE cc.id=? LIMIT 1";$r=$this->db->execute($sql,[$id]);$row=$r instanceof \mysqli_result?$r->fetch_assoc():null;return is_array($row)?$row:null;}
 public function project(int $id):?array{$r=$this->db->execute('SELECT p.id,p.project_code,p.name,p.client_id,COALESCE(c.company_name,c.name) client_name,c.client_code FROM projects p JOIN clients c ON c.id=p.client_id WHERE p.id=? LIMIT 1',[$id]);$row=$r instanceof \mysqli_result?$r->fetch_assoc():null;return is_array($row)?$row:null;}
 public function contractForProject(int $projectId,?int $exceptId=null):bool{$sql='SELECT 1 FROM client_contracts WHERE project_id=?'.($exceptId===null?'':' AND id<>?').' LIMIT 1';$params=$exceptId===null?[$projectId]:[$projectId,$exceptId];return $this->exists($sql,$params);}
 public function numberExists(string $number,?int $exceptId=null):bool{$sql='SELECT 1 FROM client_contracts WHERE contract_number=?'.($exceptId===null?'':' AND id<>?').' LIMIT 1';$params=$exceptId===null?[$number]:[$number,$exceptId];return $this->exists($sql,$params);}
 public function contactBelongsTo(int $contactId,int $clientId):bool{return $this->exists('SELECT 1 FROM client_contacts WHERE id=? AND client_id=? LIMIT 1',[$contactId,$clientId]);}
 public function create(string $code,ClientContractData $d):int{$sql='INSERT INTO client_contracts(contract_code,contract_number,project_id,client_id,client_contact_id,pricing_method,contract_date,start_date,expected_end_date,contract_value,markup_percentage,title,description,terms,notes,status) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,\'draft\')';$this->db->execute($sql,[$code,$d->contractNumber,$d->projectId,$d->clientId,$d->clientContactId,$d->pricingMethod,$d->contractDate,$d->startDate,$d->expectedEndDate,$d->contractValue,$d->markupPercentage,$d->title,$d->description,$d->terms,$d->notes]);return (int)$this->db->connection()->insert_id;}
 public function updateDraft(int $id,ClientContractData $d):void{$this->db->execute('UPDATE client_contracts SET contract_number=?,client_id=?,client_contact_id=?,pricing_method=?,contract_date=?,start_date=?,expected_end_date=?,contract_value=?,markup_percentage=?,title=?,description=?,terms=?,notes=? WHERE id=?',[$d->contractNumber,$d->clientId,$d->clientContactId,$d->pricingMethod,$d->contractDate,$d->startDate,$d->expectedEndDate,$d->contractValue,$d->markupPercentage,$d->title,$d->description,$d->terms,$d->notes,$id]);}
 public function updateAdministrative(int $id,ClientContractData $d):void{$this->db->execute('UPDATE client_contracts SET client_contact_id=?,start_date=?,expected_end_date=?,notes=? WHERE id=?',[$d->clientContactId,$d->startDate,$d->expectedEndDate,$d->notes,$id]);}
 public function changeStatus(int $id,string $status):void{$this->db->execute('UPDATE client_contracts SET status=? WHERE id=?',[$status,$id]);}
 public function references(?int $currentId=null):array{$sql='SELECT p.id,p.project_code,p.name,p.client_id,COALESCE(c.company_name,c.name) client_name,c.client_code FROM projects p JOIN clients c ON c.id=p.client_id LEFT JOIN client_contracts cc ON cc.project_id=p.id WHERE cc.id IS NULL'.($currentId===null?'':' OR cc.id=?').' ORDER BY p.project_code';$r=$this->db->execute($sql,$currentId===null?[]:[$currentId]);$projects=$r instanceof \mysqli_result?$r->fetch_all(MYSQLI_ASSOC):[];$r=$this->db->execute('SELECT id,client_code,COALESCE(company_name,name) name FROM clients ORDER BY COALESCE(company_name,name)');return ['projects'=>$projects,'clients'=>$r instanceof \mysqli_result?$r->fetch_all(MYSQLI_ASSOC):[]];}
 public function filterReferences():array{$r=$this->db->execute('SELECT id,project_code,name FROM projects ORDER BY project_code');$projects=$r instanceof \mysqli_result?$r->fetch_all(MYSQLI_ASSOC):[];$r=$this->db->execute('SELECT id,client_code,COALESCE(company_name,name) name FROM clients ORDER BY COALESCE(company_name,name)');return ['projects'=>$projects,'clients'=>$r instanceof \mysqli_result?$r->fetch_all(MYSQLI_ASSOC):[]];}
 public function contactsForProject(int $projectId):array{$r=$this->db->execute('SELECT ct.id,ct.name,ct.job_title FROM projects p JOIN client_contacts ct ON ct.client_id=p.client_id WHERE p.id=? ORDER BY ct.is_primary DESC,ct.name',[$projectId]);return $r instanceof \mysqli_result?$r->fetch_all(MYSQLI_ASSOC):[];}
 public function dataTable(ClientContractTableQuery $q):array{$from=' FROM client_contracts cc JOIN projects p ON p.id=cc.project_id JOIN clients c ON c.id=cc.client_id';$parts=[];$params=[];if($q->search!==''){$s='%'.$q->search.'%';$parts[]='(cc.contract_code LIKE ? OR cc.contract_number LIKE ? OR cc.title LIKE ? OR p.name LIKE ? OR COALESCE(c.company_name,c.name) LIKE ?)';array_push($params,$s,$s,$s,$s,$s);}foreach(['cc.project_id'=>$q->projectId,'cc.client_id'=>$q->clientId,'cc.pricing_method'=>$q->pricingMethod,'cc.status'=>$q->status] as $f=>$v){if($v!==null){$parts[]="$f=?";$params[]=$v;}}if($q->year!==null){$parts[]='YEAR(cc.contract_date)=?';$params[]=$q->year;}$where=$parts?' WHERE '.implode(' AND ',$parts):'';$t=$this->db->execute('SELECT COUNT(*) total FROM client_contracts');$f=$this->db->execute('SELECT COUNT(*) total'.$from.$where,$params);$sort=['contract_code'=>'cc.contract_code','contract_number'=>'cc.contract_number','project_name'=>'p.name','client_name'=>'COALESCE(c.company_name,c.name)','pricing_method'=>'cc.pricing_method','contract_date'=>'cc.contract_date','contract_value'=>'cc.contract_value','markup_percentage'=>'cc.markup_percentage','status'=>'cc.status'];$sql='SELECT cc.id,cc.contract_code,cc.contract_number,cc.title,p.name project_name,COALESCE(c.company_name,c.name) client_name,cc.pricing_method,cc.contract_date,cc.contract_value,cc.markup_percentage,cc.status'.$from.$where.' ORDER BY '.($sort[$q->sortColumn]??'cc.contract_code').' '.$q->sortDirection.' LIMIT ? OFFSET ?';$r=$this->db->execute($sql,[...$params,$q->length,$q->start]);return ['recordsTotal'=>(int)(($t instanceof \mysqli_result?$t->fetch_assoc():[])['total']??0),'recordsFiltered'=>(int)(($f instanceof \mysqli_result?$f->fetch_assoc():[])['total']??0),'rows'=>$r instanceof \mysqli_result?$r->fetch_all(MYSQLI_ASSOC):[]];}
 private function exists(string $sql,array $params):bool{$r=$this->db->execute($sql,$params);return $r instanceof \mysqli_result&&$r->num_rows>0;}
}
