<?php
declare(strict_types=1);
namespace App\Modules\SupplierInvoices\Repositories;
use App\Core\Database\Database;
use App\Modules\SupplierInvoices\DTOs\SupplierInvoiceData;
use App\Modules\SupplierInvoices\DTOs\SupplierInvoiceTableQuery;
final class SupplierInvoiceRepository
{
    public function __construct(private readonly Database $database) {}
    public function find(int $id,bool $lock=false):?array{return $this->one("SELECT i.*,v.vendor_code current_vendor_code,v.name current_vendor_name,p.project_code current_project_code,p.name current_project_name,po.po_code current_purchase_order_code,cu.name created_by_name,au.name approved_by_name,xu.name cancelled_by_name FROM supplier_invoices i JOIN vendors v ON v.id=i.vendor_id JOIN projects p ON p.id=i.project_id LEFT JOIN purchase_orders po ON po.id=i.purchase_order_id JOIN users cu ON cu.id=i.created_by LEFT JOIN users au ON au.id=i.approved_by LEFT JOIN users xu ON xu.id=i.cancelled_by WHERE i.id=? LIMIT 1".($lock?' FOR UPDATE':''),[$id]);}
    public function findForProject(int $id,int $projectId,bool $lock=false):?array{return $this->one("SELECT i.*,v.vendor_code current_vendor_code,v.name current_vendor_name,p.project_code current_project_code,p.name current_project_name,po.po_code current_purchase_order_code,cu.name created_by_name,au.name approved_by_name,xu.name cancelled_by_name FROM supplier_invoices i JOIN vendors v ON v.id=i.vendor_id JOIN projects p ON p.id=i.project_id LEFT JOIN purchase_orders po ON po.id=i.purchase_order_id JOIN users cu ON cu.id=i.created_by LEFT JOIN users au ON au.id=i.approved_by LEFT JOIN users xu ON xu.id=i.cancelled_by WHERE i.id=? AND i.project_id=? LIMIT 1".($lock?' FOR UPDATE':''),[$id,$projectId]);}
    public function vendor(int $id,bool $lock=false):?array{return $this->one('SELECT id,vendor_code,vendor_type,name,is_active FROM vendors WHERE id=?'.($lock?' FOR UPDATE':''),[$id]);}
    public function project(int $id,bool $lock=false):?array{return $this->one('SELECT id,project_code,name,status FROM projects WHERE id=?'.($lock?' FOR UPDATE':''),[$id]);}
    public function purchaseOrder(int $id,bool $lock=false):?array{return $this->one('SELECT id,po_code,vendor_id,project_id,status,total_amount FROM purchase_orders WHERE id=?'.($lock?' FOR UPDATE':''),[$id]);}
    public function costCodes(array $ids,bool $lock=false):array{if($ids===[])return[];$marks=implode(',',array_fill(0,count($ids),'?'));return $this->rows("SELECT c.id,c.cost_code,c.name cost_code_name,c.is_active cost_code_active,w.section_code,w.name work_section_name,w.is_active section_active FROM cost_codes c JOIN work_sections w ON w.id=c.work_section_id WHERE c.id IN($marks) ORDER BY c.id".($lock?' FOR UPDATE':''),$ids);}
    public function numberExists(int $vendor,string $number,?int $except=null):bool{return $this->one('SELECT id FROM supplier_invoices WHERE vendor_id=? AND invoice_number=?'.($except?' AND id<>?':'').' LIMIT 1',$except?[$vendor,$number,$except]:[$vendor,$number])!==null;}
    public function create(string $code,SupplierInvoiceData $data,int $user):int{$this->database->execute("INSERT INTO supplier_invoices(invoice_code,vendor_id,project_id,purchase_order_id,invoice_number,invoice_date,due_date,reference,notes,status,created_by) VALUES(?,?,?,?,?,?,?,?,?,'draft',?)",[$code,$data->vendorId,$data->projectId,$data->purchaseOrderId,$data->invoiceNumber,$data->invoiceDate,$data->dueDate,$data->reference,$data->notes,$user]);return (int)$this->database->connection()->insert_id;}
    public function update(int $id,SupplierInvoiceData $data):void{$this->database->execute("UPDATE supplier_invoices SET vendor_id=?,project_id=?,purchase_order_id=?,invoice_number=?,invoice_date=?,due_date=?,reference=?,notes=? WHERE id=? AND status='draft'",[$data->vendorId,$data->projectId,$data->purchaseOrderId,$data->invoiceNumber,$data->invoiceDate,$data->dueDate,$data->reference,$data->notes,$id]);}
    public function syncLines(int $id,array $lines):void{$this->database->execute('DELETE FROM supplier_invoice_lines WHERE supplier_invoice_id=?',[$id]);foreach($lines as $line)$this->database->execute('INSERT INTO supplier_invoice_lines(supplier_invoice_id,description,cost_code_id,amount,sort_order) VALUES(?,?,?,?,?)',[$id,$line['description'],$line['cost_code_id'],$line['amount'],$line['sort_order']]);}
    public function lines(int $id,bool $lock=false):array{return $this->rows("SELECT l.*,c.cost_code current_cost_code,c.name current_cost_code_name,w.section_code current_section_code,w.name current_section_name FROM supplier_invoice_lines l JOIN cost_codes c ON c.id=l.cost_code_id JOIN work_sections w ON w.id=c.work_section_id WHERE l.supplier_invoice_id=? ORDER BY l.sort_order,l.id".($lock?' FOR UPDATE':''),[$id]);}
    public function total(int $id):string{return (string)($this->one('SELECT CAST(COALESCE(SUM(amount),0) AS DECIMAL(18,2)) total FROM supplier_invoice_lines WHERE supplier_invoice_id=?',[$id])['total']??'0.00');}
    public function sourceCostExists(int $invoiceId,int $lineId):bool{return $this->one("SELECT id FROM project_actual_costs WHERE source_type='supplier_invoice' AND source_id=? AND source_line_id=? LIMIT 1",[$invoiceId,$lineId])!==null;}
    public function createCost(string $code,array $invoice,array $line,array $master,int $user):void{$this->database->execute("INSERT INTO project_actual_costs(cost_entry_code,project_id,cost_code_id,vendor_id,cost_date,description,reference_number,amount,source_type,source_id,source_line_id,work_section_code_snapshot,work_section_name_snapshot,cost_code_snapshot,cost_code_name_snapshot,status,created_by,approved_at,approved_by,notes) VALUES(?,?,?,?,?,?,?,?,'supplier_invoice',?,?,?,?,?,?,'approved',?,NOW(),?,?)",[$code,$invoice['project_id'],$line['cost_code_id'],$invoice['vendor_id'],$invoice['invoice_date'],$line['description'],$invoice['invoice_number'],$line['amount'],$invoice['id'],$line['id'],$master['section_code'],$master['work_section_name'],$master['cost_code'],$master['cost_code_name'],$user,$user,'تكلفة معترف بها من فاتورة المورد '.$invoice['invoice_code']]);}
    public function freezeLine(int $id,array $master):void{$this->database->execute('UPDATE supplier_invoice_lines SET work_section_code_snapshot=?,work_section_name_snapshot=?,cost_code_snapshot=?,cost_code_name_snapshot=? WHERE id=?',[$master['section_code'],$master['work_section_name'],$master['cost_code'],$master['cost_code_name'],$id]);}
    public function approve(int $id,string $total,array $vendor,array $project,?string $purchaseOrderCode,int $user):void{$this->database->execute("UPDATE supplier_invoices SET total_amount=?,vendor_code_snapshot=?,vendor_name_snapshot=?,project_code_snapshot=?,project_name_snapshot=?,purchase_order_code_snapshot=?,status='approved',approved_at=NOW(),approved_by=? WHERE id=? AND status='draft'",[$total,$vendor['vendor_code'],$vendor['name'],$project['project_code'],$project['name'],$purchaseOrderCode,$user,$id]);}
    public function cancel(int $id,int $user):void{$this->database->execute("UPDATE supplier_invoices SET status='cancelled',cancelled_at=NOW(),cancelled_by=? WHERE id=? AND status='draft'",[$user,$id]);}
    public function references():array{return ['vendors'=>$this->rows("SELECT id,vendor_code,name FROM vendors WHERE is_active=1 AND vendor_type IN('supplier','both') ORDER BY name"),'projects'=>$this->rows("SELECT id,project_code,name FROM projects WHERE status<>'cancelled' ORDER BY project_code"),'codes'=>$this->rows('SELECT c.id,c.cost_code,c.name,w.section_code,w.name section_name FROM cost_codes c JOIN work_sections w ON w.id=c.work_section_id WHERE c.is_active=1 AND w.is_active=1 ORDER BY w.sort_order,c.sort_order'),'purchase_orders'=>$this->rows("SELECT id,po_code,vendor_id,project_id,total_amount FROM purchase_orders WHERE status='approved' ORDER BY po_date DESC,id DESC")];}
    public function dataTable(SupplierInvoiceTableQuery $query):array{$where=[];$params=[];foreach(['i.vendor_id'=>$query->vendorId,'i.project_id'=>$query->projectId,'i.status'=>$query->status] as $field=>$value)if($value!==null){$where[]="$field=?";$params[]=$value;}if($query->dateFrom){$where[]='i.invoice_date>=?';$params[]=$query->dateFrom;}if($query->dateTo){$where[]='i.invoice_date<=?';$params[]=$query->dateTo;}if($query->search!==''){$search='%'.$query->search.'%';$where[]='(i.invoice_code LIKE ? OR i.invoice_number LIKE ? OR i.reference LIKE ? OR v.name LIKE ? OR p.name LIKE ?)';array_push($params,$search,$search,$search,$search,$search);}$clause=$where?' WHERE '.implode(' AND ',$where):'';$from=' FROM supplier_invoices i JOIN vendors v ON v.id=i.vendor_id JOIN projects p ON p.id=i.project_id LEFT JOIN users au ON au.id=i.approved_by';$total=$this->one('SELECT COUNT(*) total FROM supplier_invoices');$filtered=$this->one('SELECT COUNT(*) total'.$from.$clause,$params);$sort=['invoice_code'=>'i.invoice_code','invoice_number'=>'i.invoice_number','invoice_date'=>'i.invoice_date','due_date'=>'i.due_date','vendor_name'=>'vendor_name','project_name'=>'project_name','total_amount'=>'i.total_amount','status'=>'i.status','approved_by_name'=>'au.name'];$sql="SELECT i.id,i.invoice_code,i.invoice_number,i.invoice_date,i.due_date,CASE WHEN i.status='approved' THEN i.vendor_name_snapshot ELSE v.name END vendor_name,CASE WHEN i.status='approved' THEN i.project_name_snapshot ELSE p.name END project_name,i.total_amount,i.status,au.name approved_by_name".$from.$clause.' ORDER BY '.($sort[$query->sortColumn]??'i.invoice_date').' '.$query->sortDirection.',i.id '.$query->sortDirection.' LIMIT ? OFFSET ?';$result=$this->database->execute($sql,[...$params,$query->length,$query->start]);return ['recordsTotal'=>(int)($total['total']??0),'recordsFiltered'=>(int)($filtered['total']??0),'rows'=>$result instanceof \mysqli_result?$result->fetch_all(MYSQLI_ASSOC):[]];}
    private function one(string $sql,array $params=[]):?array{$result=$this->database->execute($sql,$params);$row=$result instanceof \mysqli_result?$result->fetch_assoc():null;return is_array($row)?$row:null;}
    private function rows(string $sql,array $params=[]):array{$result=$this->database->execute($sql,$params);return $result instanceof \mysqli_result?$result->fetch_all(MYSQLI_ASSOC):[];}
}
