<?php
declare(strict_types=1);
namespace App\Modules\PurchaseOrders\Repositories;
use App\Core\Database\Database;
use App\Modules\PurchaseOrders\DTOs\PurchaseOrderData;
use App\Modules\PurchaseOrders\DTOs\PurchaseOrderTableQuery;
final class PurchaseOrderRepository
{
    public function __construct(private readonly Database $database) {}
    public function find(int $id,bool $lock=false):?array{return $this->one("SELECT o.*,v.vendor_code current_vendor_code,v.name current_vendor_name,p.project_code current_project_code,p.name current_project_name,cu.name created_by_name,au.name approved_by_name,xu.name cancelled_by_name FROM purchase_orders o JOIN vendors v ON v.id=o.vendor_id JOIN projects p ON p.id=o.project_id JOIN users cu ON cu.id=o.created_by LEFT JOIN users au ON au.id=o.approved_by LEFT JOIN users xu ON xu.id=o.cancelled_by WHERE o.id=? LIMIT 1".($lock?' FOR UPDATE':''),[$id]);}
    public function vendor(int $id,bool $lock=false):?array{return $this->one('SELECT id,vendor_code,vendor_type,name,is_active FROM vendors WHERE id=?'.($lock?' FOR UPDATE':''),[$id]);}
    public function project(int $id,bool $lock=false):?array{return $this->one('SELECT id,project_code,name,status FROM projects WHERE id=?'.($lock?' FOR UPDATE':''),[$id]);}
    public function costCodes(array $ids,bool $lock=false):array{if($ids===[])return[];$marks=implode(',',array_fill(0,count($ids),'?'));return $this->rows("SELECT c.id,c.cost_code,c.name cost_code_name,c.is_active cost_code_active,w.section_code,w.name work_section_name,w.is_active section_active FROM cost_codes c JOIN work_sections w ON w.id=c.work_section_id WHERE c.id IN($marks) ORDER BY c.id".($lock?' FOR UPDATE':''),$ids);}
    public function create(string $code,PurchaseOrderData $data,int $user):int{$this->database->execute("INSERT INTO purchase_orders(po_code,vendor_id,project_id,po_date,expected_date,reference,notes,status,created_by) VALUES(?,?,?,?,?,?,?,'draft',?)",[$code,$data->vendorId,$data->projectId,$data->poDate,$data->expectedDate,$data->reference,$data->notes,$user]);return (int)$this->database->connection()->insert_id;}
    public function update(int $id,PurchaseOrderData $data):void{$this->database->execute("UPDATE purchase_orders SET vendor_id=?,project_id=?,po_date=?,expected_date=?,reference=?,notes=? WHERE id=? AND status='draft'",[$data->vendorId,$data->projectId,$data->poDate,$data->expectedDate,$data->reference,$data->notes,$id]);}
    public function syncLines(int $id,array $lines):void{$this->database->execute('DELETE FROM purchase_order_lines WHERE purchase_order_id=?',[$id]);foreach($lines as $line)$this->database->execute('INSERT INTO purchase_order_lines(purchase_order_id,description,cost_code_id,quantity,unit_price,sort_order) VALUES(?,?,?,?,?,?)',[$id,$line['description'],$line['cost_code_id'],$line['quantity'],$line['unit_price'],$line['sort_order']]);}
    public function lines(int $id,bool $lock=false):array{return $this->rows("SELECT l.*,c.cost_code current_cost_code,c.name current_cost_code_name,w.section_code current_section_code,w.name current_section_name FROM purchase_order_lines l JOIN cost_codes c ON c.id=l.cost_code_id JOIN work_sections w ON w.id=c.work_section_id WHERE l.purchase_order_id=? ORDER BY l.sort_order,l.id".($lock?' FOR UPDATE':''),[$id]);}
    /** @return array{total:string,fits:bool} */
    public function totalSummary(int $id):array{$row=$this->one('SELECT COALESCE(SUM(line_total),0.00) total,CASE WHEN COALESCE(SUM(line_total),0.00)<=CAST(? AS DECIMAL(18,2)) THEN 1 ELSE 0 END fits FROM purchase_order_lines WHERE purchase_order_id=?',['9999999999999999.99',$id])??[];return ['total'=>(string)($row['total']??'0.00'),'fits'=>(bool)($row['fits']??false)];}
    public function total(int $id):string{return $this->totalSummary($id)['total'];}
    public function freezeLine(int $id,array $master):void{$this->database->execute('UPDATE purchase_order_lines SET work_section_code_snapshot=?,work_section_name_snapshot=?,cost_code_snapshot=?,cost_code_name_snapshot=? WHERE id=?',[$master['section_code'],$master['work_section_name'],$master['cost_code'],$master['cost_code_name'],$id]);}
    public function approve(int $id,string $total,array $vendor,array $project,int $user):void{$this->database->execute("UPDATE purchase_orders SET total_amount=?,vendor_code_snapshot=?,vendor_name_snapshot=?,project_code_snapshot=?,project_name_snapshot=?,status='approved',approved_at=NOW(),approved_by=? WHERE id=? AND status='draft'",[$total,$vendor['vendor_code'],$vendor['name'],$project['project_code'],$project['name'],$user,$id]);}
    public function cancel(int $id,int $user):void{$this->database->execute("UPDATE purchase_orders SET status='cancelled',cancelled_at=NOW(),cancelled_by=? WHERE id=? AND status='draft'",[$user,$id]);}
    public function references():array{return ['vendors'=>$this->rows("SELECT id,vendor_code,name FROM vendors WHERE is_active=1 AND vendor_type IN('supplier','both') ORDER BY name"),'projects'=>$this->rows("SELECT id,project_code,name FROM projects WHERE status<>'cancelled' ORDER BY project_code"),'codes'=>$this->rows('SELECT c.id,c.cost_code,c.name,w.section_code,w.name section_name FROM cost_codes c JOIN work_sections w ON w.id=c.work_section_id WHERE c.is_active=1 AND w.is_active=1 ORDER BY w.sort_order,c.sort_order')];}
    public function dataTable(PurchaseOrderTableQuery $query):array{$where=[];$params=[];foreach(['o.vendor_id'=>$query->vendorId,'o.project_id'=>$query->projectId,'o.status'=>$query->status] as $field=>$value)if($value!==null){$where[]="$field=?";$params[]=$value;}if($query->dateFrom){$where[]='o.po_date>=?';$params[]=$query->dateFrom;}if($query->dateTo){$where[]='o.po_date<=?';$params[]=$query->dateTo;}if($query->search!==''){$search='%'.$query->search.'%';$where[]='(o.po_code LIKE ? OR o.reference LIKE ? OR v.name LIKE ? OR p.name LIKE ?)';array_push($params,$search,$search,$search,$search);}$clause=$where?' WHERE '.implode(' AND ',$where):'';$from=' FROM purchase_orders o JOIN vendors v ON v.id=o.vendor_id JOIN projects p ON p.id=o.project_id LEFT JOIN users au ON au.id=o.approved_by';$total=$this->one('SELECT COUNT(*) total FROM purchase_orders');$filtered=$this->one('SELECT COUNT(*) total'.$from.$clause,$params);$sort=['po_code'=>'o.po_code','po_date'=>'o.po_date','expected_date'=>'o.expected_date','vendor_name'=>'vendor_name','project_name'=>'project_name','total_amount'=>'o.total_amount','status'=>'o.status','approved_by_name'=>'au.name'];$sql="SELECT o.id,o.po_code,o.po_date,o.expected_date,CASE WHEN o.status='approved' THEN o.vendor_name_snapshot ELSE v.name END vendor_name,CASE WHEN o.status='approved' THEN o.project_name_snapshot ELSE p.name END project_name,o.total_amount,o.status,au.name approved_by_name".$from.$clause.' ORDER BY '.($sort[$query->sortColumn]??'o.po_date').' '.$query->sortDirection.',o.id '.$query->sortDirection.' LIMIT ? OFFSET ?';$result=$this->database->execute($sql,[...$params,$query->length,$query->start]);return ['recordsTotal'=>(int)($total['total']??0),'recordsFiltered'=>(int)($filtered['total']??0),'rows'=>$result instanceof \mysqli_result?$result->fetch_all(MYSQLI_ASSOC):[]];}
    private function one(string $sql,array $params=[]):?array{$result=$this->database->execute($sql,$params);$row=$result instanceof \mysqli_result?$result->fetch_assoc():null;return is_array($row)?$row:null;}
    private function rows(string $sql,array $params=[]):array{$result=$this->database->execute($sql,$params);return $result instanceof \mysqli_result?$result->fetch_all(MYSQLI_ASSOC):[];}
}
