<?php
declare(strict_types=1);
namespace App\Modules\ContractVariations\Validators;
use App\Core\Exceptions\ValidationException;use App\Core\Validation\Validator;use App\Modules\ContractVariations\DTOs\ContractVariationData;
final class ContractVariationValidator
{
 public const TYPES=['addendum','additional_work','deduction','commercial_adjustment'];public const EFFECTS=['increase','decrease','none'];public function __construct(private readonly Validator $validator){}
 public function validate(array $i):ContractVariationData
 {
  if(!$this->validator->validate($i,['client_contract_id'=>'required','variation_number'=>'string|max:50','variation_type'=>'required|string|max:30','title'=>'required|string|max:190','variation_date'=>'required','amount_effect'=>'required|string|max:20','description'=>'string|max:5000','notes'=>'string|max:5000']))throw new ValidationException($this->validator->errors());$e=[];$contract=$this->id($i['client_contract_id']??null);if($contract===null)$e['client_contract_id'][]='عقد العميل غير صالح.';$type=trim((string)($i['variation_type']??''));$effect=trim((string)($i['amount_effect']??''));if(!in_array($type,self::TYPES,true))$e['variation_type'][]='نوع الملحق غير صالح.';if(!in_array($effect,self::EFFECTS,true))$e['amount_effect'][]='اتجاه المبلغ غير صالح.';
  $variationDate=$this->date($i['variation_date']??null);$effectiveDate=$this->date($i['effective_date']??null);if($variationDate===null)$e['variation_date'][]='تاريخ الملحق غير صالح.';if(trim((string)($i['effective_date']??''))!==''&&$effectiveDate===null)$e['effective_date'][]='تاريخ السريان غير صالح.';$amount=$this->decimal($i['amount']??null,true);$markup=$this->decimal($i['markup_percentage']??null,false);if($effect==='none'){if(trim((string)($i['amount']??''))!==''||trim((string)($i['markup_percentage']??''))!=='')$e['amount'][]='الملحق غير المالي لا يقبل مبلغًا أو نسبة زيادة.';$amount=null;$markup=null;}else{if($amount===null)$e['amount'][]='المبلغ مطلوب ويجب ألا يقل عن صفر.';if(trim((string)($i['markup_percentage']??''))!==''&&$markup===null)$e['markup_percentage'][]='نسبة الزيادة يجب أن تكون أكبر من صفر.';}
  if($type==='additional_work'&&$effect!=='increase')$e['amount_effect'][]='الأعمال الإضافية يجب أن تكون زيادة.';if($type==='deduction'&&$effect!=='decrease')$e['amount_effect'][]='الخصم يجب أن يكون تخفيضًا.';if($type==='commercial_adjustment'&&!in_array($effect,['increase','decrease'],true))$e['amount_effect'][]='التسوية التجارية يجب أن تكون زيادة أو تخفيضًا.';if($e)throw new ValidationException($e);return new ContractVariationData((int)$contract,$this->nullable($i['variation_number']??null),$type,trim((string)$i['title']),$this->nullable($i['description']??null),(string)$variationDate,$effectiveDate,$amount,$effect,$markup,$this->nullable($i['notes']??null));
 }
 private function id(mixed $v):?int{$x=filter_var($v,FILTER_VALIDATE_INT,['options'=>['min_range'=>1]]);return $x===false?null:$x;}private function nullable(mixed $v):?string{$v=trim((string)$v);return $v===''?null:$v;}private function date(mixed $v):?string{$v=trim((string)$v);if($v==='')return null;$d=\DateTimeImmutable::createFromFormat('!Y-m-d',$v);return $d&&$d->format('Y-m-d')===$v?$v:null;}private function decimal(mixed $v,bool $zero):?string{$v=trim((string)$v);if($v===''||!preg_match('/^\d+(?:\.\d+)?$/',$v))return null;$n=(float)$v;if($zero?$n<0:$n<=0)return null;return number_format($n,$zero?2:4,'.','');}
}
