<?php

declare(strict_types=1);

use App\Modules\Foundation\Controllers\FoundationController;
use App\Modules\AccessControl\Controllers\AuthenticationController;
use App\Modules\AccessControl\Controllers\PermissionController;
use App\Modules\AccessControl\Controllers\RoleController;
use App\Modules\AccessControl\Controllers\UserController;
use App\Modules\CompanyProfile\Controllers\CompanyProfileController;
use App\Modules\Clients\Controllers\ClientController;
use App\Modules\Clients\Controllers\ClientContactController;
use App\Modules\Vendors\Controllers\VendorController;
use App\Modules\Vendors\Controllers\VendorContactController;
use App\Modules\ProjectCosts\Controllers\ProjectCostController;
use App\Modules\Projects\Controllers\ProjectController;
use App\Modules\CostStructure\Controllers\CostStructureController;
use App\Modules\ClientContracts\Controllers\ClientContractController;
use App\Modules\ContractVariations\Controllers\ContractVariationController;
use App\Modules\ContractBoq\Controllers\ContractBoqController;
use App\Modules\Subcontracts\Controllers\SubcontractController;
use App\Modules\SubcontractBoq\Controllers\SubcontractBoqController;
use App\Modules\SubcontractCertificates\Controllers\SubcontractCertificateController;
use App\Modules\SubcontractPayments\Controllers\SubcontractPaymentController;
use App\Modules\ClientProgressStatements\Controllers\ClientProgressStatementController;
use App\Modules\ClientReceipts\Controllers\ClientReceiptAllocationController;
use App\Modules\ClientReceipts\Controllers\ClientReceiptController;
use App\Modules\ClientReceipts\Controllers\ClientReceiptDataTableController;
use App\Modules\SupplierInvoices\Controllers\SupplierInvoiceController;
use App\Modules\SupplierInvoices\Controllers\SupplierInvoiceDataTableController;
use App\Modules\SupplierPayments\Controllers\SupplierPaymentController;
use App\Modules\SupplierPayments\Controllers\SupplierPaymentDataTableController;
use App\Modules\PurchaseOrders\Controllers\PurchaseOrderController;
use App\Modules\PurchaseOrders\Controllers\PurchaseOrderDataTableController;
use App\Modules\Accounting\Controllers\AccountingController;
use App\Modules\Employees\Controllers\EmployeeController;
use App\Modules\EmployeeCustodies\Controllers\CustodyController;

$app->router()->get('/login',[AuthenticationController::class,'form'],['guest']);
$app->router()->post('/login',[AuthenticationController::class,'login'],['guest']);
$app->router()->post('/logout',[AuthenticationController::class,'logout'],['auth']);
$app->router()->get('/',[FoundationController::class,'index'],['auth']);
$app->router()->post('/foundation/check',[FoundationController::class,'check'],['auth']);
$app->router()->get('/access/users',[UserController::class,'index'],['auth','permission:users.view']);
$app->router()->get('/access/users/create',[UserController::class,'create'],['auth','permission:users.create']);
$app->router()->post('/access/users',[UserController::class,'store'],['auth','permission:users.create']);
$app->router()->get('/access/users/{id}/edit',[UserController::class,'edit'],['auth','permission:users.edit']);
$app->router()->post('/access/users/{id}/edit',[UserController::class,'update'],['auth','permission:users.edit']);
$app->router()->post('/access/users/{id}/activate',[UserController::class,'activate'],['auth','permission:users.activate']);
$app->router()->get('/access/users/{id}/roles',[UserController::class,'roles'],['auth','permission:users.assign_roles']);
$app->router()->post('/access/users/{id}/roles',[UserController::class,'assignRoles'],['auth','permission:users.assign_roles']);
$app->router()->get('/access/roles',[RoleController::class,'index'],['auth','permission:roles.view']);
$app->router()->get('/access/roles/create',[RoleController::class,'create'],['auth','permission:roles.create']);
$app->router()->post('/access/roles',[RoleController::class,'store'],['auth','permission:roles.create']);
$app->router()->get('/access/roles/{id}/edit',[RoleController::class,'edit'],['auth','permission:roles.edit']);
$app->router()->post('/access/roles/{id}/edit',[RoleController::class,'update'],['auth','permission:roles.edit']);
$app->router()->get('/access/roles/{id}/permissions',[RoleController::class,'permissions'],['auth','permission:roles.assign_permissions']);
$app->router()->post('/access/roles/{id}/permissions',[RoleController::class,'assignPermissions'],['auth','permission:roles.assign_permissions']);
$app->router()->get('/access/permissions',[PermissionController::class,'index'],['auth','permission:permissions.view']);
$app->router()->get('/settings/company',[CompanyProfileController::class,'show'],['auth','permission:company_profile.view']);
$app->router()->post('/settings/company',[CompanyProfileController::class,'update'],['auth','permission:company_profile.edit']);
$app->router()->get('/settings/company/logo',[CompanyProfileController::class,'logo'],['auth']);
$app->router()->get('/clients',[ClientController::class,'index'],['auth','permission:clients.view']);
$app->router()->get('/clients/create',[ClientController::class,'create'],['auth','permission:clients.create']);
$app->router()->post('/clients',[ClientController::class,'store'],['auth','permission:clients.create']);
$app->router()->get('/clients/{id}',[ClientController::class,'show'],['auth','permission:clients.view']);
$app->router()->get('/clients/{id}/edit',[ClientController::class,'edit'],['auth','permission:clients.edit']);
$app->router()->post('/clients/{id}/edit',[ClientController::class,'update'],['auth','permission:clients.edit']);
$app->router()->post('/clients/{id}/activate',[ClientController::class,'activate'],['auth','permission:clients.activate']);
$app->router()->get('/clients/{client_id}/contacts/create',[ClientContactController::class,'create'],['auth','permission:clients.edit']);
$app->router()->post('/clients/{client_id}/contacts',[ClientContactController::class,'store'],['auth','permission:clients.edit']);
$app->router()->get('/clients/{client_id}/contacts/{contact_id}/edit',[ClientContactController::class,'edit'],['auth','permission:clients.edit']);
$app->router()->post('/clients/{client_id}/contacts/{contact_id}/edit',[ClientContactController::class,'update'],['auth','permission:clients.edit']);
$app->router()->post('/clients/{client_id}/contacts/{contact_id}/remove',[ClientContactController::class,'remove'],['auth','permission:clients.edit']);
$app->router()->post('/clients/{client_id}/contacts/{contact_id}/primary',[ClientContactController::class,'primary'],['auth','permission:clients.edit']);
$app->router()->get('/vendors',[VendorController::class,'index'],['auth','permission:vendors.view']);
$app->router()->get('/vendors/create',[VendorController::class,'create'],['auth','permission:vendors.create']);
$app->router()->post('/vendors',[VendorController::class,'store'],['auth','permission:vendors.create']);
$app->router()->get('/vendors/{id}',[VendorController::class,'show'],['auth','permission:vendors.view']);
$app->router()->get('/vendors/{id}/edit',[VendorController::class,'edit'],['auth','permission:vendors.edit']);
$app->router()->post('/vendors/{id}/edit',[VendorController::class,'update'],['auth','permission:vendors.edit']);
$app->router()->post('/vendors/{id}/activate',[VendorController::class,'activate'],['auth','permission:vendors.activate']);
$app->router()->post('/api/vendors/{vendor_id}/contacts',[VendorContactController::class,'store'],['auth','permission:vendors.edit']);
$app->router()->post('/api/vendors/{vendor_id}/contacts/{contact_id}',[VendorContactController::class,'update'],['auth','permission:vendors.edit']);
$app->router()->post('/api/vendors/{vendor_id}/contacts/{contact_id}/remove',[VendorContactController::class,'remove'],['auth','permission:vendors.edit']);
$app->router()->post('/api/vendors/{vendor_id}/contacts/{contact_id}/primary',[VendorContactController::class,'primary'],['auth','permission:vendors.edit']);
$app->router()->get('/project-costs',[ProjectCostController::class,'global'],['auth','permission:project_costs.view']);
$app->router()->get('/projects/{project_id}/costs',[ProjectCostController::class,'project'],['auth','permission:project_costs.view']);
$app->router()->get('/projects/{project_id}/costs/create',[ProjectCostController::class,'create'],['auth','permission:project_costs.create']);
$app->router()->post('/projects/{project_id}/costs',[ProjectCostController::class,'store'],['auth','permission:project_costs.create']);
$app->router()->get('/project-costs/{id}',[ProjectCostController::class,'show'],['auth','permission:project_costs.view']);
$app->router()->get('/project-costs/{id}/edit',[ProjectCostController::class,'edit'],['auth','permission:project_costs.edit']);
$app->router()->post('/project-costs/{id}/edit',[ProjectCostController::class,'update'],['auth','permission:project_costs.edit']);
$app->router()->post('/project-costs/{id}/approve',[ProjectCostController::class,'approve'],['auth','permission:project_costs.approve']);
$app->router()->post('/project-costs/{id}/cancel',[ProjectCostController::class,'cancel'],['auth','permission:project_costs.cancel']);
$app->router()->get('/projects',[ProjectController::class,'index'],['auth','permission:projects.view']);
$app->router()->get('/projects/create',[ProjectController::class,'create'],['auth','permission:projects.create']);
$app->router()->post('/projects',[ProjectController::class,'store'],['auth','permission:projects.create']);
$app->router()->get('/projects/{id}',[ProjectController::class,'show'],['auth','permission:projects.view']);
$app->router()->get('/projects/{id}/edit',[ProjectController::class,'edit'],['auth','permission:projects.edit']);
$app->router()->post('/projects/{id}/edit',[ProjectController::class,'update'],['auth','permission:projects.edit']);
$app->router()->post('/projects/{id}/status',[ProjectController::class,'status'],['auth','permission:projects.change_status']);
$app->router()->get('/settings/cost-structure',[CostStructureController::class,'index'],['auth','permission:cost_structure.view']);
$app->router()->post('/settings/cost-structure/sections',[CostStructureController::class,'storeSection'],['auth','permission:cost_structure.manage']);
$app->router()->post('/settings/cost-structure/sections/{id}',[CostStructureController::class,'updateSection'],['auth','permission:cost_structure.manage']);
$app->router()->post('/settings/cost-structure/sections/{id}/activate',[CostStructureController::class,'toggleSection'],['auth','permission:cost_structure.manage']);
$app->router()->post('/settings/cost-structure/codes',[CostStructureController::class,'storeCode'],['auth','permission:cost_structure.manage']);
$app->router()->post('/settings/cost-structure/codes/{id}',[CostStructureController::class,'updateCode'],['auth','permission:cost_structure.manage']);
$app->router()->post('/settings/cost-structure/codes/{id}/activate',[CostStructureController::class,'toggleCode'],['auth','permission:cost_structure.manage']);
$app->router()->post('/settings/cost-structure/units',[CostStructureController::class,'storeUnit'],['auth','permission:cost_structure.manage']);
$app->router()->post('/settings/cost-structure/units/{id}',[CostStructureController::class,'updateUnit'],['auth','permission:cost_structure.manage']);
$app->router()->post('/settings/cost-structure/units/{id}/activate',[CostStructureController::class,'toggleUnit'],['auth','permission:cost_structure.manage']);
$app->router()->get('/contracts',[ClientContractController::class,'index'],['auth','permission:client_contracts.view']);
$app->router()->get('/contracts/create',[ClientContractController::class,'create'],['auth','permission:client_contracts.create']);
$app->router()->post('/contracts',[ClientContractController::class,'store'],['auth','permission:client_contracts.create']);
$app->router()->get('/contracts/{id}',[ClientContractController::class,'show'],['auth','permission:client_contracts.view']);
$app->router()->get('/contracts/{id}/edit',[ClientContractController::class,'edit'],['auth','permission:client_contracts.edit']);
$app->router()->post('/contracts/{id}/edit',[ClientContractController::class,'update'],['auth','permission:client_contracts.edit']);
$app->router()->post('/contracts/{id}/status',[ClientContractController::class,'status'],['auth','permission:client_contracts.change_status']);
$app->router()->get('/contracts/{contract_id}/variations',[ContractVariationController::class,'index'],['auth','permission:contract_variations.view']);
$app->router()->get('/contracts/{contract_id}/variations/create',[ContractVariationController::class,'create'],['auth','permission:contract_variations.create']);
$app->router()->post('/contracts/{contract_id}/variations',[ContractVariationController::class,'store'],['auth','permission:contract_variations.create']);
$app->router()->get('/contract-variations/{id}',[ContractVariationController::class,'show'],['auth','permission:contract_variations.view']);
$app->router()->get('/contract-variations/{id}/edit',[ContractVariationController::class,'edit'],['auth','permission:contract_variations.edit']);
$app->router()->post('/contract-variations/{id}/edit',[ContractVariationController::class,'update'],['auth','permission:contract_variations.edit']);
$app->router()->post('/contract-variations/{id}/approve',[ContractVariationController::class,'approve'],['auth','permission:contract_variations.approve']);
$app->router()->post('/contract-variations/{id}/cancel',[ContractVariationController::class,'cancel'],['auth','permission:contract_variations.cancel']);
$app->router()->get('/contracts/{contract_id}/boq',[ContractBoqController::class,'show'],['auth','permission:contract_boq.view']);
$app->router()->post('/contracts/{contract_id}/boq',[ContractBoqController::class,'start'],['auth','permission:contract_boq.manage']);
$app->router()->post('/contracts/{contract_id}/boq/discard',[ContractBoqController::class,'discard'],['auth','permission:contract_boq.manage']);
$app->router()->post('/contracts/{contract_id}/boq/sections',[ContractBoqController::class,'section'],['auth','permission:contract_boq.manage']);
$app->router()->post('/contracts/{contract_id}/boq/sections/{section_id}',[ContractBoqController::class,'section'],['auth','permission:contract_boq.manage']);
$app->router()->post('/contracts/{contract_id}/boq/sections/{section_id}/remove',[ContractBoqController::class,'removeSection'],['auth','permission:contract_boq.manage']);
$app->router()->post('/contracts/{contract_id}/boq/items',[ContractBoqController::class,'item'],['auth','permission:contract_boq.manage']);
$app->router()->post('/contracts/{contract_id}/boq/items/{item_id}',[ContractBoqController::class,'item'],['auth','permission:contract_boq.manage']);
$app->router()->post('/contracts/{contract_id}/boq/items/{item_id}/remove',[ContractBoqController::class,'removeItem'],['auth','permission:contract_boq.manage']);
$app->router()->post('/contracts/{contract_id}/boq/approve',[ContractBoqController::class,'approve'],['auth','permission:contract_boq.approve']);
$app->router()->get('/subcontracts',[SubcontractController::class,'index'],['auth','permission:subcontracts.view']);
$app->router()->get('/subcontracts/create',[SubcontractController::class,'create'],['auth','permission:subcontracts.create']);
$app->router()->post('/subcontracts',[SubcontractController::class,'store'],['auth','permission:subcontracts.create']);
$app->router()->get('/subcontracts/{id}',[SubcontractController::class,'show'],['auth','permission:subcontracts.view']);
$app->router()->get('/subcontracts/{id}/edit',[SubcontractController::class,'edit'],['auth','permission:subcontracts.edit']);
$app->router()->post('/subcontracts/{id}/edit',[SubcontractController::class,'update'],['auth','permission:subcontracts.edit']);
$app->router()->post('/subcontracts/{id}/status',[SubcontractController::class,'status'],['auth','permission:subcontracts.change_status']);
$app->router()->get('/subcontracts/{subcontract_id}/boq',[SubcontractBoqController::class,'show'],['auth','permission:subcontract_boq.view']);
$app->router()->post('/subcontracts/{subcontract_id}/boq',[SubcontractBoqController::class,'start'],['auth','permission:subcontract_boq.manage']);
$app->router()->post('/subcontracts/{subcontract_id}/boq/discard',[SubcontractBoqController::class,'discard'],['auth','permission:subcontract_boq.manage']);
$app->router()->post('/subcontracts/{subcontract_id}/boq/sections',[SubcontractBoqController::class,'section'],['auth','permission:subcontract_boq.manage']);
$app->router()->post('/subcontracts/{subcontract_id}/boq/sections/{section_id}',[SubcontractBoqController::class,'section'],['auth','permission:subcontract_boq.manage']);
$app->router()->post('/subcontracts/{subcontract_id}/boq/sections/{section_id}/remove',[SubcontractBoqController::class,'removeSection'],['auth','permission:subcontract_boq.manage']);
$app->router()->post('/subcontracts/{subcontract_id}/boq/items',[SubcontractBoqController::class,'item'],['auth','permission:subcontract_boq.manage']);
$app->router()->post('/subcontracts/{subcontract_id}/boq/items/{item_id}',[SubcontractBoqController::class,'item'],['auth','permission:subcontract_boq.manage']);
$app->router()->post('/subcontracts/{subcontract_id}/boq/items/{item_id}/remove',[SubcontractBoqController::class,'removeItem'],['auth','permission:subcontract_boq.manage']);
$app->router()->post('/subcontracts/{subcontract_id}/boq/approve',[SubcontractBoqController::class,'approve'],['auth','permission:subcontract_boq.approve']);
$app->router()->get('/subcontracts/{subcontract_id}/certificates',[SubcontractCertificateController::class,'index'],['auth','permission:subcontract_certificates.view']);
$app->router()->get('/subcontracts/{subcontract_id}/certificates/create',[SubcontractCertificateController::class,'create'],['auth','permission:subcontract_certificates.create']);
$app->router()->post('/subcontracts/{subcontract_id}/certificates',[SubcontractCertificateController::class,'store'],['auth','permission:subcontract_certificates.create']);
$app->router()->get('/subcontract-certificates/{id}',[SubcontractCertificateController::class,'show'],['auth','permission:subcontract_certificates.view']);
$app->router()->get('/subcontract-certificates/{id}/edit',[SubcontractCertificateController::class,'edit'],['auth','permission:subcontract_certificates.edit']);
$app->router()->post('/subcontract-certificates/{id}/edit',[SubcontractCertificateController::class,'update'],['auth','permission:subcontract_certificates.edit']);
$app->router()->post('/subcontract-certificates/{id}/approve',[SubcontractCertificateController::class,'approve'],['auth','permission:subcontract_certificates.approve']);
$app->router()->post('/subcontract-certificates/{id}/cancel',[SubcontractCertificateController::class,'cancel'],['auth','permission:subcontract_certificates.cancel']);
$app->router()->get('/subcontracts/{subcontract_id}/payments',[SubcontractPaymentController::class,'index'],['auth','permission:subcontract_payments.view']);
$app->router()->get('/subcontracts/{subcontract_id}/payments/create',[SubcontractPaymentController::class,'create'],['auth','permission:subcontract_payments.create']);
$app->router()->post('/subcontracts/{subcontract_id}/payments',[SubcontractPaymentController::class,'store'],['auth','permission:subcontract_payments.create']);
$app->router()->get('/subcontract-payments/{id}',[SubcontractPaymentController::class,'show'],['auth','permission:subcontract_payments.view']);
$app->router()->get('/subcontract-payments/{id}/edit',[SubcontractPaymentController::class,'edit'],['auth','permission:subcontract_payments.edit']);
$app->router()->post('/subcontract-payments/{id}/edit',[SubcontractPaymentController::class,'update'],['auth','permission:subcontract_payments.edit']);
$app->router()->post('/subcontract-payments/{id}/post',[SubcontractPaymentController::class,'post'],['auth','permission:subcontract_payments.post']);
$app->router()->post('/subcontract-payments/{id}/cancel',[SubcontractPaymentController::class,'cancel'],['auth','permission:subcontract_payments.cancel']);
$app->router()->get('/client-progress-statements',[ClientProgressStatementController::class,'global'],['auth','permission:client_progress_statements.view']);
$app->router()->get('/client-contracts/{contract_id}/progress-statements',[ClientProgressStatementController::class,'contract'],['auth','permission:client_progress_statements.view']);
$app->router()->get('/client-contracts/{contract_id}/progress-statements/create',[ClientProgressStatementController::class,'create'],['auth','permission:client_progress_statements.create']);
$app->router()->post('/client-contracts/{contract_id}/progress-statements',[ClientProgressStatementController::class,'store'],['auth','permission:client_progress_statements.create']);
$app->router()->get('/client-progress-statements/{id}',[ClientProgressStatementController::class,'show'],['auth','permission:client_progress_statements.view']);
$app->router()->get('/client-progress-statements/{id}/edit',[ClientProgressStatementController::class,'edit'],['auth','permission:client_progress_statements.edit']);
$app->router()->post('/client-progress-statements/{id}/edit',[ClientProgressStatementController::class,'update'],['auth','permission:client_progress_statements.edit']);
$app->router()->post('/client-progress-statements/{id}/approve',[ClientProgressStatementController::class,'approve'],['auth','permission:client_progress_statements.approve']);
$app->router()->post('/client-progress-statements/{id}/cancel',[ClientProgressStatementController::class,'cancel'],['auth','permission:client_progress_statements.cancel']);
$app->router()->get('/client-progress-statements/{id}/print',[ClientProgressStatementController::class,'print'],['auth','permission:client_progress_statements.view']);
$app->router()->get('/client-receipts',[ClientReceiptController::class,'global'],['auth','permission:client_receipts.view']);
$app->router()->get('/client-contracts/{contract_id}/receipts',[ClientReceiptController::class,'contract'],['auth','permission:client_receipts.view']);
$app->router()->get('/client-contracts/{contract_id}/receipts/create',[ClientReceiptController::class,'create'],['auth','permission:client_receipts.create']);
$app->router()->post('/client-contracts/{contract_id}/receipts',[ClientReceiptController::class,'store'],['auth','permission:client_receipts.create']);
$app->router()->get('/client-receipts/{id}',[ClientReceiptController::class,'show'],['auth','permission:client_receipts.view']);
$app->router()->get('/client-receipts/{id}/edit',[ClientReceiptController::class,'edit'],['auth','permission:client_receipts.edit']);
$app->router()->post('/client-receipts/{id}/edit',[ClientReceiptController::class,'update'],['auth','permission:client_receipts.edit']);
$app->router()->post('/client-receipts/{id}/post',[ClientReceiptController::class,'post'],['auth','permission:client_receipts.post']);
$app->router()->post('/client-receipts/{id}/cancel',[ClientReceiptController::class,'cancel'],['auth','permission:client_receipts.cancel']);
$app->router()->get('/client-receipts/{id}/allocate',[ClientReceiptAllocationController::class,'form'],['auth','permission:client_receipts.allocate']);
$app->router()->post('/client-receipts/{id}/allocate',[ClientReceiptAllocationController::class,'store'],['auth','permission:client_receipts.allocate']);
$app->router()->get('/client-receipts/{id}/print',[ClientReceiptController::class,'print'],['auth','permission:client_receipts.view']);
$app->router()->get('/api/client-receipts',[ClientReceiptDataTableController::class,'global'],['auth','permission:client_receipts.view']);
$app->router()->get('/api/client-contracts/{contract_id}/receipts',[ClientReceiptDataTableController::class,'contract'],['auth','permission:client_receipts.view']);
$app->router()->get('/api/client-receipts/{id}/eligible-statements',[ClientReceiptAllocationController::class,'eligible'],['auth','permission:client_receipts.allocate']);
$app->router()->get('/supplier-invoices',[SupplierInvoiceController::class,'index'],['auth','permission:supplier_invoices.view']);
$app->router()->get('/supplier-invoices/create',[SupplierInvoiceController::class,'create'],['auth','permission:supplier_invoices.create']);
$app->router()->post('/supplier-invoices',[SupplierInvoiceController::class,'store'],['auth','permission:supplier_invoices.create']);
$app->router()->get('/supplier-invoices/{id}',[SupplierInvoiceController::class,'show'],['auth','permission:supplier_invoices.view']);
$app->router()->get('/supplier-invoices/{id}/edit',[SupplierInvoiceController::class,'edit'],['auth','permission:supplier_invoices.edit']);
$app->router()->post('/supplier-invoices/{id}/edit',[SupplierInvoiceController::class,'update'],['auth','permission:supplier_invoices.edit']);
$app->router()->post('/supplier-invoices/{id}/approve',[SupplierInvoiceController::class,'approve'],['auth','permission:supplier_invoices.approve']);
$app->router()->post('/supplier-invoices/{id}/cancel',[SupplierInvoiceController::class,'cancel'],['auth','permission:supplier_invoices.cancel']);
$app->router()->get('/supplier-invoices/{id}/print',[SupplierInvoiceController::class,'print'],['auth','permission:supplier_invoices.view']);
$app->router()->get('/api/supplier-invoices',[SupplierInvoiceDataTableController::class,'index'],['auth','permission:supplier_invoices.view']);
$app->router()->get('/supplier-payments',[SupplierPaymentController::class,'index'],['auth','permission:supplier_payments.view']);
$app->router()->get('/supplier-payments/create',[SupplierPaymentController::class,'create'],['auth','permission:supplier_payments.create']);
$app->router()->post('/supplier-payments',[SupplierPaymentController::class,'store'],['auth','permission:supplier_payments.create']);
$app->router()->get('/supplier-payments/{id}',[SupplierPaymentController::class,'show'],['auth','permission:supplier_payments.view']);
$app->router()->get('/supplier-payments/{id}/edit',[SupplierPaymentController::class,'edit'],['auth','permission:supplier_payments.edit']);
$app->router()->post('/supplier-payments/{id}/edit',[SupplierPaymentController::class,'update'],['auth','permission:supplier_payments.edit']);
$app->router()->post('/supplier-payments/{id}/post',[SupplierPaymentController::class,'post'],['auth','permission:supplier_payments.post']);
$app->router()->post('/supplier-payments/{id}/cancel',[SupplierPaymentController::class,'cancel'],['auth','permission:supplier_payments.cancel']);
$app->router()->get('/supplier-payments/{id}/print',[SupplierPaymentController::class,'print'],['auth','permission:supplier_payments.view']);
$app->router()->get('/api/supplier-payments',[SupplierPaymentDataTableController::class,'index'],['auth','permission:supplier_payments.view']);
$app->router()->get('/purchase-orders',[PurchaseOrderController::class,'index'],['auth','permission:purchase_orders.view']);
$app->router()->get('/purchase-orders/create',[PurchaseOrderController::class,'create'],['auth','permission:purchase_orders.create']);
$app->router()->post('/purchase-orders',[PurchaseOrderController::class,'store'],['auth','permission:purchase_orders.create']);
$app->router()->get('/purchase-orders/{id}',[PurchaseOrderController::class,'show'],['auth','permission:purchase_orders.view']);
$app->router()->get('/purchase-orders/{id}/edit',[PurchaseOrderController::class,'edit'],['auth','permission:purchase_orders.edit']);
$app->router()->post('/purchase-orders/{id}/edit',[PurchaseOrderController::class,'update'],['auth','permission:purchase_orders.edit']);
$app->router()->post('/purchase-orders/{id}/approve',[PurchaseOrderController::class,'approve'],['auth','permission:purchase_orders.approve']);
$app->router()->post('/purchase-orders/{id}/cancel',[PurchaseOrderController::class,'cancel'],['auth','permission:purchase_orders.cancel']);
$app->router()->get('/purchase-orders/{id}/print',[PurchaseOrderController::class,'print'],['auth','permission:purchase_orders.view']);
$app->router()->get('/api/purchase-orders',[PurchaseOrderDataTableController::class,'index'],['auth','permission:purchase_orders.view']);
$app->router()->get('/accounting/accounts',[AccountingController::class,'accounts'],['auth','permission:accounts.view']);
$app->router()->post('/accounting/accounts',[AccountingController::class,'saveAccount'],['auth','permission:accounts.manage']);
$app->router()->get('/accounting/journals',[AccountingController::class,'journalIndex'],['auth','permission:journal_entries.view']);
$app->router()->get('/accounting/journals/create',[AccountingController::class,'journalCreate'],['auth','permission:journal_entries.create']);
$app->router()->post('/accounting/journals',[AccountingController::class,'journalStore'],['auth','permission:journal_entries.create']);
$app->router()->get('/accounting/journals/{id}',[AccountingController::class,'journalShow'],['auth','permission:journal_entries.view']);
$app->router()->get('/accounting/journals/{id}/edit',[AccountingController::class,'journalEdit'],['auth','permission:journal_entries.edit']);
$app->router()->post('/accounting/journals/{id}/edit',[AccountingController::class,'journalUpdate'],['auth','permission:journal_entries.edit']);
$app->router()->post('/accounting/journals/{id}/post',[AccountingController::class,'journalPost'],['auth','permission:journal_entries.post']);
$app->router()->get('/accounting/trial-balance',[AccountingController::class,'trialBalance'],['auth','permission:trial_balance.view']);
$app->router()->get('/accounting/periods',[AccountingController::class,'periods'],['auth','permission:accounting_periods.view']);
$app->router()->post('/accounting/periods',[AccountingController::class,'createYear'],['auth','permission:accounting_periods.manage']);
$app->router()->post('/accounting/periods/{id}/status',[AccountingController::class,'periodStatus'],['auth','permission:accounting_periods.manage']);
$app->router()->get('/accounting/setup',[AccountingController::class,'setup'],['auth','permission:accounting_setup.view']);
$app->router()->post('/accounting/setup',[AccountingController::class,'saveSetup'],['auth','permission:accounting_setup.manage']);
$app->router()->post('/accounting/setup/cost-codes',[AccountingController::class,'saveCostCodeMapping'],['auth','permission:accounting_setup.manage']);
$app->router()->get('/employees',[EmployeeController::class,'index'],['auth','permission:employees.view']);
$app->router()->post('/employees',[EmployeeController::class,'store'],['auth','permission:employees.manage']);
$app->router()->post('/employees/{id}',[EmployeeController::class,'update'],['auth','permission:employees.manage']);
$app->router()->get('/employee-custodies',[CustodyController::class,'index'],['auth','permission:employee_custodies.view']);
$app->router()->get('/employee-custodies/create',[CustodyController::class,'create'],['auth','permission:employee_custodies.create']);
$app->router()->post('/employee-custodies',[CustodyController::class,'store'],['auth','permission:employee_custodies.create']);
$app->router()->get('/employee-custodies/{id}',[CustodyController::class,'show'],['auth','permission:employee_custodies.view']);
$app->router()->get('/employee-custodies/{id}/edit',[CustodyController::class,'edit'],['auth','permission:employee_custodies.edit']);
$app->router()->post('/employee-custodies/{id}/edit',[CustodyController::class,'update'],['auth','permission:employee_custodies.edit']);
$app->router()->post('/employee-custodies/{id}/issue',[CustodyController::class,'issue'],['auth','permission:employee_custodies.issue']);
$app->router()->post('/employee-custodies/{id}/cancel',[CustodyController::class,'cancel'],['auth','permission:employee_custodies.cancel']);
$app->router()->post('/employee-custodies/{id}/expense',[CustodyController::class,'expense'],['auth','permission:employee_custodies.settle']);
$app->router()->post('/employee-custodies/{id}/cash-return',[CustodyController::class,'cashReturn'],['auth','permission:employee_custodies.settle']);
$app->router()->get('/employee-custodies/{id}/print',[CustodyController::class,'print'],['auth','permission:employee_custodies.view']);
