<?php

declare(strict_types=1);

use App\Modules\Foundation\Controllers\FoundationController;
use App\Modules\AccessControl\Controllers\AuthenticationController;
use App\Modules\AccessControl\Controllers\PermissionController;
use App\Modules\AccessControl\Controllers\RoleController;
use App\Modules\AccessControl\Controllers\UserController;
use App\Modules\CompanyProfile\Controllers\CompanyProfileController;
use App\Modules\Clients\Controllers\ClientController;
use App\Modules\Clients\Controllers\ClientContactController;
use App\Modules\Vendors\Controllers\VendorController;
use App\Modules\Vendors\Controllers\VendorContactController;
use App\Modules\Projects\Controllers\ProjectController;
use App\Modules\CostStructure\Controllers\CostStructureController;

$app->router()->get('/login',[AuthenticationController::class,'form'],['guest']);
$app->router()->post('/login',[AuthenticationController::class,'login'],['guest']);
$app->router()->post('/logout',[AuthenticationController::class,'logout'],['auth']);
$app->router()->get('/',[FoundationController::class,'index'],['auth']);
$app->router()->post('/foundation/check',[FoundationController::class,'check'],['auth']);
$app->router()->get('/access/users',[UserController::class,'index'],['auth','permission:users.view']);
$app->router()->get('/access/users/create',[UserController::class,'create'],['auth','permission:users.create']);
$app->router()->post('/access/users',[UserController::class,'store'],['auth','permission:users.create']);
$app->router()->get('/access/users/{id}/edit',[UserController::class,'edit'],['auth','permission:users.edit']);
$app->router()->post('/access/users/{id}/edit',[UserController::class,'update'],['auth','permission:users.edit']);
$app->router()->post('/access/users/{id}/activate',[UserController::class,'activate'],['auth','permission:users.activate']);
$app->router()->get('/access/users/{id}/roles',[UserController::class,'roles'],['auth','permission:users.assign_roles']);
$app->router()->post('/access/users/{id}/roles',[UserController::class,'assignRoles'],['auth','permission:users.assign_roles']);
$app->router()->get('/access/roles',[RoleController::class,'index'],['auth','permission:roles.view']);
$app->router()->get('/access/roles/create',[RoleController::class,'create'],['auth','permission:roles.create']);
$app->router()->post('/access/roles',[RoleController::class,'store'],['auth','permission:roles.create']);
$app->router()->get('/access/roles/{id}/edit',[RoleController::class,'edit'],['auth','permission:roles.edit']);
$app->router()->post('/access/roles/{id}/edit',[RoleController::class,'update'],['auth','permission:roles.edit']);
$app->router()->get('/access/roles/{id}/permissions',[RoleController::class,'permissions'],['auth','permission:roles.assign_permissions']);
$app->router()->post('/access/roles/{id}/permissions',[RoleController::class,'assignPermissions'],['auth','permission:roles.assign_permissions']);
$app->router()->get('/access/permissions',[PermissionController::class,'index'],['auth','permission:permissions.view']);
$app->router()->get('/settings/company',[CompanyProfileController::class,'show'],['auth','permission:company_profile.view']);
$app->router()->post('/settings/company',[CompanyProfileController::class,'update'],['auth','permission:company_profile.edit']);
$app->router()->get('/settings/company/logo',[CompanyProfileController::class,'logo'],['auth','permission:company_profile.view']);
$app->router()->get('/clients',[ClientController::class,'index'],['auth','permission:clients.view']);
$app->router()->get('/clients/create',[ClientController::class,'create'],['auth','permission:clients.create']);
$app->router()->post('/clients',[ClientController::class,'store'],['auth','permission:clients.create']);
$app->router()->get('/clients/{id}',[ClientController::class,'show'],['auth','permission:clients.view']);
$app->router()->get('/clients/{id}/edit',[ClientController::class,'edit'],['auth','permission:clients.edit']);
$app->router()->post('/clients/{id}/edit',[ClientController::class,'update'],['auth','permission:clients.edit']);
$app->router()->post('/clients/{id}/activate',[ClientController::class,'activate'],['auth','permission:clients.activate']);
$app->router()->get('/clients/{client_id}/contacts/create',[ClientContactController::class,'create'],['auth','permission:clients.edit']);
$app->router()->post('/clients/{client_id}/contacts',[ClientContactController::class,'store'],['auth','permission:clients.edit']);
$app->router()->get('/clients/{client_id}/contacts/{contact_id}/edit',[ClientContactController::class,'edit'],['auth','permission:clients.edit']);
$app->router()->post('/clients/{client_id}/contacts/{contact_id}/edit',[ClientContactController::class,'update'],['auth','permission:clients.edit']);
$app->router()->post('/clients/{client_id}/contacts/{contact_id}/remove',[ClientContactController::class,'remove'],['auth','permission:clients.edit']);
$app->router()->post('/clients/{client_id}/contacts/{contact_id}/primary',[ClientContactController::class,'primary'],['auth','permission:clients.edit']);
$app->router()->get('/vendors',[VendorController::class,'index'],['auth','permission:vendors.view']);
$app->router()->get('/vendors/create',[VendorController::class,'create'],['auth','permission:vendors.create']);
$app->router()->post('/vendors',[VendorController::class,'store'],['auth','permission:vendors.create']);
$app->router()->get('/vendors/{id}',[VendorController::class,'show'],['auth','permission:vendors.view']);
$app->router()->get('/vendors/{id}/edit',[VendorController::class,'edit'],['auth','permission:vendors.edit']);
$app->router()->post('/vendors/{id}/edit',[VendorController::class,'update'],['auth','permission:vendors.edit']);
$app->router()->post('/vendors/{id}/activate',[VendorController::class,'activate'],['auth','permission:vendors.activate']);
$app->router()->post('/api/vendors/{vendor_id}/contacts',[VendorContactController::class,'store'],['auth','permission:vendors.edit']);
$app->router()->post('/api/vendors/{vendor_id}/contacts/{contact_id}',[VendorContactController::class,'update'],['auth','permission:vendors.edit']);
$app->router()->post('/api/vendors/{vendor_id}/contacts/{contact_id}/remove',[VendorContactController::class,'remove'],['auth','permission:vendors.edit']);
$app->router()->post('/api/vendors/{vendor_id}/contacts/{contact_id}/primary',[VendorContactController::class,'primary'],['auth','permission:vendors.edit']);
$app->router()->get('/projects',[ProjectController::class,'index'],['auth','permission:projects.view']);
$app->router()->get('/projects/create',[ProjectController::class,'create'],['auth','permission:projects.create']);
$app->router()->post('/projects',[ProjectController::class,'store'],['auth','permission:projects.create']);
$app->router()->get('/projects/{id}',[ProjectController::class,'show'],['auth','permission:projects.view']);
$app->router()->get('/projects/{id}/edit',[ProjectController::class,'edit'],['auth','permission:projects.edit']);
$app->router()->post('/projects/{id}/edit',[ProjectController::class,'update'],['auth','permission:projects.edit']);
$app->router()->post('/projects/{id}/status',[ProjectController::class,'status'],['auth','permission:projects.change_status']);
$app->router()->get('/settings/cost-structure',[CostStructureController::class,'index'],['auth','permission:cost_structure.view']);
$app->router()->post('/settings/cost-structure/sections',[CostStructureController::class,'storeSection'],['auth','permission:cost_structure.manage']);
$app->router()->post('/settings/cost-structure/sections/{id}',[CostStructureController::class,'updateSection'],['auth','permission:cost_structure.manage']);
$app->router()->post('/settings/cost-structure/sections/{id}/activate',[CostStructureController::class,'toggleSection'],['auth','permission:cost_structure.manage']);
$app->router()->post('/settings/cost-structure/codes',[CostStructureController::class,'storeCode'],['auth','permission:cost_structure.manage']);
$app->router()->post('/settings/cost-structure/codes/{id}',[CostStructureController::class,'updateCode'],['auth','permission:cost_structure.manage']);
$app->router()->post('/settings/cost-structure/codes/{id}/activate',[CostStructureController::class,'toggleCode'],['auth','permission:cost_structure.manage']);
$app->router()->post('/settings/cost-structure/units',[CostStructureController::class,'storeUnit'],['auth','permission:cost_structure.manage']);
$app->router()->post('/settings/cost-structure/units/{id}',[CostStructureController::class,'updateUnit'],['auth','permission:cost_structure.manage']);
$app->router()->post('/settings/cost-structure/units/{id}/activate',[CostStructureController::class,'toggleUnit'],['auth','permission:cost_structure.manage']);
