<?php
declare(strict_types=1);
namespace App\Modules\ContractVariations\Repositories;
use App\Core\Database\Database;use App\Modules\ContractVariations\DTOs\ContractVariationData;use App\Modules\ContractVariations\DTOs\ContractVariationTableQuery;
final class ContractVariationRepository
{
 public function __construct(private readonly Database $db){}
 public function contract(int $id):?array{$r=$this->db->execute("SELECT cc.id,cc.contract_code,cc.contract_number,cc.title,cc.status,cc.pricing_method,cc.contract_value,p.project_code,p.name project_name,COALESCE(c.company_name,c.name) client_name FROM client_contracts cc JOIN projects p ON p.id=cc.project_id JOIN clients c ON c.id=cc.client_id WHERE cc.id=? LIMIT 1",[$id]);$row=$r instanceof \mysqli_result?$r->fetch_assoc():null;return is_array($row)?$row:null;}
 public function find(int $id):?array{$r=$this->db->execute("SELECT v.*,cc.contract_code,cc.contract_number,cc.title contract_title,cc.status contract_status,cc.pricing_method,p.project_code,p.name project_name,COALESCE(c.company_name,c.name) client_name,au.name approved_by_name,cu.name cancelled_by_name FROM contract_variations v JOIN client_contracts cc ON cc.id=v.client_contract_id JOIN projects p ON p.id=cc.project_id JOIN clients c ON c.id=cc.client_id LEFT JOIN users au ON au.id=v.approved_by LEFT JOIN users cu ON cu.id=v.cancelled_by WHERE v.id=? LIMIT 1",[$id]);$row=$r instanceof \mysqli_result?$r->fetch_assoc():null;return is_array($row)?$row:null;}
 public function lockContract(int$id):?array{$r=$this->db->execute('SELECT id,status FROM client_contracts WHERE id=? FOR UPDATE',[$id]);$x=$r instanceof \mysqli_result?$r->fetch_assoc():null;return is_array($x)?$x:null;}
 public function lockVariation(int$id):?array{$r=$this->db->execute('SELECT * FROM contract_variations WHERE id=? FOR UPDATE',[$id]);$x=$r instanceof \mysqli_result?$r->fetch_assoc():null;return is_array($x)?$x:null;}
 public function hasCommittedStatementAllocation(int$id):bool{$r=$this->db->execute('SELECT 1 FROM client_progress_statement_variations WHERE contract_variation_id=? AND is_committed=1 LIMIT 1',[$id]);return$r instanceof \mysqli_result&&$r->num_rows>0;}
 public function numberExists(int $contractId,string $number,?int $exceptId=null):bool{$sql='SELECT 1 FROM contract_variations WHERE client_contract_id=? AND variation_number=?'.($exceptId===null?'':' AND id<>?').' LIMIT 1';$params=$exceptId===null?[$contractId,$number]:[$contractId,$number,$exceptId];$r=$this->db->execute($sql,$params);return $r instanceof \mysqli_result&&$r->num_rows>0;}
 public function create(string $code,ContractVariationData $d):int{$this->db->execute("INSERT INTO contract_variations(variation_code,client_contract_id,variation_number,variation_type,title,description,variation_date,effective_date,amount,amount_effect,markup_percentage,status,notes) VALUES(?,?,?,?,?,?,?,?,?,?,?,'draft',?)",[$code,$d->clientContractId,$d->variationNumber,$d->variationType,$d->title,$d->description,$d->variationDate,$d->effectiveDate,$d->amount,$d->amountEffect,$d->markupPercentage,$d->notes]);return (int)$this->db->connection()->insert_id;}
 public function updateDraft(int $id,ContractVariationData $d):void{$this->db->execute('UPDATE contract_variations SET variation_number=?,variation_type=?,title=?,description=?,variation_date=?,effective_date=?,amount=?,amount_effect=?,markup_percentage=?,notes=? WHERE id=?',[$d->variationNumber,$d->variationType,$d->title,$d->description,$d->variationDate,$d->effectiveDate,$d->amount,$d->amountEffect,$d->markupPercentage,$d->notes,$id]);}
 public function updateNotes(int $id,?string $notes):void{$this->db->execute('UPDATE contract_variations SET notes=? WHERE id=?',[$notes,$id]);}
 public function approve(int $id,int $userId):void{$this->db->execute("UPDATE contract_variations SET status='approved',approved_at=NOW(),approved_by=? WHERE id=? AND status='draft'",[$userId,$id]);}
 public function cancel(int $id,int $userId):void{$this->db->execute("UPDATE contract_variations SET status='cancelled',cancelled_at=NOW(),cancelled_by=? WHERE id=? AND status IN('draft','approved')",[$userId,$id]);}
 public function summary(int $contractId):array{$r=$this->db->execute("SELECT COALESCE(SUM(CASE WHEN status='approved' AND amount_effect='increase' THEN amount ELSE 0 END),0) increases,COALESCE(SUM(CASE WHEN status='approved' AND amount_effect='decrease' THEN amount ELSE 0 END),0) decreases,SUM(status='approved' AND amount_effect='none') non_financial FROM contract_variations WHERE client_contract_id=?",[$contractId]);$row=$r instanceof \mysqli_result?$r->fetch_assoc():null;return is_array($row)?$row:['increases'=>'0.00','decreases'=>'0.00','non_financial'=>0];}
 public function dataTable(ContractVariationTableQuery $q):array{$where=['v.client_contract_id=?'];$params=[$q->contractId];if($q->search!==''){$s='%'.$q->search.'%';$where[]='(v.variation_code LIKE ? OR v.variation_number LIKE ? OR v.title LIKE ? OR v.description LIKE ?)';array_push($params,$s,$s,$s,$s);}foreach(['v.variation_type'=>$q->type,'v.status'=>$q->status,'v.amount_effect'=>$q->effect] as $f=>$v){if($v!==null){$where[]="$f=?";$params[]=$v;}}$clause=' WHERE '.implode(' AND ',$where);$total=$this->db->execute('SELECT COUNT(*) total FROM contract_variations WHERE client_contract_id=?',[$q->contractId]);$filtered=$this->db->execute('SELECT COUNT(*) total FROM contract_variations v'.$clause,$params);$sort=['variation_code'=>'v.variation_code','variation_number'=>'v.variation_number','variation_type'=>'v.variation_type','title'=>'v.title','variation_date'=>'v.variation_date','amount'=>'v.amount','amount_effect'=>'v.amount_effect','status'=>'v.status'];$r=$this->db->execute('SELECT v.id,v.variation_code,v.variation_number,v.variation_type,v.title,v.variation_date,v.amount,v.amount_effect,v.status FROM contract_variations v'.$clause.' ORDER BY '.($sort[$q->sortColumn]??'v.variation_code').' '.$q->sortDirection.' LIMIT ? OFFSET ?',[...$params,$q->length,$q->start]);return ['recordsTotal'=>(int)(($total instanceof \mysqli_result?$total->fetch_assoc():[])['total']??0),'recordsFiltered'=>(int)(($filtered instanceof \mysqli_result?$filtered->fetch_assoc():[])['total']??0),'rows'=>$r instanceof \mysqli_result?$r->fetch_all(MYSQLI_ASSOC):[]];}
}
