<?php
declare(strict_types=1);
namespace App\Modules\Subcontracts\Repositories;
use App\Core\Database\Database;
use App\Modules\Subcontracts\DTOs\SubcontractData;
final class SubcontractRepository
{
    public function __construct(private readonly Database $db) {}
    public function find(int $id): ?array { $r=$this->db->execute('SELECT s.*,p.project_code,p.name project_name,v.vendor_code,v.name vendor_name,ws.section_code work_section_code,ws.name work_section_name FROM subcontracts s JOIN projects p ON p.id=s.project_id JOIN vendors v ON v.id=s.vendor_id LEFT JOIN work_sections ws ON ws.id=s.work_section_id WHERE s.id=? LIMIT 1',[$id]); $x=$r instanceof \mysqli_result?$r->fetch_assoc():null; return is_array($x)?$x:null; }
    public function project(int $id): bool { $r=$this->db->execute('SELECT 1 FROM projects WHERE id=? LIMIT 1',[$id]); return $r instanceof \mysqli_result&&$r->num_rows>0; }
    public function workSection(int $id): bool { $r=$this->db->execute('SELECT 1 FROM work_sections WHERE id=? AND is_active=1 LIMIT 1',[$id]); return $r instanceof \mysqli_result&&$r->num_rows>0; }
    public function vendor(int $id,bool $active): bool { $r=$this->db->execute("SELECT 1 FROM vendors WHERE id=? AND vendor_type IN('subcontractor','both')".($active?' AND is_active=1':'').' LIMIT 1',[$id]); return $r instanceof \mysqli_result&&$r->num_rows>0; }
    public function vendorInWorkSection(int $vendorId,int $sectionId): bool { $r=$this->db->execute('SELECT 1 FROM vendor_work_sections WHERE vendor_id=? AND work_section_id=? LIMIT 1',[$vendorId,$sectionId]); return $r instanceof \mysqli_result&&$r->num_rows>0; }
    public function numberExists(SubcontractData $data,?int $id): bool { $sql='SELECT 1 FROM subcontracts WHERE project_id=? AND vendor_id=? AND subcontract_number=?'.($id?' AND id<>?':'').' LIMIT 1'; $params=[$data->projectId,$data->vendorId,$data->number]; if($id)$params[]=$id; $r=$this->db->execute($sql,$params); return $r instanceof \mysqli_result&&$r->num_rows>0; }
    public function create(string $code,SubcontractData $data): int { $this->db->execute("INSERT INTO subcontracts(subcontract_code,subcontract_number,project_id,work_section_id,vendor_id,pricing_method,title,description,contract_date,start_date,expected_end_date,contract_value,status,notes) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,'draft',?)",[$code,$data->number,$data->projectId,$data->workSectionId,$data->vendorId,'boq',$data->title,$data->description,$data->contractDate,$data->startDate,$data->endDate,$data->value,$data->notes]); return (int)$this->db->connection()->insert_id; }
    public function update(int $id,SubcontractData $data,bool $commercial): void { if($commercial)$this->db->execute('UPDATE subcontracts SET subcontract_number=?,project_id=?,work_section_id=?,vendor_id=?,pricing_method=?,title=?,description=?,contract_date=?,start_date=?,expected_end_date=?,contract_value=?,notes=? WHERE id=?',[$data->number,$data->projectId,$data->workSectionId,$data->vendorId,'boq',$data->title,$data->description,$data->contractDate,$data->startDate,$data->endDate,$data->value,$data->notes,$id]); else $this->db->execute('UPDATE subcontracts SET start_date=?,expected_end_date=?,notes=? WHERE id=?',[$data->startDate,$data->endDate,$data->notes,$id]); }
    public function status(int $id,string $status): void { $this->db->execute('UPDATE subcontracts SET status=? WHERE id=?',[$status,$id]); }
    public function boq(int $id): ?array { $r=$this->db->execute('SELECT status FROM subcontract_boqs WHERE subcontract_id=? LIMIT 1',[$id]); $x=$r instanceof \mysqli_result?$r->fetch_assoc():null; return is_array($x)?$x:null; }
    public function refs(): array { foreach(['projects'=>'SELECT id,project_code,name FROM projects ORDER BY project_code','work_sections'=>'SELECT id,section_code,name FROM work_sections WHERE is_active=1 ORDER BY sort_order,section_code','vendors'=>"SELECT v.id,v.vendor_code,v.name,v.is_active FROM vendors v WHERE v.vendor_type IN('subcontractor','both') ORDER BY v.name"] as $key=>$sql){$r=$this->db->execute($sql);$references[$key]=$r instanceof \mysqli_result?$r->fetch_all(MYSQLI_ASSOC):[];} return $references; }
    public function vendorsForWorkSection(int $sectionId): array { $r=$this->db->execute("SELECT v.id,v.vendor_code,v.name,v.is_active FROM vendors v JOIN vendor_work_sections vws ON vws.vendor_id=v.id WHERE vws.work_section_id=? AND v.is_active=1 AND v.vendor_type IN('subcontractor','both') ORDER BY v.name",[$sectionId]); return $r instanceof \mysqli_result?$r->fetch_all(MYSQLI_ASSOC):[]; }
    public function all(): array { $r=$this->db->execute('SELECT s.id,s.subcontract_code,s.subcontract_number,s.project_id,s.work_section_id,s.vendor_id,p.name project_name,v.name vendor_name,ws.name work_section_name,s.title,s.contract_value,s.contract_date,s.status FROM subcontracts s JOIN projects p ON p.id=s.project_id JOIN vendors v ON v.id=s.vendor_id LEFT JOIN work_sections ws ON ws.id=s.work_section_id ORDER BY s.id DESC'); return $r instanceof \mysqli_result?$r->fetch_all(MYSQLI_ASSOC):[]; }
}
