<?php
declare(strict_types=1);
namespace App\Modules\ProjectCosts\Controllers;
use App\Core\Exceptions\BusinessRuleException;use App\Core\Exceptions\ValidationException;use App\Core\Http\Csrf;use App\Core\Http\Request;use App\Core\Http\Response;use App\Core\Http\Session;use App\Core\View\View;use App\Modules\AccessControl\Services\AuthorizationService;use App\Modules\ProjectCosts\Services\ProjectCostService;use App\Modules\ProjectCosts\Validators\ProjectCostValidator;
final class ProjectCostController{public function __construct(private readonly View$view,private readonly Csrf$csrf,private readonly Session$session,private readonly AuthorizationService$authorization,private readonly ProjectCostService$costs,private readonly ProjectCostValidator$validator){}
 public function global(Request$r):Response{return$this->listing(null);}
 public function project(Request$r):Response{return$this->listing((int)$r->route('project_id'));}
 private function listing(?int$projectId):Response{$refs=$this->costs->references();$project=$projectId===null?null:$this->costs->project($projectId);return Response::html($this->view->render('modules/project-costs/index',['title'=>'سجل التكاليف الفعلية','project'=>$project,'summary'=>$projectId? $this->costs->summary($projectId):null,'bySection'=>$projectId?$this->costs->getApprovedCostsByWorkSection($projectId):[],'byCode'=>$projectId?$this->costs->getApprovedCostsByCostCode($projectId):[],'projectId'=>$projectId,'canCreate'=>$this->authorization->can('project_costs.create'),...$refs]));}
 public function create(Request$r):Response{return$this->form(null,(int)$r->route('project_id'));}
 public function edit(Request$r):Response{return$this->form((int)$r->route('id'),null);}
 public function show(Request$r):Response{$entry=$this->costs->find((int)$r->route('id'));return Response::html($this->view->render('modules/project-costs/show',['title'=>'تفاصيل قيد التكلفة','entry'=>$entry,'canEdit'=>$this->authorization->can('project_costs.edit'),'canApprove'=>$this->authorization->can('project_costs.approve'),'canCancel'=>$this->authorization->can('project_costs.cancel')]));}
 public function store(Request$r):Response{return$this->save($r,null);}
 public function update(Request$r):Response{return$this->save($r,(int)$r->route('id'));}
 private function form(?int$id,?int$projectId):Response{$entry=$id===null?null:$this->costs->find($id);if($entry!==null&&$entry['status']!=='draft')return Response::redirect("/project-costs/{$id}");$refs=$this->costs->references();return Response::html($this->view->render('modules/project-costs/form',['title'=>$id===null?'إضافة تكلفة فعلية':'تعديل قيد التكلفة','entry'=>$entry,'fixedProject'=>$projectId===null?null:$this->costs->project($projectId),...$refs]));}
 private function save(Request$r,?int$id):Response{if(!$this->csrf->isValid($r->input('_token')))return Response::html('انتهت صلاحية الطلب.',419);try{$id=$this->costs->save($this->validator->validate($r->all()),$id);$this->flash('success','تم الحفظ','تم حفظ قيد التكلفة.');return Response::redirect("/project-costs/{$id}");}catch(ValidationException|BusinessRuleException$e){$m=$e instanceof ValidationException?(string)reset($e->errors[array_key_first($e->errors)]):$e->getMessage();$this->flash('error','تعذر الحفظ',$m);return Response::redirect($id?"/project-costs/{$id}/edit":"/projects/".(int)$r->input('project_id').'/costs/create');}}
 public function approve(Request$r):Response{return$this->transition($r,'approve','تم اعتماد قيد التكلفة.');}public function cancel(Request$r):Response{return$this->transition($r,'cancel','تم إلغاء مسودة التكلفة.');}
 private function transition(Request$r,string$action,string$message):Response{if(!$this->csrf->isValid($r->input('_token')))return Response::html('انتهت صلاحية الطلب.',419);$id=(int)$r->route('id');try{$this->costs->{$action}($id);$this->flash('success','تم التحديث',$message);}catch(BusinessRuleException$e){$this->flash('error','تعذر التحديث',$e->getMessage());}return Response::redirect("/project-costs/{$id}");}
 private function flash(string$type,string$title,string$text):void{$this->session->flash('alert',compact('type','title','text'));}}
