<?php
declare(strict_types=1);
use App\Core\Auth\Auth;use App\Core\Database\Database;use App\Core\Exceptions\BusinessRuleException;use App\Modules\ClientProgressStatements\DTOs\ClientProgressStatementData;use App\Modules\ClientProgressStatements\Services\ClientProgressStatementService;
/** @var Database $db */$db=$app->make(Database::class);/** @var ClientProgressStatementService $service */$service=$app->make(ClientProgressStatementService::class);/** @var Auth $auth */$auth=$app->make(Auth::class);
$user=$db->execute('SELECT id,name,username FROM users WHERE is_active=1 LIMIT 1')->fetch_assoc();$unit=$db->execute('SELECT id,name_ar,symbol_ar FROM units WHERE is_active=1 LIMIT 1')->fetch_assoc();if(!$user||!$unit)throw new RuntimeException('BOQ CPS fixtures unavailable.');$suffix=(string)random_int(100000,999999);$client=$project=$contract=$boq=$section=$item=$variation=0;
try{
$db->execute("INSERT INTO clients(client_code,client_type,name)VALUES(?,'individual','BOQ CPS Client')",['BCPSC-'.$suffix]);$client=(int)$db->connection()->insert_id;$db->execute("INSERT INTO projects(project_code,name,client_id,project_type,status)VALUES(?,'BOQ CPS Project',?,'contracting','active')",['BCPSP-'.$suffix,$client]);$project=(int)$db->connection()->insert_id;$db->execute("INSERT INTO client_contracts(contract_code,contract_number,project_id,client_id,pricing_method,contract_date,contract_value,title,status)VALUES(?,?,?,?, 'boq','2026-01-01','30.00','BOQ CPS Contract','active')",['BCPS-'.$suffix,'N-'.$suffix,$project,$client]);$contract=(int)$db->connection()->insert_id;
$db->execute("INSERT INTO contract_boqs(client_contract_id,status,approved_at,approved_by)VALUES(?,'approved',NOW(),?)",[$contract,(int)$user['id']]);$boq=(int)$db->connection()->insert_id;$db->execute("INSERT INTO contract_boq_sections(contract_boq_id,section_code,title,sort_order)VALUES(?,'01','أعمال اختبار',1)",[$boq]);$section=(int)$db->connection()->insert_id;$db->execute("INSERT INTO contract_boq_items(contract_boq_section_id,item_code,description,unit_id,unit_name,unit_symbol,quantity,unit_rate,sort_order)VALUES(?,NULL,'بند اختبار',?,?,?,?, '10.00',1)",[$section,(int)$unit['id'],$unit['name_ar'],$unit['symbol_ar'],'3.0000']);$item=(int)$db->connection()->insert_id;$auth->login($user);
$first=$service->save($contract,new ClientProgressStatementData('2026-09-01',null,null,'B-1',null,[],[],[$item=>'1.2345']));$draft=$db->execute('SELECT * FROM client_progress_statement_boq_items WHERE statement_id=?',[$first])->fetch_assoc();if(!$draft||$draft['current_quantity']!=='1.2345'||(int)$draft['is_committed']!==0||$draft['description_snapshot']!==null)throw new RuntimeException('Complete BOQ draft seeding failed.');$service->approve($first);$approved=$service->find($first);if($approved['pricing_method_snapshot']!=='boq'||$approved['current_boq_amount']!=='12.35'||$approved['current_statement_amount']!=='12.35'||$approved['current_cost_amount']!==null||$approved['current_markup_amount']!==null||$approved['markup_percentage_snapshot']!==null)throw new RuntimeException('BOQ header calculation failed.');$line=$db->execute('SELECT * FROM client_progress_statement_boq_items WHERE statement_id=?',[$first])->fetch_assoc();if($line['previous_quantity']!=='0.0000'||$line['cumulative_quantity']!=='1.2345'||$line['current_amount']!=='12.35'||$line['item_code_snapshot']!==null||(int)$line['is_committed']!==1)throw new RuntimeException('BOQ snapshots failed.');
$second=$service->save($contract,new ClientProgressStatementData('2026-09-01',null,null,'B-2',null,[],[],[$item=>'0.7655']));$service->approve($second);$line2=$db->execute('SELECT * FROM client_progress_statement_boq_items WHERE statement_id=?',[$second])->fetch_assoc();if($line2['previous_quantity']!=='1.2345'||$line2['cumulative_quantity']!=='2.0000'||$line2['previous_amount']!=='12.35'||$line2['current_amount']!=='7.66'||$line2['cumulative_amount']!=='20.01')throw new RuntimeException('Previous amount or exact BOQ calculation failed.');
$staleA=$service->save($contract,new ClientProgressStatementData('2026-09-02',null,null,'B-3',null,[],[],[$item=>'0.6000']));$staleB=$service->save($contract,new ClientProgressStatementData('2026-09-02',null,null,'B-4',null,[],[],[$item=>'0.6000']));$service->approve($staleA);try{$service->approve($staleB);throw new RuntimeException('Stale BOQ draft exceeded contract quantity.');}catch(BusinessRuleException){}
$db->execute("INSERT INTO contract_variations(variation_code,client_contract_id,title,variation_type,variation_date,amount,amount_effect,status,approved_at,approved_by)VALUES(? ,?,'BOQ Increase','additional_work','2026-09-02','5.00','increase','approved',NOW(),?)",['BCPV-'.$suffix,$contract,(int)$user['id']]);$variation=(int)$db->connection()->insert_id;$positive=$service->save($contract,new ClientProgressStatementData('2026-09-03',null,null,'B-5',null,[],[['variation_id'=>$variation,'current_billed_amount'=>'5.00']],[$item=>'0.0000']));$service->approve($positive);if($service->find($positive)['current_statement_amount']!=='5.00')throw new RuntimeException('Pure positive Variation BOQ statement failed.');
}finally{$auth->logout();if($contract){$db->execute('DELETE d FROM client_progress_statement_boq_items d JOIN client_progress_statements s ON s.id=d.statement_id WHERE s.client_contract_id=?',[$contract]);$db->execute('DELETE d FROM client_progress_statement_variations d JOIN client_progress_statements s ON s.id=d.statement_id WHERE s.client_contract_id=?',[$contract]);$db->execute('DELETE FROM client_progress_statements WHERE client_contract_id=?',[$contract]);}$variation&&$db->execute('DELETE FROM contract_variations WHERE id=?',[$variation]);$item&&$db->execute('DELETE FROM contract_boq_items WHERE id=?',[$item]);$section&&$db->execute('DELETE FROM contract_boq_sections WHERE id=?',[$section]);$boq&&$db->execute('DELETE FROM contract_boqs WHERE id=?',[$boq]);$contract&&$db->execute('DELETE FROM client_contracts WHERE id=?',[$contract]);$project&&$db->execute('DELETE FROM projects WHERE id=?',[$project]);$client&&$db->execute('DELETE FROM clients WHERE id=?',[$client]);}
