<?php
declare(strict_types=1);
use App\Core\Auth\Auth;use App\Core\Database\Database;use App\Core\Exceptions\BusinessRuleException;use App\Modules\Accounting\Services\AccountingService;use App\Modules\EmployeeCustodies\DTOs\CustodyData;use App\Modules\EmployeeCustodies\DTOs\SettlementData;use App\Modules\EmployeeCustodies\Services\CustodyService;
/** @var Database $db */$db=$app->make(Database::class);/** @var CustodyService $service */$service=$app->make(CustodyService::class);/** @var AccountingService $accounting */$accounting=$app->make(AccountingService::class);/** @var Auth $auth */$auth=$app->make(Auth::class);
$user=$db->execute('SELECT id,name,username FROM users WHERE is_active=1 LIMIT 1')->fetch_assoc();$auth->login($user);$suffix=(string)random_int(100000,999999);$year=2097;$client=$project=$employee=0;$custodies=[];
try{$accounting->createYear($year);$db->execute('INSERT INTO clients(client_code,client_type,name) VALUES(?,\'individual\',?)',['CUST-CL-'.$suffix,'Custody Client']);$client=(int)$db->connection()->insert_id;$db->execute('INSERT INTO projects(project_code,name,client_id,project_type,status) VALUES(?,?,?,\'contracting\',\'active\')',['CUST-PRJ-'.$suffix,'Custody Project',$client]);$project=(int)$db->connection()->insert_id;$db->execute('INSERT INTO employees(employee_code,name) VALUES(?,?)',['CUST-EMP-'.$suffix,'Custody Employee']);$employee=(int)$db->connection()->insert_id;$cash=(int)$db->execute('SELECT account_id FROM accounting_setup WHERE mapping_key=?',['cash_on_hand'])->fetch_assoc()['account_id'];$costCode=(int)$db->execute('SELECT id FROM cost_codes WHERE is_active=1 LIMIT 1')->fetch_assoc()['id'];$expense=(int)$db->execute('SELECT id FROM accounts WHERE account_code=?',['590001'])->fetch_assoc()['id'];$accounting->saveCostCodeMapping($costCode,$expense);
$id=$service->save(new CustodyData($employee,$project,$year.'-01-02','0.30','cash',$cash,'Test custody'));$custodies[]=$id;$service->issue($id);$issued=$service->find($id);if($issued['status']!=='issued'||$issued['remaining_amount']!=='0.30')throw new RuntimeException('Custody issue failed.');$pac=$db->execute('SELECT COUNT(*) n FROM project_actual_costs WHERE source_type=\'employee_custody_settlement\'')->fetch_assoc();if((int)$pac['n']!==0)throw new RuntimeException('Custody issue created a Project Actual Cost.');$balance=$db->execute('SELECT CAST(SUM(l.debit) AS DECIMAL(18,2)) d,CAST(SUM(l.credit) AS DECIMAL(18,2)) c FROM journal_lines l WHERE l.journal_entry_id=?',[(int)$issued['issue_journal_entry_id']])->fetch_assoc();if($balance['d']!==$balance['c']||$balance['d']!=='0.30')throw new RuntimeException('Custody issue journal is not balanced.');
$service->settle($id,new SettlementData('expense',$year.'-01-03','Project expense','0.10',$project,$costCode,null,null));$details=$service->details($id);if(count($details['settlements'])!==1||$details['settlements'][0]['project_actual_cost_id']===null)throw new RuntimeException('Expense settlement did not create one PAC.');$settlementId=(int)$details['settlements'][0]['id'];try{$accounting->createPostedAutomatic($year.'-01-03','Duplicate','employee_custody_settlement',$settlementId,null,[]);throw new RuntimeException('Duplicate settlement posting accepted.');}catch(BusinessRuleException){}
try{$service->settle($id,new SettlementData('cash_return',$year.'-01-04','Over return','0.21',null,null,$cash,null));throw new RuntimeException('Over-settlement accepted.');}catch(BusinessRuleException){}$service->settle($id,new SettlementData('cash_return',$year.'-01-04','Cash return','0.20',null,null,$cash,null));$settled=$service->find($id);if($settled['status']!=='settled'||$settled['remaining_amount']!=='0.00')throw new RuntimeException('Final custody balance/status is incorrect.');$effects=$db->execute('SELECT COUNT(*) n FROM project_actual_costs WHERE source_type=\'employee_custody_settlement\' AND source_id=?',[$settlementId])->fetch_assoc();if((int)$effects['n']!==1)throw new RuntimeException('Expense settlement PAC was duplicated.');
$cancel=$service->save(new CustodyData($employee,null,$year.'-01-05','1.00','cash',$cash,null));$custodies[]=$cancel;$service->cancel($cancel);$cancelled=$service->find($cancel);if($cancelled['status']!=='cancelled'||$cancelled['issue_journal_entry_id']!==null)throw new RuntimeException('Cancelled draft had a financial effect.');
}finally{$auth->logout();if($custodies){$marks=implode(',',array_fill(0,count($custodies),'?'));$journals=$db->execute('SELECT journal_entry_id id FROM employee_custody_settlements WHERE custody_id IN('.$marks.') UNION SELECT issue_journal_entry_id id FROM employee_custodies WHERE id IN('.$marks.')',[...$custodies,...$custodies]);$journalIds=[];foreach($journals->fetch_all(MYSQLI_ASSOC)as$j)if($j['id']!==null)$journalIds[]=(int)$j['id'];$costs=$db->execute('SELECT project_actual_cost_id id FROM employee_custody_settlements WHERE custody_id IN('.$marks.')',$custodies)->fetch_all(MYSQLI_ASSOC);$db->execute('DELETE FROM employee_custody_settlements WHERE custody_id IN('.$marks.')',$custodies);foreach($custodies as$c)$db->execute('DELETE FROM employee_custodies WHERE id=?',[$c]);foreach($costs as$c)if($c['id']!==null)$db->execute('DELETE FROM project_actual_costs WHERE id=?',[(int)$c['id']]);foreach(array_unique($journalIds)as$j){$db->execute('DELETE FROM journal_lines WHERE journal_entry_id=?',[$j]);$db->execute('DELETE FROM journal_entries WHERE id=?',[$j]);}}if($employee)$db->execute('DELETE FROM employees WHERE id=?',[$employee]);if($project)$db->execute('DELETE FROM projects WHERE id=?',[$project]);if($client)$db->execute('DELETE FROM clients WHERE id=?',[$client]);$db->execute('DELETE FROM accounting_periods WHERE fiscal_year=?',[$year]);}
