<?php
declare(strict_types=1);
use App\Core\Auth\Auth;use App\Core\Database\Database;use App\Core\Exceptions\BusinessRuleException;use App\Modules\ProjectCosts\DTOs\ProjectCostData;use App\Modules\ProjectCosts\Services\ProjectCostService;
/** @var Database $db */$db=$app->make(Database::class);/** @var ProjectCostService $service */$service=$app->make(ProjectCostService::class);/** @var Auth $auth */$auth=$app->make(Auth::class);
$user=$db->execute('SELECT id,name,username FROM users WHERE is_active=1 LIMIT 1')->fetch_assoc();$code=$db->execute('SELECT c.id,c.cost_code,c.name,w.section_code,w.name section_name FROM cost_codes c JOIN work_sections w ON w.id=c.work_section_id WHERE c.is_active=1 AND w.is_active=1 LIMIT 1')->fetch_assoc();if(!$user||!$code)throw new RuntimeException('Project cost workflow fixtures unavailable.');
$suffix=(string)random_int(100000,999999);$clientId=$projectId=$vendorId=0;
try{$db->execute("INSERT INTO clients(client_code,client_type,name)VALUES(?,'individual','Test Client')",['TCL-'.$suffix]);$clientId=(int)$db->connection()->insert_id;$db->execute("INSERT INTO projects(project_code,name,client_id,project_type,status)VALUES(?,'Test Completed Project',?,'contracting','completed')",['TPR-'.$suffix,$clientId]);$projectId=(int)$db->connection()->insert_id;$db->execute("INSERT INTO vendors(vendor_code,vendor_type,name)VALUES(?,'supplier','Test Vendor')",['TVN-'.$suffix]);$vendorId=(int)$db->connection()->insert_id;$auth->login($user);
 $draft=$service->save(new ProjectCostData($projectId,'2026-08-20',(int)$code['id'],$vendorId,'Late cost',null,'1250.50',null));$row=$service->find($draft);if($row['source_type']!==ProjectCostService::SOURCE_MANUAL||$row['source_id']!==null||$row['approved_at']!==null||$row['cost_code_snapshot']!==null)throw new RuntimeException('Draft system state is invalid.');
 $service->save(new ProjectCostData($projectId,'2026-05-10',(int)$code['id'],$vendorId,'Backdated cost',null,'1250.50',null),$draft);
 $db->execute('UPDATE vendors SET is_active=0 WHERE id=?',[$vendorId]);try{$service->approve($draft);throw new RuntimeException('Inactive vendor approval accepted.');}catch(BusinessRuleException){}$db->execute('UPDATE vendors SET is_active=1 WHERE id=?',[$vendorId]);$service->approve($draft);$approved=$service->find($draft);if($approved['status']!=='approved'||$approved['approved_by']===null||$approved['cost_code_snapshot']!==$code['cost_code']||$approved['work_section_code_snapshot']!==$code['section_code'])throw new RuntimeException('Approval audit or snapshots failed.');
 $db->execute('UPDATE vendors SET is_active=0 WHERE id=?',[$vendorId]);if($service->getApprovedProjectCostTotal($projectId)!=='1250.50')throw new RuntimeException('Approved total or historical vendor behavior failed.');try{$service->cancel($draft);throw new RuntimeException('Approved cost cancellation accepted.');}catch(BusinessRuleException){}
 $second=$service->save(new ProjectCostData($projectId,'2026-01-10',(int)$code['id'],null,'Draft',null,'10.00',null));try{$service->save(new ProjectCostData($projectId,'2027-01-10',(int)$code['id'],null,'Draft',null,'10.00',null),$second);throw new RuntimeException('Cross-year edit accepted.');}catch(BusinessRuleException){}if($service->getApprovedProjectCostTotal($projectId)!=='1250.50')throw new RuntimeException('Draft entered approved totals.');$service->cancel($second);$cancelled=$service->find($second);if($cancelled['cancelled_by']===null||$cancelled['approved_by']!==null)throw new RuntimeException('Cancellation audit failed.');if($service->getApprovedProjectCostTotal($projectId)!=='1250.50')throw new RuntimeException('Cancelled draft entered totals.');
 $db->execute("UPDATE projects SET status='cancelled' WHERE id=?",[$projectId]);try{$service->save(new ProjectCostData($projectId,'2026-09-01',(int)$code['id'],null,'Rejected',null,'1.00',null));throw new RuntimeException('Cancelled project accepted a cost.');}catch(BusinessRuleException){}
}finally{$auth->logout();if($projectId){$db->execute('DELETE FROM project_actual_costs WHERE project_id=?',[$projectId]);}$vendorId&&$db->execute('DELETE FROM vendors WHERE id=?',[$vendorId]);$projectId&&$db->execute('DELETE FROM projects WHERE id=?',[$projectId]);$clientId&&$db->execute('DELETE FROM clients WHERE id=?',[$clientId]);}
