<?php
$approved=$order['status']==='approved';
$status=['draft'=>'مسودة','approved'=>'معتمد','cancelled'=>'ملغي'][$order['status']]??$order['status'];
$vendor=$approved?$order['vendor_code_snapshot'].' - '.$order['vendor_name_snapshot']:$order['current_vendor_code'].' - '.$order['current_vendor_name'];
$project=$approved?$order['project_code_snapshot'].' - '.$order['project_name_snapshot']:$order['current_project_code'].' - '.$order['current_project_name'];
?>
<div class="page-header mb-4"><div class="row"><div class="col"><div class="page-pretitle"><?=e($order['po_code'])?></div><h2 class="page-title">أمر شراء</h2></div><div class="col-auto"><?php if($approved):?><a class="btn" target="_blank" href="/purchase-orders/<?=(int)$order['id']?>/print"><i class="ti ti-printer"></i> طباعة</a><?php endif;?><?php if($order['status']==='draft'&&$canEdit):?><a class="btn" href="/purchase-orders/<?=(int)$order['id']?>/edit"><i class="ti ti-edit"></i> تعديل</a><?php endif;?></div></div></div>
<div class="alert alert-info"><i class="ti ti-info-circle"></i> اعتماد أمر الشراء يمثل التزام شراء فقط، ولا ينشئ تكلفة فعلية أو ذمة أو دفعة للمورد.</div>
<div class="card mb-4"><div class="card-body"><div class="row g-3"><?php foreach(['الحالة'=>$status,'تاريخ الأمر'=>$order['po_date'],'التوريد المتوقع'=>$order['expected_date']?:'—','المورد'=>$vendor,'المشروع'=>$project,'المرجع'=>$order['reference']?:'—','أنشئ بواسطة'=>$order['created_by_name']] as $label=>$value):?><div class="col-md-3"><div class="small text-secondary"><?=$label?></div><strong><?=e((string)$value)?></strong></div><?php endforeach;?></div><?php if($order['notes']):?><hr><div class="small text-secondary">ملاحظات</div><div><?=nl2br(e($order['notes']))?></div><?php endif;?></div></div>
<div class="card mb-4"><div class="table-responsive"><table class="table card-table"><thead><tr><th>#</th><th>الوصف</th><th>القسم / كود التكلفة</th><th>الكمية</th><th>سعر الوحدة</th><th>الإجمالي</th></tr></thead><tbody><?php foreach($lines as $line):?><tr><td><?=(int)$line['sort_order']?></td><td><?=e($line['description'])?></td><td><?=e(($approved?$line['work_section_code_snapshot']:$line['current_section_code']).' / '.($approved?$line['cost_code_snapshot']:$line['current_cost_code']))?></td><td><?=decimal_format($line['quantity'],4)?></td><td><?=decimal_format($line['unit_price'])?></td><td><?=decimal_format($line['line_total'])?></td></tr><?php endforeach;?></tbody><tfoot><tr><th colspan="5">الإجمالي</th><th><?=decimal_format($order['total_amount']??$displayTotal)?></th></tr></tfoot></table></div></div>
<?php if($order['status']==='draft'):?><div class="d-flex gap-2"><?php if($canApprove):?><form method="post" action="/purchase-orders/<?=(int)$order['id']?>/approve" class="js-confirm-form" data-confirm="سيتم اعتماد أمر الشراء كالتزام شراء فقط ولن يمكن تعديله بعد الاعتماد. هل تريد المتابعة؟"><input type="hidden" name="_token" value="<?=e($csrfToken)?>"><button class="btn btn-success"><i class="ti ti-check"></i> اعتماد</button></form><?php endif;?><?php if($canCancel):?><form method="post" action="/purchase-orders/<?=(int)$order['id']?>/cancel" class="js-confirm-form" data-confirm="هل تريد إلغاء مسودة أمر الشراء؟ لن ينتج عن الإلغاء أي أثر مالي."><input type="hidden" name="_token" value="<?=e($csrfToken)?>"><button class="btn btn-danger"><i class="ti ti-x"></i> إلغاء</button></form><?php endif;?></div><?php endif;?>
