<?php
declare(strict_types=1);
namespace App\Modules\ClientContracts\Services;
use App\Core\Database\Database;use App\Core\Exceptions\BusinessRuleException;use App\Modules\ClientContracts\DTOs\ClientContractData;use App\Modules\ClientContracts\DTOs\ClientContractTableQuery;use App\Modules\ClientContracts\Repositories\ClientContractRepository;use App\Shared\Numbering\NumberGeneratorService;
final class ClientContractService
{
 private const TRANSITIONS=['draft'=>['active','cancelled'],'active'=>['suspended','completed','cancelled'],'suspended'=>['active','completed','cancelled'],'completed'=>[],'cancelled'=>[]];
 public function __construct(private readonly ClientContractRepository $contracts,private readonly NumberGeneratorService $numbers,private readonly Database $db){}
 public function find(int $id):array{return $this->contracts->find($id)??throw new BusinessRuleException('عقد العميل غير موجود.');}
 public function save(ClientContractData $d,?int $id=null):int{$existing=$id===null?null:$this->find($id);$this->relations($d,$id,$existing);return $this->db->transaction(function()use($d,$id,$existing){if($id===null){$year=(int)substr($d->contractDate,0,4);return $this->contracts->create($this->numbers->nextClientContractCode($year),$d);}if((int)$existing['project_id']!==$d->projectId)throw new BusinessRuleException('لا يمكن تغيير مشروع العقد بعد إنشائه.');$boq=$this->contracts->boqState($id);if($boq&&$boq['status']==='approved'&&($d->pricingMethod!==(string)$existing['pricing_method']||$d->contractValue!==(string)$existing['contract_value']))throw new BusinessRuleException('قيمة وطريقة تسعير العقد محميتان بجدول كميات معتمد.');if($existing['status']==='draft')$this->contracts->updateDraft($id,$d);else{$this->assertCommercialUnchanged($existing,$d);$this->contracts->updateAdministrative($id,$d);}return $id;});}
 public function changeStatus(int $id,string $status):void{$c=$this->find($id);$current=(string)$c['status'];if($status===$current)throw new BusinessRuleException('العقد موجود بالفعل في هذه الحالة.');if(!in_array($status,self::TRANSITIONS[$current]??[],true))throw new BusinessRuleException('انتقال حالة العقد المطلوب غير مسموح.');if($status==='active'){if(trim((string)$c['contract_number'])==='')throw new BusinessRuleException('يجب إدخال رقم العقد التجاري قبل التفعيل.');$boq=$this->contracts->boqState($id);if($c['pricing_method']==='boq'&&(!$boq||$boq['status']!=='approved'))throw new BusinessRuleException('يجب اعتماد جدول الكميات قبل تفعيل عقد BOQ.');if($boq&&$boq['status']!=='approved')throw new BusinessRuleException('يجب اعتماد أو حذف نطاق العقد الاختياري قبل التفعيل.');}$this->contracts->changeStatus($id,$status);}
 public function allowedTransitions(string $status):array{return self::TRANSITIONS[$status]??[];}public function references(?int $id=null):array{return $this->contracts->references($id);}public function filterReferences():array{return $this->contracts->filterReferences();}public function contacts(int $projectId):array{if($this->contracts->project($projectId)===null)throw new BusinessRuleException('المشروع غير موجود.');return $this->contracts->contactsForProject($projectId);}public function dataTable(ClientContractTableQuery $q):array{$r=$this->contracts->dataTable($q);return ['draw'=>$q->draw,'recordsTotal'=>$r['recordsTotal'],'recordsFiltered'=>$r['recordsFiltered'],'data'=>$r['rows']];}
 private function relations(ClientContractData $d,?int $id,?array $existing):void{$p=$this->contracts->project($d->projectId)??throw new BusinessRuleException('المشروع غير موجود.');if((int)$p['client_id']!==$d->clientId)throw new BusinessRuleException('العميل لا يطابق عميل المشروع.');if($this->contracts->contractForProject($d->projectId,$id))throw new BusinessRuleException('يوجد عقد رئيسي لهذا المشروع بالفعل.');if($d->clientContactId!==null&&!$this->contracts->contactBelongsTo($d->clientContactId,$d->clientId))throw new BusinessRuleException('جهة الاتصال لا تتبع عميل المشروع.');if($d->contractNumber!==null&&$this->contracts->numberExists($d->contractNumber,$id))throw new BusinessRuleException('رقم العقد التجاري مستخدم بالفعل.');}
 private function assertCommercialUnchanged(array $c,ClientContractData $d):void{foreach(['client_id'=>(string)$d->clientId,'pricing_method'=>$d->pricingMethod,'contract_number'=>$d->contractNumber,'contract_value'=>$d->contractValue,'markup_percentage'=>$d->markupPercentage,'contract_date'=>$d->contractDate,'title'=>$d->title,'description'=>$d->description,'terms'=>$d->terms] as $field=>$value){$old=$c[$field]===null?null:(string)$c[$field];if($old!==$value)throw new BusinessRuleException('لا يمكن تعديل البنود التجارية بعد تفعيل العقد. استخدم ملحق عقد مستقبلًا.');}}
}
