<?php
declare(strict_types=1);
namespace App\Modules\ProjectCosts\Services;
use App\Core\Auth\Auth;use App\Core\Database\Database;use App\Core\Exceptions\BusinessRuleException;use App\Modules\ProjectCosts\DTOs\ProjectCostData;use App\Modules\ProjectCosts\DTOs\ProjectCostTableQuery;use App\Modules\ProjectCosts\Repositories\ProjectCostRepository;use App\Shared\Numbering\NumberGeneratorService;
final class ProjectCostService{public const SOURCE_MANUAL='manual';private const PROJECT_STATUSES=['planning','active','on_hold','completed'];public function __construct(private readonly ProjectCostRepository$costs,private readonly NumberGeneratorService$numbers,private readonly Database$db,private readonly Auth$auth){}
 public function find(int$id):array{return$this->costs->find($id)??throw new BusinessRuleException('قيد التكلفة غير موجود.');}
 public function save(ProjectCostData$d,?int$id=null):int{return$this->db->transaction(function()use($d,$id){$old=$id===null?null:$this->find($id);if($old!==null&&(int)$old['project_id']!==$d->projectId)throw new BusinessRuleException('لا يمكن تغيير المشروع لمسودة قائمة.');$project=$this->costs->project($d->projectId,true)??throw new BusinessRuleException('المشروع غير موجود.');if(!in_array($project['status'],self::PROJECT_STATUSES,true))throw new BusinessRuleException('لا يمكن إضافة تكلفة إلى مشروع ملغي.');if($old!==null){$old=$this->costs->lockEntry($id);if($old['status']!=='draft')throw new BusinessRuleException('يمكن تعديل المسودة فقط.');if($this->year($old)!==substr($d->costDate,0,4))throw new BusinessRuleException('لا يمكن تغيير سنة تاريخ التكلفة. ألغِ المسودة وأنشئ قيداً جديداً.');}$this->validateMasters($d);if($id===null)return$this->costs->create($this->numbers->nextProjectActualCostCode((int)substr($d->costDate,0,4)),$d,$this->user());$this->costs->update($id,$d);return$id;});}
 public function approve(int$id):void{$probe=$this->find($id);$this->db->transaction(function()use($id,$probe){$project=$this->costs->project((int)$probe['project_id'],true)??throw new BusinessRuleException('المشروع غير موجود.');$entry=$this->costs->lockEntry($id)??throw new BusinessRuleException('قيد التكلفة غير موجود.');if($entry['status']!=='draft')throw new BusinessRuleException('يمكن اعتماد المسودة فقط.');if(!in_array($project['status'],self::PROJECT_STATUSES,true))throw new BusinessRuleException('لا يمكن اعتماد تكلفة لمشروع ملغي.');$master=$this->costs->costCode((int)$entry['cost_code_id'],true)??throw new BusinessRuleException('كود التكلفة غير موجود.');if(!(bool)$master['cost_code_active']||!(bool)$master['work_section_active'])throw new BusinessRuleException('كود التكلفة أو قسم الأعمال غير نشط.');if($entry['vendor_id']!==null){$vendor=$this->costs->vendor((int)$entry['vendor_id'],true);if($vendor===null||!(bool)$vendor['is_active'])throw new BusinessRuleException('المورد المحدد غير موجود أو أصبح غير نشط.');}if(!preg_match('/^(?!0+(?:\.0{1,2})?$)\d{1,16}(?:\.\d{1,2})?$/',(string)$entry['amount']))throw new BusinessRuleException('مبلغ التكلفة غير صالح.');if($this->year($entry)!==substr((string)$entry['cost_date'],0,4))throw new BusinessRuleException('سنة كود القيد لا تطابق سنة تاريخ التكلفة.');$this->costs->approve($id,$this->user(),['section_code'=>$master['section_code'],'work_section_name'=>$master['work_section_name'],'cost_code'=>$master['cost_code'],'cost_code_name'=>$master['cost_code_name']]);});}
 public function cancel(int$id):void{$probe=$this->find($id);$this->db->transaction(function()use($id,$probe){$this->costs->project((int)$probe['project_id'],true);$entry=$this->costs->lockEntry($id)??throw new BusinessRuleException('قيد التكلفة غير موجود.');if($entry['status']!=='draft')throw new BusinessRuleException('يمكن إلغاء المسودة فقط.');$this->costs->cancel($id,$this->user());});}
 private function validateMasters(ProjectCostData$d):void{$code=$this->costs->costCode($d->costCodeId,true);if($code===null||!(bool)$code['cost_code_active']||!(bool)$code['work_section_active'])throw new BusinessRuleException('اختر كود تكلفة نشطاً تابعاً لقسم أعمال نشط.');if($d->vendorId!==null){$v=$this->costs->vendor($d->vendorId,true);if($v===null||!(bool)$v['is_active'])throw new BusinessRuleException('اختر مورداً نشطاً.');}}
 private function year(array$e):string{return preg_match('/^COST-(\d{4})-/',(string)$e['cost_entry_code'],$m)?$m[1]:'';}private function user():int{return$this->auth->id()??throw new BusinessRuleException('تعذر تحديد المستخدم الحالي.');}
 public function getApprovedProjectCostTotal(int$id):string{$this->project($id);return$this->costs->total($id);}public function getApprovedCostsByCostCode(int$id):array{$this->project($id);return$this->costs->byCostCode($id);}public function getApprovedCostsByWorkSection(int$id):array{$this->project($id);return$this->costs->byWorkSection($id);}public function project(int$id):array{return$this->costs->project($id)??throw new BusinessRuleException('المشروع غير موجود.');}public function references():array{return$this->costs->references();}public function summary(int$id):array{$this->project($id);return$this->costs->summary($id);}public function dataTable(ProjectCostTableQuery$q):array{$r=$this->costs->dataTable($q);return['draw'=>$q->draw,'recordsTotal'=>$r['recordsTotal'],'recordsFiltered'=>$r['recordsFiltered'],'data'=>$r['rows']];}}
