<?php
declare(strict_types=1);
namespace App\Modules\EmployeeCustodies\Validators;
use App\Core\Exceptions\ValidationException;
use App\Modules\EmployeeCustodies\DTOs\SettlementData;
final class SettlementValidator
{
 public function validate(array$i,string$type):SettlementData{$e=[];$date=$this->date($i['settlement_date']??null);$description=trim((string)($i['description']??''));$amount=$this->decimal($i['amount']??null);$project=$this->optionalId($i['project_id']??null);$cost=$this->optionalId($i['cost_code_id']??null);$account=$this->optionalId($i['return_account_id']??null);if(!in_array($type,['expense','cash_return'],true))$e['settlement_type'][]='نوع التسوية غير صالح.';if($date===null)$e['settlement_date'][]='تاريخ التسوية غير صالح.';if($description===''||mb_strlen($description)>500)$e['description'][]='وصف التسوية مطلوب وبحد أقصى 500 حرف.';if($amount===null)$e['amount'][]='مبلغ التسوية غير صالح.';if($type==='expense'&&($project===null||$cost===null))$e['project_id'][]='المشروع وكود التكلفة مطلوبان لتسوية المصروف.';if($type==='cash_return'&&$account===null)$e['return_account_id'][]='حساب رد النقدية مطلوب.';$reference=$this->nullable($i['reference']??null);if($reference!==null&&mb_strlen($reference)>190)$e['reference'][]='المرجع يتجاوز 190 حرفًا.';if($e)throw new ValidationException($e);return new SettlementData($type,(string)$date,$description,(string)$amount,$type==='expense'?$project:null,$type==='expense'?$cost:null,$type==='cash_return'?$account:null,$reference);}
 private function decimal(mixed$v):?string{$v=trim((string)$v);if(!preg_match('/^\d{1,16}(?:\.\d{1,2})?$/D',$v))return null;[$w,$f]=array_pad(explode('.',$v,2),2,'');$w=ltrim($w,'0');$n=($w===''?'0':$w).'.'.str_pad($f,2,'0');return$n==='0.00'?null:$n;}private function id(mixed$v):?int{$x=filter_var($v,FILTER_VALIDATE_INT,['options'=>['min_range'=>1]]);return$x===false?null:$x;}private function optionalId(mixed$v):?int{return trim((string)$v)===''?null:$this->id($v);}private function date(mixed$v):?string{$v=trim((string)$v);$d=\DateTimeImmutable::createFromFormat('!Y-m-d',$v);return$d&&$d->format('Y-m-d')===$v?$v:null;}private function nullable(mixed$v):?string{$v=trim((string)$v);return$v===''?null:$v;}
}
