<?php $displayName=(string)($client['client_type']==='company'?$client['company_name']:$client['name']); ?>
<div class="page-header mb-4"><div class="row align-items-center"><div class="col"><div class="page-pretitle"><?=e($client['client_code'])?></div><h2 class="page-title"><?=e($displayName)?></h2></div><div class="col-auto d-flex gap-2"><?php if($canEdit):?><a class="btn btn-primary" href="/clients/<?=(int)$client['id']?>/edit"><i class="ti ti-edit ms-2"></i>تعديل</a><?php endif;?><a class="btn" href="/clients">العودة</a></div></div></div>
<div class="row g-4"><div class="col-lg-5"><div class="card"><div class="card-header"><h3 class="card-title">بيانات العميل</h3></div><div class="card-body"><dl class="row mb-0">
<?php foreach(['client_code'=>'كود العميل','client_type'=>'النوع','tax_number'=>'الرقم الضريبي','commercial_registration'=>'السجل التجاري','phone'=>'الهاتف','mobile'=>'المحمول','email'=>'البريد الإلكتروني','address'=>'العنوان'] as $key=>$label):?><dt class="col-5 mb-2"><?=e($label)?></dt><dd class="col-7 mb-2"><?=e($key==='client_type'?($client[$key]==='company'?'شركة':'فرد'):($client[$key]?:'—'))?></dd><?php endforeach;?>
<dt class="col-5">الحالة</dt><dd class="col-7"><span class="badge <?=$client['is_active']?'bg-green-lt':'bg-secondary-lt'?>"><?=$client['is_active']?'نشط':'غير نشط'?></span></dd></dl></div></div></div>
<div class="col-lg-7"><div class="card"><div class="card-header"><h3 class="card-title">جهات الاتصال</h3><?php if($canEdit):?><div class="card-actions"><a class="btn btn-sm btn-primary" href="/clients/<?=(int)$client['id']?>/contacts/create"><i class="ti ti-plus ms-1"></i>إضافة</a></div><?php endif;?></div><div class="table-responsive"><table class="table table-vcenter card-table"><thead><tr><th>الاسم</th><th>المسمى الوظيفي</th><th>التواصل</th><th>الأساسية</th><?php if($canEdit):?><th>الإجراءات</th><?php endif;?></tr></thead><tbody>
<?php if($contacts===[]):?><tr><td colspan="5" class="text-center text-secondary py-4">لا توجد جهات اتصال.</td></tr><?php endif;?>
<?php foreach($contacts as $contact):?><tr><td><?=e($contact['name'])?></td><td><?=e($contact['job_title']?:'—')?></td><td><?=e($contact['mobile']?:($contact['phone']?:($contact['email']?:'—')))?></td><td><?=$contact['is_primary']?'<span class="badge bg-primary-lt">أساسية</span>':'—'?></td><?php if($canEdit):?><td><div class="btn-list flex-nowrap"><a class="btn btn-sm" href="/clients/<?=(int)$client['id']?>/contacts/<?=(int)$contact['id']?>/edit">تعديل</a><?php if(!$contact['is_primary']):?><form method="post" action="/clients/<?=(int)$client['id']?>/contacts/<?=(int)$contact['id']?>/primary"><input type="hidden" name="_token" value="<?=e($csrfToken)?>"><button class="btn btn-sm" type="submit">تعيين كأساسية</button></form><?php endif;?><form class="js-confirm-form" data-confirm="سيتم حذف جهة الاتصال إذا لم تكن مرتبطة ببيانات أخرى." method="post" action="/clients/<?=(int)$client['id']?>/contacts/<?=(int)$contact['id']?>/remove"><input type="hidden" name="_token" value="<?=e($csrfToken)?>"><button class="btn btn-sm btn-outline-danger" type="submit">حذف</button></form></div></td><?php endif;?></tr><?php endforeach;?></tbody></table></div></div></div></div>
<?php if($canActivate):?><div class="mt-4"><form class="js-confirm-form" data-confirm="هل تريد <?=$client['is_active']?'تعطيل':'تفعيل'?> هذا العميل؟" method="post" action="/clients/<?=(int)$client['id']?>/activate"><input type="hidden" name="_token" value="<?=e($csrfToken)?>"><input type="hidden" name="active" value="<?=$client['is_active']?'0':'1'?>"><button class="btn <?=$client['is_active']?'btn-outline-danger':'btn-success'?>" type="submit"><?=$client['is_active']?'تعطيل العميل':'تفعيل العميل'?></button></form></div><?php endif;?>
