CREATE TABLE project_actual_costs (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    cost_entry_code VARCHAR(30) NOT NULL,
    project_id BIGINT UNSIGNED NOT NULL,
    cost_code_id BIGINT UNSIGNED NOT NULL,
    vendor_id BIGINT UNSIGNED NULL,
    cost_date DATE NOT NULL,
    description VARCHAR(500) NOT NULL,
    reference_number VARCHAR(190) NULL,
    amount DECIMAL(18,2) NOT NULL,
    source_type VARCHAR(50) NOT NULL DEFAULT 'manual',
    source_id BIGINT UNSIGNED NULL,
    source_line_id BIGINT UNSIGNED NULL,
    work_section_code_snapshot VARCHAR(20) NULL,
    work_section_name_snapshot VARCHAR(190) NULL,
    cost_code_snapshot VARCHAR(30) NULL,
    cost_code_name_snapshot VARCHAR(255) NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'draft',
    created_by BIGINT UNSIGNED NOT NULL,
    approved_at DATETIME NULL,
    approved_by BIGINT UNSIGNED NULL,
    cancelled_at DATETIME NULL,
    cancelled_by BIGINT UNSIGNED NULL,
    notes TEXT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_project_actual_costs_code (cost_entry_code),
    UNIQUE KEY uq_project_actual_costs_source (source_type, source_id, source_line_id),
    KEY idx_project_actual_costs_project_status_date (project_id, status, cost_date),
    KEY idx_project_actual_costs_cost_code (cost_code_id, status),
    KEY idx_project_actual_costs_vendor (vendor_id),
    KEY idx_project_actual_costs_source (source_type, source_id),
    CONSTRAINT fk_project_actual_costs_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE RESTRICT,
    CONSTRAINT fk_project_actual_costs_cost_code FOREIGN KEY (cost_code_id) REFERENCES cost_codes(id) ON DELETE RESTRICT,
    CONSTRAINT fk_project_actual_costs_vendor FOREIGN KEY (vendor_id) REFERENCES vendors(id) ON DELETE RESTRICT,
    CONSTRAINT fk_project_actual_costs_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT fk_project_actual_costs_approved_by FOREIGN KEY (approved_by) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT fk_project_actual_costs_cancelled_by FOREIGN KEY (cancelled_by) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT chk_project_actual_costs_amount CHECK (amount > 0),
    CONSTRAINT chk_project_actual_costs_status CHECK (status IN ('draft','approved','cancelled')),
    CONSTRAINT chk_project_actual_costs_source CHECK ((source_type = 'manual' AND source_id IS NULL AND source_line_id IS NULL) OR (source_type <> 'manual' AND source_id IS NOT NULL AND source_line_id IS NOT NULL)),
    CONSTRAINT chk_project_actual_costs_audit CHECK (
      (status = 'draft' AND approved_at IS NULL AND approved_by IS NULL AND cancelled_at IS NULL AND cancelled_by IS NULL AND work_section_code_snapshot IS NULL AND work_section_name_snapshot IS NULL AND cost_code_snapshot IS NULL AND cost_code_name_snapshot IS NULL)
      OR (status = 'approved' AND approved_at IS NOT NULL AND approved_by IS NOT NULL AND cancelled_at IS NULL AND cancelled_by IS NULL AND work_section_code_snapshot IS NOT NULL AND work_section_name_snapshot IS NOT NULL AND cost_code_snapshot IS NOT NULL AND cost_code_name_snapshot IS NOT NULL)
      OR (status = 'cancelled' AND cancelled_at IS NOT NULL AND cancelled_by IS NOT NULL AND approved_at IS NULL AND approved_by IS NULL)
    )
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
