<?php
$draft = $payment['status'] === 'draft';
$methods = ['cash'=>'نقدي','bank_transfer'=>'تحويل بنكي','cheque'=>'شيك','instapay'=>'إنستاباي','other'=>'أخرى'];
$method = $payment['payment_channel'] === 'bank' ? ($payment['bank_payment_method'] ?? 'other') : 'cash';
$accountName = $payment['status'] === 'posted' ? trim(($payment['payment_account_code_snapshot'] ?? '').' - '.($payment['payment_account_name_snapshot'] ?? ''), ' -') : trim(($payment['current_payment_account_code'] ?? '').' - '.($payment['current_payment_account_name'] ?? ''), ' -');
?>
<div class="page-header mb-4"><div class="row"><div class="col"><h2 class="page-title"><?=e($payment['payment_code'])?></h2></div><div class="col-auto d-flex gap-2"><a class="btn" href="/subcontracts/<?=(int)$payment['subcontract_id']?>/payments">العودة</a><?php if($draft&&$canEdit):?><a class="btn" href="/subcontract-payments/<?=(int)$payment['id']?>/edit">تعديل</a><?php endif;?></div></div></div>
<div class="card mb-4"><div class="card-body"><div class="row g-3">
<?php foreach(['payment_date'=>'تاريخ الدفع','amount'=>'المبلغ','reference_number'=>'المرجع','status'=>'الحالة','created_by_name'=>'أنشأ بواسطة','posted_by_name'=>'رحّل بواسطة'] as$key=>$label):?><div class="col-md-3"><div class="text-secondary"><?=$label?></div><strong><?=e($payment[$key]??'—')?></strong></div><?php endforeach;?>
<div class="col-md-3"><div class="text-secondary">طريقة الدفع</div><strong><?=e($methods[$method]??$method)?></strong></div><div class="col-md-3"><div class="text-secondary">حساب الدفع</div><strong><?=e($accountName?:'—')?></strong></div>
<?php if($method==='cheque'):?><?php foreach(['cheque_number'=>'رقم الشيك','cheque_date'=>'تاريخ الشيك','cheque_due_date'=>'تاريخ الاستحقاق']as$key=>$label):?><div class="col-md-3"><div class="text-secondary"><?=$label?></div><strong><?=e($payment[$key]??'—')?></strong></div><?php endforeach;?><?php endif;?>
</div></div></div>
<?php if($payment['status']==='posted'):?><div class="row g-3 mb-4"><?php foreach(['approved_progress_percentage_snapshot'=>'الإنجاز المعتمد %','approved_earned_value_snapshot'=>'القيمة المكتسبة','previous_payments_snapshot'=>'المدفوع سابقًا','available_payment_snapshot'=>'المتاح قبل الدفعة']as$key=>$label):?><div class="col-md-3"><div class="card card-sm"><div class="card-body"><div class="text-secondary"><?=$label?></div><div class="h3"><?=e($payment[$key])?></div></div></div></div><?php endforeach;?></div><?php endif;?>
<?php if($draft):?><div class="d-flex gap-2"><?php if($canPost):?><form method="post" action="/subcontract-payments/<?=(int)$payment['id']?>/post" class="js-confirm-form" data-confirm-text="سيتم تجميد القيم وإنشاء القيد المحاسبي وترحيل الدفعة نهائيًا."><input type="hidden" name="_token" value="<?=e($csrfToken)?>"><button class="btn btn-success">ترحيل الدفعة</button></form><?php endif;?><?php if($canCancel):?><form method="post" action="/subcontract-payments/<?=(int)$payment['id']?>/cancel" class="js-confirm-form"><input type="hidden" name="_token" value="<?=e($csrfToken)?>"><button class="btn btn-danger">إلغاء المسودة</button></form><?php endif;?></div><?php endif;?>
