<?php
declare(strict_types=1);
namespace App\Modules\PurchaseOrders\Services;
use App\Core\Auth\Auth;
use App\Core\Database\Database;
use App\Core\Exceptions\BusinessRuleException;
use App\Modules\PurchaseOrders\DTOs\PurchaseOrderData;
use App\Modules\PurchaseOrders\DTOs\PurchaseOrderTableQuery;
use App\Modules\PurchaseOrders\Repositories\PurchaseOrderRepository;
use App\Shared\Numbering\NumberGeneratorService;
final class PurchaseOrderService
{
    private const PROJECT_STATUSES=['planning','active','on_hold','completed'];
    public function __construct(private readonly PurchaseOrderRepository $orders,private readonly NumberGeneratorService $numbers,private readonly Database $database,private readonly Auth $auth) {}
    public function find(int $id):array{return $this->orders->find($id)??throw new BusinessRuleException('أمر الشراء غير موجود.');}
    public function details(int $id):array{return ['order'=>$this->find($id),'lines'=>$this->orders->lines($id),'displayTotal'=>$this->orders->total($id)];}
    public function save(PurchaseOrderData $data,?int $id=null):int{return $this->database->transaction(function()use($data,$id){$order=$id===null?null:$this->orders->find($id,true);if($id!==null&&$order===null)throw new BusinessRuleException('أمر الشراء غير موجود.');if($order!==null&&$order['status']!=='draft')throw new BusinessRuleException('يمكن تعديل مسودة أمر الشراء فقط.');if($order!==null&&$this->year((string)$order['po_code'])!==substr($data->poDate,0,4))throw new BusinessRuleException('لا يمكن تغيير سنة تاريخ أمر الشراء. ألغِ المسودة وأنشئ أمرًا جديدًا.');$this->validateMasters($data,true);if($id===null)$id=$this->orders->create($this->numbers->nextPurchaseOrderCode((int)substr($data->poDate,0,4)),$data,$this->user());else $this->orders->update($id,$data);$this->orders->syncLines($id,$data->lines);$this->assertTotalFits($id);return $id;});}
    public function approve(int $id):void{$this->database->transaction(function()use($id){$order=$this->orders->find($id,true)??throw new BusinessRuleException('أمر الشراء غير موجود.');if($order['status']!=='draft')throw new BusinessRuleException('يمكن اعتماد مسودة أمر الشراء فقط.');$vendor=$this->orders->vendor((int)$order['vendor_id'],true)??throw new BusinessRuleException('المورد غير موجود.');$project=$this->orders->project((int)$order['project_id'],true)??throw new BusinessRuleException('المشروع غير موجود.');if(!(bool)$vendor['is_active']||!in_array($vendor['vendor_type'],['supplier','both'],true))throw new BusinessRuleException('المورد غير نشط أو غير مصنف كمورد.');if(!in_array($project['status'],self::PROJECT_STATUSES,true))throw new BusinessRuleException('حالة المشروع لا تسمح باعتماد أمر الشراء.');$lines=$this->orders->lines($id,true);if($lines===[])throw new BusinessRuleException('لا يمكن اعتماد أمر شراء بلا بنود.');$ids=array_values(array_unique(array_map('intval',array_column($lines,'cost_code_id'))));sort($ids);$masters=$this->orders->costCodes($ids,true);$byId=array_column($masters,null,'id');if(count($byId)!==count($ids))throw new BusinessRuleException('أحد أكواد التكلفة غير موجود.');$summary=$this->assertTotalFits($id);foreach($lines as $line){$master=$byId[$line['cost_code_id']]??null;if($master===null||!(bool)$master['cost_code_active']||!(bool)$master['section_active'])throw new BusinessRuleException('أحد أكواد التكلفة أو أقسام الأعمال غير نشط.');$this->orders->freezeLine((int)$line['id'],$master);}if($summary['total']==='0.00')throw new BusinessRuleException('إجمالي أمر الشراء يجب أن يكون أكبر من صفر.');$this->orders->approve($id,$summary['total'],$vendor,$project,$this->user());$verified=$this->orders->find($id,true);if(($verified['status']??null)!=='approved')throw new \RuntimeException('Purchase order approval failed.');});}
    public function cancel(int $id):void{$this->database->transaction(function()use($id){$order=$this->orders->find($id,true)??throw new BusinessRuleException('أمر الشراء غير موجود.');if($order['status']!=='draft')throw new BusinessRuleException('يمكن إلغاء مسودة أمر الشراء فقط.');$this->orders->cancel($id,$this->user());$verified=$this->orders->find($id,true);if(($verified['status']??null)!=='cancelled')throw new \RuntimeException('Purchase order cancellation failed.');});}
    private function validateMasters(PurchaseOrderData $data,bool $lock):void{$vendor=$this->orders->vendor($data->vendorId,$lock);if($vendor===null||!(bool)$vendor['is_active']||!in_array($vendor['vendor_type'],['supplier','both'],true))throw new BusinessRuleException('اختر موردًا نشطًا ومصنفًا كمورد.');$project=$this->orders->project($data->projectId,$lock);if($project===null||!in_array($project['status'],self::PROJECT_STATUSES,true))throw new BusinessRuleException('اختر مشروعًا صالحًا غير ملغي.');$ids=array_values(array_unique(array_map('intval',array_column($data->lines,'cost_code_id'))));sort($ids);$codes=$this->orders->costCodes($ids,$lock);if(count($codes)!==count($ids))throw new BusinessRuleException('أحد أكواد التكلفة غير موجود.');foreach($codes as $code)if(!(bool)$code['cost_code_active']||!(bool)$code['section_active'])throw new BusinessRuleException('اختر أكواد تكلفة نشطة ضمن أقسام نشطة.');}
    /** @return array{total:string,fits:bool} */
    private function assertTotalFits(int $id):array{$summary=$this->orders->totalSummary($id);if(!$summary['fits'])throw new BusinessRuleException('إجمالي أمر الشراء يتجاوز الحد الأقصى المسموح DECIMAL(18,2).');return $summary;}
    private function year(string $code):string{return preg_match('/^PO-(\d{4})-/',$code,$matches)?$matches[1]:'';}
    private function user():int{return $this->auth->id()??throw new BusinessRuleException('تعذر تحديد المستخدم الحالي.');}
    public function references():array{return $this->orders->references();}
    public function dataTable(PurchaseOrderTableQuery $query):array{$result=$this->orders->dataTable($query);return ['draw'=>$query->draw,'recordsTotal'=>$result['recordsTotal'],'recordsFiltered'=>$result['recordsFiltered'],'data'=>$result['rows']];}
}
