<?php
declare(strict_types=1);
namespace App\Modules\EmployeeCustodies\Repositories;
use App\Core\Database\Database;
use App\Modules\EmployeeCustodies\DTOs\CustodyData;
use App\Modules\EmployeeCustodies\DTOs\SettlementData;
final class CustodyRepository
{
 public function __construct(private readonly Database$db){}
 public function all():array{return$this->rows('SELECT c.*,e.name employee_name,p.name project_name,COALESCE(s.settled,0.00) settled_amount,CAST(c.amount-COALESCE(s.settled,0.00) AS DECIMAL(18,2)) remaining_amount FROM employee_custodies c JOIN employees e ON e.id=c.employee_id LEFT JOIN projects p ON p.id=c.project_id LEFT JOIN(SELECT custody_id,SUM(amount) settled FROM employee_custody_settlements GROUP BY custody_id)s ON s.custody_id=c.id ORDER BY c.issue_date DESC,c.id DESC');}
 public function find(int$id,bool$lock=false):?array{return$this->one('SELECT c.*,e.employee_code,e.name employee_name,e.is_active employee_active,p.project_code,p.name project_name,a.account_code funding_account_code,a.name_ar funding_account_name,COALESCE(s.settled,0.00) settled_amount,CAST(c.amount-COALESCE(s.settled,0.00) AS DECIMAL(18,2)) remaining_amount FROM employee_custodies c JOIN employees e ON e.id=c.employee_id LEFT JOIN projects p ON p.id=c.project_id JOIN accounts a ON a.id=c.funding_account_id LEFT JOIN(SELECT custody_id,SUM(amount) settled FROM employee_custody_settlements GROUP BY custody_id)s ON s.custody_id=c.id WHERE c.id=?'.($lock?' FOR UPDATE':''),[$id]);}
 public function settlements(int$id):array{return$this->rows('SELECT s.*,c.cost_code,a.account_code return_account_code,j.journal_no,x.cost_entry_code FROM employee_custody_settlements s LEFT JOIN cost_codes c ON c.id=s.cost_code_id LEFT JOIN accounts a ON a.id=s.return_account_id LEFT JOIN journal_entries j ON j.id=s.journal_entry_id LEFT JOIN project_actual_costs x ON x.id=s.project_actual_cost_id WHERE s.custody_id=? ORDER BY s.sort_order,s.id',[$id]);}
 public function references():array{return['employees'=>$this->rows('SELECT id,employee_code,name FROM employees WHERE is_active=1 ORDER BY employee_code'),'projects'=>$this->rows('SELECT id,project_code,name FROM projects WHERE status<>\'cancelled\' ORDER BY project_code'),'funding_accounts'=>$this->rows('SELECT id,account_code,name_ar FROM accounts WHERE account_code IN(\'111001\',\'111010\') AND is_active=1 AND is_postable=1 ORDER BY account_code'),'cost_codes'=>$this->rows('SELECT id,cost_code,name FROM cost_codes WHERE is_active=1 ORDER BY cost_code')];}
 public function create(string$number,CustodyData$d,int$user):int{$this->db->execute('INSERT INTO employee_custodies(custody_no,employee_id,project_id,issue_date,amount,funding_type,funding_account_id,purpose,created_by) VALUES(?,?,?,?,?,?,?,?,?)',[$number,$d->employeeId,$d->projectId,$d->issueDate,$d->amount,$d->fundingType,$d->fundingAccountId,$d->purpose,$user]);return(int)$this->db->connection()->insert_id;}
 public function update(int$id,CustodyData$d):void{$this->db->execute('UPDATE employee_custodies SET employee_id=?,project_id=?,issue_date=?,amount=?,funding_type=?,funding_account_id=?,purpose=? WHERE id=? AND status=\'draft\'',[$d->employeeId,$d->projectId,$d->issueDate,$d->amount,$d->fundingType,$d->fundingAccountId,$d->purpose,$id]);}
 public function issue(int$id,int$journal,int$user,array$s):void{$this->db->execute('UPDATE employee_custodies SET employee_code_snapshot=?,employee_name_snapshot=?,project_code_snapshot=?,project_name_snapshot=?,funding_account_code_snapshot=?,funding_account_name_snapshot=?,issue_journal_entry_id=?,status=\'issued\',issued_by=?,issued_at=NOW() WHERE id=? AND status=\'draft\'',[$s['employee_code'],$s['employee_name'],$s['project_code'],$s['project_name'],$s['account_code'],$s['account_name'],$journal,$user,$id]);}
 public function cancel(int$id,int$user):void{$this->db->execute('UPDATE employee_custodies SET status=\'cancelled\',cancelled_by=?,cancelled_at=NOW() WHERE id=? AND status=\'draft\'',[$user,$id]);}
 public function employee(int$id,bool$lock=false):?array{return$this->one('SELECT * FROM employees WHERE id=?'.($lock?' FOR UPDATE':''),[$id]);}
 public function project(int$id,bool$lock=false):?array{return$this->one('SELECT * FROM projects WHERE id=?'.($lock?' FOR UPDATE':''),[$id]);}
 public function account(int$id,bool$lock=false):?array{return$this->one('SELECT * FROM accounts WHERE id=?'.($lock?' FOR UPDATE':''),[$id]);}
 public function costCode(int$id,bool$lock=false):?array{return$this->one('SELECT c.*,w.section_code,w.name section_name,w.is_active section_active FROM cost_codes c JOIN work_sections w ON w.id=c.work_section_id WHERE c.id=?'.($lock?' FOR UPDATE':''),[$id]);}
 public function settlementCapacity(int$custody,string$amount):array{return$this->one('SELECT CAST(c.amount-COALESCE(SUM(s.amount),0.00) AS DECIMAL(18,2)) remaining,CASE WHEN CAST(? AS DECIMAL(18,2))<=c.amount-COALESCE(SUM(s.amount),0.00) THEN 1 ELSE 0 END fits,COALESCE(MAX(s.sort_order),0)+1 next_order FROM employee_custodies c LEFT JOIN employee_custody_settlements s ON s.custody_id=c.id WHERE c.id=? GROUP BY c.id,c.amount',[$amount,$custody])??[];}
 public function createSettlement(int$custody,SettlementData$d,int$order,int$user):int{$this->db->execute('INSERT INTO employee_custody_settlements(custody_id,settlement_type,settlement_date,description,cost_code_id,amount,project_id,return_account_id,reference,sort_order,created_by) VALUES(?,?,?,?,?,?,?,?,?,?,?)',[$custody,$d->type,$d->date,$d->description,$d->costCodeId,$d->amount,$d->projectId,$d->returnAccountId,$d->reference,$order,$user]);return(int)$this->db->connection()->insert_id;}
 public function linkSettlement(int$id,int$journal,?int$cost):void{$this->db->execute('UPDATE employee_custody_settlements SET journal_entry_id=?,project_actual_cost_id=? WHERE id=? AND journal_entry_id IS NULL',[$journal,$cost,$id]);}
 public function refreshStatus(int$id):void{$this->db->execute('UPDATE employee_custodies c SET status=CASE WHEN (SELECT COALESCE(SUM(s.amount),0.00) FROM employee_custody_settlements s WHERE s.custody_id=c.id)=c.amount THEN \'settled\' ELSE \'partially_settled\' END WHERE c.id=? AND status IN(\'issued\',\'partially_settled\')',[$id]);}
 public function sourceCostExists(int$settlement):bool{return$this->one('SELECT id FROM project_actual_costs WHERE source_type=\'employee_custody_settlement\' AND source_id=? AND source_line_id=1 LIMIT 1',[$settlement])!==null;}
 public function createActualCost(string$code,int$settlement,array$custody,SettlementData$d,array$master,int$user):int{$this->db->execute('INSERT INTO project_actual_costs(cost_entry_code,project_id,cost_code_id,cost_date,description,reference_number,amount,source_type,source_id,source_line_id,work_section_code_snapshot,work_section_name_snapshot,cost_code_snapshot,cost_code_name_snapshot,status,created_by,approved_at,approved_by,notes) VALUES(?,?,?,?,?,?,?,\'employee_custody_settlement\',?,1,?,?,?,?,\'approved\',?,NOW(),?,?)',[$code,$d->projectId,$d->costCodeId,$d->date,$d->description,$d->reference,$d->amount,$settlement,$master['section_code'],$master['section_name'],$master['cost_code'],$master['name'],$user,$user,'تسوية مصروف من العهدة '.$custody['custody_no']]);return(int)$this->db->connection()->insert_id;}
 private function one(string$sql,array$params=[]):?array{$result=$this->db->execute($sql,$params);$row=$result instanceof \mysqli_result?$result->fetch_assoc():null;return is_array($row)?$row:null;}
 private function rows(string$sql,array$params=[]):array{$result=$this->db->execute($sql,$params);return$result instanceof \mysqli_result?$result->fetch_all(MYSQLI_ASSOC):[];}
}
