<?php
declare(strict_types=1);
namespace App\Modules\ContractVariations\Controllers;
use App\Core\Exceptions\BusinessRuleException;use App\Core\Exceptions\ValidationException;use App\Core\Http\Csrf;use App\Core\Http\Request;use App\Core\Http\Response;use App\Core\Http\Session;use App\Core\View\View;use App\Modules\AccessControl\Services\AuthorizationService;use App\Modules\ContractVariations\Services\ContractVariationService;use App\Modules\ContractVariations\Validators\ContractVariationValidator;
final class ContractVariationController
{
 public function __construct(private readonly View $view,private readonly Csrf $csrf,private readonly Session $session,private readonly AuthorizationService $auth,private readonly ContractVariationService $service,private readonly ContractVariationValidator $validator){}
 public function index(Request $r):Response{$id=(int)$r->route('contract_id');$contract=$this->service->contract($id);return Response::html($this->view->render('modules/contract-variations/index',['title'=>'الملحقات والأعمال الإضافية','contract'=>$contract,'summary'=>$this->service->summary($id),'canCreate'=>$this->auth->can('contract_variations.create')&&in_array($contract['status'],['active','suspended'],true),'canEdit'=>$this->auth->can('contract_variations.edit')]));}
 public function create(Request $r):Response{return $this->form(null,(int)$r->route('contract_id'));}public function edit(Request $r):Response{$v=$this->service->find((int)$r->route('id'));return $this->form((int)$v['id'],(int)$v['client_contract_id']);}public function show(Request $r):Response{$v=$this->service->find((int)$r->route('id'));return Response::html($this->view->render('modules/contract-variations/show',['title'=>'تفاصيل ملحق العقد','variation'=>$v,'canEdit'=>$this->auth->can('contract_variations.edit'),'canApprove'=>$this->auth->can('contract_variations.approve'),'canCancel'=>$this->auth->can('contract_variations.cancel')]));}public function store(Request $r):Response{return $this->save($r,null,(int)$r->route('contract_id'));}public function update(Request $r):Response{$v=$this->service->find((int)$r->route('id'));return $this->save($r,(int)$v['id'],(int)$v['client_contract_id']);}
 public function approve(Request $r):Response{return $this->action($r,'approve');}public function cancel(Request $r):Response{return $this->action($r,'cancel');}
 private function form(?int $id,int $contractId):Response{$contract=$this->service->contract($contractId);$variation=$id===null?null:$this->service->find($id);if($id===null&&!in_array($contract['status'],['active','suspended'],true))throw new BusinessRuleException('لا يمكن إنشاء ملحق لهذا العقد.');return Response::html($this->view->render('modules/contract-variations/form',['title'=>$id===null?'إضافة ملحق عقد':'تعديل ملحق العقد','contract'=>$contract,'variation'=>$variation]));}
 private function save(Request $r,?int $id,int $contractId):Response{if(!$this->csrf->isValid($r->input('_token')))return Response::html('انتهت صلاحية الطلب.',419);$input=$r->all();$input['client_contract_id']=$contractId;try{$id=$this->service->save($this->validator->validate($input),$id);$this->flash('success','تم الحفظ','تم حفظ ملحق العقد.');return Response::redirect("/contract-variations/{$id}");}catch(ValidationException|BusinessRuleException $e){$message=$e instanceof ValidationException?(string)reset($e->errors[array_key_first($e->errors)]):$e->getMessage();$this->flash('error','تعذر الحفظ',$message);return Response::redirect($id===null?"/contracts/{$contractId}/variations/create":"/contract-variations/{$id}/edit");}}
 private function action(Request $r,string $action):Response{if(!$this->csrf->isValid($r->input('_token')))return Response::html('انتهت صلاحية الطلب.',419);$id=(int)$r->route('id');try{$action==='approve'?$this->service->approve($id):$this->service->cancel($id);$this->flash('success','تم التحديث',$action==='approve'?'تم اعتماد الملحق.':'تم إلغاء الملحق.');}catch(BusinessRuleException $e){$this->flash('error','تعذر التحديث',$e->getMessage());}return Response::redirect("/contract-variations/{$id}");}
 private function flash(string $type,string $title,string $text):void{$this->session->flash('alert',compact('type','title','text'));}
}
