<?php
declare(strict_types=1);
namespace App\Modules\ClientContracts\Validators;
use App\Core\Exceptions\ValidationException;use App\Core\Validation\Validator;use App\Modules\ClientContracts\DTOs\ClientContractData;
final class ClientContractValidator
{
 public const METHODS=['cost_plus','boq','lump_sum'];public function __construct(private readonly Validator $validator){}
 public function validate(array $i):ClientContractData
 {
  if(!$this->validator->validate($i,['project_id'=>'required','client_id'=>'required','pricing_method'=>'required|string|max:20','contract_date'=>'required','contract_number'=>'string|max:100','title'=>'required|string|max:190','description'=>'string|max:5000','terms'=>'string|max:10000','notes'=>'string|max:5000']))throw new ValidationException($this->validator->errors());$e=[];
  $project=$this->id($i['project_id']??null);$client=$this->id($i['client_id']??null);$contact=$this->optionalId($i['client_contact_id']??null);if($project===null)$e['project_id'][]='المشروع غير صالح.';if($client===null)$e['client_id'][]='العميل غير صالح.';if(trim((string)($i['client_contact_id']??''))!==''&&$contact===null)$e['client_contact_id'][]='جهة الاتصال غير صالحة.';
  $method=trim((string)($i['pricing_method']??''));if(!in_array($method,self::METHODS,true))$e['pricing_method'][]='طريقة التسعير غير صالحة.';$dates=[];foreach(['contract_date','start_date','expected_end_date'] as $f){$dates[$f]=$this->date($i[$f]??null);if(($f==='contract_date'||trim((string)($i[$f]??''))!=='')&&$dates[$f]===null)$e[$f][]='التاريخ غير صالح.';}if($dates['start_date']&&$dates['expected_end_date']&&$dates['expected_end_date']<$dates['start_date'])$e['expected_end_date'][]='تاريخ الانتهاء لا يمكن أن يسبق تاريخ البدء.';
  $value=$this->decimal($i['contract_value']??null,true);$markup=$this->decimal($i['markup_percentage']??null,false);$markupEntered=trim((string)($i['markup_percentage']??''))!=='';if(trim((string)($i['contract_value']??''))!==''&&$value===null)$e['contract_value'][]='قيمة العقد يجب أن تكون رقمًا لا يقل عن صفر.';if($markupEntered&&$markup===null)$e['markup_percentage'][]='نسبة الزيادة يجب أن تكون رقمًا أكبر من صفر.';if($method==='cost_plus'&&$markup===null)$e['markup_percentage'][]='نسبة الزيادة مطلوبة لعقد التكلفة مضافًا إليها.';if($method==='lump_sum'&&$value===null)$e['contract_value'][]='قيمة العقد مطلوبة للعقد المقطوع.';if(in_array($method,['boq','lump_sum'],true)&&$markupEntered)$e['markup_percentage'][]='نسبة الزيادة غير مسموحة لطريقة التسعير المحددة.';if(in_array($method,['boq','lump_sum'],true))$markup=null;
  if($e!==[])throw new ValidationException($e);return new ClientContractData((int)$project,(int)$client,$contact,$method,(string)$dates['contract_date'],$dates['start_date'],$dates['expected_end_date'],$value,$markup,$this->nullable($i['contract_number']??null),trim((string)$i['title']),$this->nullable($i['description']??null),$this->nullable($i['terms']??null),$this->nullable($i['notes']??null));
 }
 private function id(mixed $v):?int{$x=filter_var($v,FILTER_VALIDATE_INT,['options'=>['min_range'=>1]]);return $x===false?null:$x;}private function optionalId(mixed $v):?int{return trim((string)$v)===''?null:$this->id($v);}private function nullable(mixed $v):?string{$v=trim((string)$v);return $v===''?null:$v;}private function date(mixed $v):?string{$v=trim((string)$v);if($v==='')return null;$d=\DateTimeImmutable::createFromFormat('!Y-m-d',$v);return $d&&$d->format('Y-m-d')===$v?$v:null;}private function decimal(mixed $v,bool $zero):?string{$v=trim((string)$v);if($v===''||!preg_match('/^\d+(?:\.\d+)?$/',$v))return null;$n=(float)$v;if($zero?$n<0:$n<=0)return null;return number_format($n,$zero?2:4,'.','');}
}
