<?php
declare(strict_types=1);
namespace App\Modules\ContractVariations\Services;
use App\Core\Auth\Auth;use App\Core\Database\Database;use App\Core\Exceptions\BusinessRuleException;use App\Modules\ContractVariations\DTOs\ContractVariationData;use App\Modules\ContractVariations\DTOs\ContractVariationTableQuery;use App\Modules\ContractVariations\Repositories\ContractVariationRepository;use App\Shared\Numbering\NumberGeneratorService;
final class ContractVariationService
{
 public function __construct(private readonly ContractVariationRepository $variations,private readonly NumberGeneratorService $numbers,private readonly Database $db,private readonly Auth $auth){}
 public function contract(int $id):array{return $this->variations->contract($id)??throw new BusinessRuleException('عقد العميل غير موجود.');}public function find(int $id):array{return $this->variations->find($id)??throw new BusinessRuleException('ملحق العقد غير موجود.');}
 public function save(ContractVariationData $d,?int $id=null):int{$contract=$this->contract($d->clientContractId);$existing=$id===null?null:$this->find($id);if($id===null&&!in_array($contract['status'],['active','suspended'],true))throw new BusinessRuleException('لا يمكن إنشاء ملحق إلا لعقد نشط أو معلق.');if($existing!==null&&(int)$existing['client_contract_id']!==$d->clientContractId)throw new BusinessRuleException('لا يمكن تغيير العقد الأب للملحق.');if($d->markupPercentage!==null&&$contract['pricing_method']!=='cost_plus')throw new BusinessRuleException('نسبة الزيادة مسموحة فقط لعقود التكلفة مضافًا إليها.');if($d->variationNumber!==null&&$this->variations->numberExists($d->clientContractId,$d->variationNumber,$id))throw new BusinessRuleException('رقم الملحق مستخدم بالفعل لهذا العقد.');return $this->db->transaction(function()use($d,$id,$existing){if($id===null)return $this->variations->create($this->numbers->nextContractVariationCode((int)substr($d->variationDate,0,4)),$d);if($existing['status']==='draft')$this->variations->updateDraft($id,$d);else{$this->assertCommercialUnchanged($existing,$d);$this->variations->updateNotes($id,$d->notes);}return $id;});}
 public function approve(int $id):void{$v=$this->find($id);if($v['status']!=='draft')throw new BusinessRuleException('يمكن اعتماد الملحق من حالة المسودة فقط.');$contract=$this->contract((int)$v['client_contract_id']);if(!in_array($contract['status'],['active','suspended'],true))throw new BusinessRuleException('لا يمكن اعتماد ملحق لعقد غير نشط أو غير معلق.');$this->variations->approve($id,$this->userId());}
 public function cancel(int $id):void{$probe=$this->find($id);$this->db->transaction(function()use($id,$probe){$this->variations->lockContract((int)$probe['client_contract_id'])??throw new BusinessRuleException('عقد العميل غير موجود.');$v=$this->variations->lockVariation($id)??throw new BusinessRuleException('ملحق العقد غير موجود.');if(!in_array($v['status'],['draft','approved'],true))throw new BusinessRuleException('لا يمكن إلغاء هذا الملحق.');if($this->variations->hasCommittedStatementAllocation($id))throw new BusinessRuleException('لا يمكن إلغاء هذا الملحق لأنه تمت فوترته في مستخلص عميل معتمد. يلزم إجراء تصحيح مالي مستقل.');$this->variations->cancel($id,$this->userId());});}
 public function summary(int $contractId):array{$this->contract($contractId);return $this->variations->summary($contractId);}public function dataTable(ContractVariationTableQuery $q):array{$this->contract($q->contractId);$r=$this->variations->dataTable($q);return ['draw'=>$q->draw,'recordsTotal'=>$r['recordsTotal'],'recordsFiltered'=>$r['recordsFiltered'],'data'=>$r['rows']];}
 private function userId():int{return $this->auth->id()??throw new BusinessRuleException('تعذر تحديد المستخدم الحالي.');}private function assertCommercialUnchanged(array $v,ContractVariationData $d):void{foreach(['variation_number'=>$d->variationNumber,'variation_type'=>$d->variationType,'title'=>$d->title,'description'=>$d->description,'variation_date'=>$d->variationDate,'effective_date'=>$d->effectiveDate,'amount'=>$d->amount,'amount_effect'=>$d->amountEffect,'markup_percentage'=>$d->markupPercentage] as $field=>$value){$old=$v[$field]===null?null:(string)$v[$field];if($old!==$value)throw new BusinessRuleException('بعد اعتماد أو إلغاء الملحق يمكن تعديل الملاحظات الإدارية فقط.');}}
}
