<?php
$editing = is_array($subcontract);
$value = static fn(string $key): string => (string) ($subcontract[$key] ?? '');
$locked = $editing && $value('status') !== 'draft';
$eligibleVendors = array_values(array_filter($vendors, static fn(array $vendor): bool => (bool) $vendor['is_active']));
$missingProjects = !$editing && $projects === [];
$missingVendors = !$editing && $eligibleVendors === [];
$cannotCreate = $missingProjects || ($missingVendors && !$canCreateVendor);
?>
<h2 class="page-title mb-4"><?= e($title) ?></h2>
<?php if ($cannotCreate): ?>
<div class="alert alert-warning"><h4 class="alert-title">لا يمكن إنشاء عقد مقاول باطن بعد</h4><ul class="mb-0"><?php if ($missingProjects): ?><li>أنشئ مشروعًا أولًا.</li><?php endif; ?><?php if ($missingVendors): ?><li>أنشئ موردًا نشطًا من النوع «مقاول باطن» أو «كلاهما» أولًا.</li><?php endif; ?></ul></div>
<?php endif; ?>
<form class="card" method="post" action="<?= $editing ? '/subcontracts/' . (int) $subcontract['id'] . '/edit' : '/subcontracts' ?>">
<div class="card-body"><input type="hidden" name="_token" value="<?= e($csrfToken) ?>"><div class="row g-3">
<div class="col-md-6"><label class="form-label required">المشروع</label><select class="form-select js-tom-select" name="project_id" required <?= $locked ? 'disabled' : '' ?>><option value="">اختر المشروع</option><?php foreach ($projects as $project): ?><option value="<?= (int) $project['id'] ?>" <?= $value('project_id') === (string) $project['id'] ? 'selected' : '' ?>><?= e($project['project_code'] . ' - ' . $project['name']) ?></option><?php endforeach; ?></select><?php if ($locked): ?><input type="hidden" name="project_id" value="<?= e($value('project_id')) ?>"><?php endif; ?></div>
<div class="col-md-6"><label class="form-label required">مجال العمل</label><select id="subcontract-work-section-id" class="form-select js-tom-select" name="work_section_id" required <?= $locked ? 'disabled' : '' ?>><option value="">اختر مجال العمل</option><?php foreach ($work_sections as $section): ?><option value="<?= (int)$section['id'] ?>" <?= $value('work_section_id') === (string)$section['id'] ? 'selected' : '' ?>><?= e($section['section_code'].' - '.$section['name']) ?></option><?php endforeach; ?></select><?php if($locked):?><input type="hidden" name="work_section_id" value="<?=e($value('work_section_id'))?>"><?php endif;?></div>
<div class="col-md-6"><label class="form-label required">مقاول الباطن</label><div class="d-flex align-items-start gap-2"><div class="flex-fill min-w-0"><select id="subcontract-vendor-id" class="form-select js-tom-select" name="vendor_id" required <?= $locked ? 'disabled' : '' ?>><option value="">اختر مقاول الباطن</option><?php foreach ($vendors as $vendor): if (!$vendor['is_active'] && $value('vendor_id') !== (string) $vendor['id']) continue; ?><option value="<?= (int) $vendor['id'] ?>" <?= $value('vendor_id') === (string) $vendor['id'] ? 'selected' : '' ?>><?= e($vendor['vendor_code'] . ' - ' . $vendor['name']) ?></option><?php endforeach; ?></select></div><?php if($canCreateVendor):?><a class="btn btn-link btn-sm p-0 text-nowrap" href="#create-vendor-modal" role="button" data-bs-toggle="modal" data-bs-target="#create-vendor-modal"><i class="ti ti-user-plus ms-1"></i>إضافة مقاول جديد</a><?php endif;?></div><?php if ($locked): ?><input type="hidden" name="vendor_id" value="<?= e($value('vendor_id')) ?>"><?php endif; ?></div>
<?php foreach (['subcontract_number'=>'رقم العقد التجاري','title'=>'اسم العقد / نطاق الأعمال','contract_date'=>'تاريخ العقد','start_date'=>'تاريخ البدء','expected_end_date'=>'الانتهاء المتوقع','contract_value'=>'قيمة العقد'] as $key=>$label): $fieldValue=$value($key); if(!$editing&&$fieldValue===''&&in_array($key,['contract_date','start_date'],true))$fieldValue=date('Y-m-d'); ?><div class="col-md-6"><label class="form-label <?= in_array($key,['title','contract_date'],true)?'required':'' ?>"><?= $label ?></label><input class="form-control" name="<?= $key ?>" placeholder="<?= $key === 'title' ? 'مثال: أعمال الكهرباء والسباكة' : '' ?>" <?= $key === 'contract_date' || str_contains($key, 'date') ? 'type="date"' : '' ?> value="<?= e($fieldValue) ?>" <?= in_array($key,['title','contract_date'],true)?'required':'' ?> <?= $locked && in_array($key,['subcontract_number','title','contract_date','contract_value'],true) ? 'readonly' : '' ?>></div><?php endforeach; ?>
<input type="hidden" name="pricing_method" value="boq">
<div class="col-12"><label class="form-label">الوصف</label><textarea class="form-control" name="description" <?= $locked ? 'readonly' : '' ?>><?= e($value('description')) ?></textarea></div><div class="col-12"><label class="form-label">ملاحظات</label><textarea class="form-control" name="notes"><?= e($value('notes')) ?></textarea></div>
</div></div><div class="card-footer"><button id="save-subcontract" class="btn btn-primary" <?= $cannotCreate ? 'disabled' : '' ?>>حفظ</button></div></form>
<?php if($canCreateVendor):?><div class="modal modal-blur fade" id="create-vendor-modal" tabindex="-1" aria-hidden="true" data-vendor-target="#subcontract-vendor-id"><div class="modal-dialog modal-xl modal-dialog-centered modal-dialog-scrollable"><div class="modal-content"><form id="create-vendor-form" class="js-vendor-form" method="post" action="/vendors"><div class="modal-header"><div><h3 class="modal-title">إضافة مقاول باطن جديد</h3><div class="text-secondary small">سيتم اختياره تلقائياً في العقد بعد الحفظ.</div></div><button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="إغلاق"></button></div><div class="modal-body"><input type="hidden" name="_token" value="<?=e($csrfToken)?>"><?=$this->component('vendor-fields',['vendor'=>null,'workSections'=>$workSections,'fixedVendorType'=>'subcontractor'])?><div class="alert alert-danger mt-3 d-none js-form-error" role="alert"></div></div><div class="modal-footer"><button type="button" class="btn btn-link" data-bs-dismiss="modal">إلغاء</button><button class="btn btn-primary js-save-vendor" type="submit"><i class="ti ti-device-floppy ms-2"></i>حفظ واختيار المقاول</button></div></form></div></div></div><script src="/assets/js/modules/vendors.js" defer></script><?php endif;?>
<script src="/assets/js/modules/subcontracts.js" defer></script>
