<?php
$isEdit = $certificate !== null;
$action = $isEdit ? '/subcontract-certificates/' . (int) $certificate['id'] . '/edit' : '/subcontracts/' . (int) $subcontract['id'] . '/certificates';
$value = static fn(string $key, string $default = ''): string => e((string) ($certificate[$key] ?? $default));
?>
<div class="page-header mb-4"><div class="row align-items-center"><div class="col"><div class="page-pretitle"><?= e($subcontract['subcontract_code'] . ' - ' . $subcontract['title']) ?></div><h2 class="page-title"><?= $isEdit ? 'تعديل مسودة المستخلص' : 'إضافة مستخلص أعمال' ?></h2></div><div class="col-auto"><a class="btn" href="<?= $isEdit ? '/subcontract-certificates/' . (int) $certificate['id'] : '/subcontracts/' . (int) $subcontract['id'] . '/certificates' ?>">إلغاء</a></div></div></div>
<form method="post" action="<?= $action ?>" id="certificate-form"><input type="hidden" name="_token" value="<?= e($csrfToken) ?>">
<div class="card mb-4"><div class="card-body"><div class="row g-3"><div class="col-md-4"><label class="form-label">الرقم المرجعي</label><input class="form-control" name="certificate_number" maxlength="100" value="<?= $value('certificate_number') ?>"></div><div class="col-md-4"><label class="form-label required">تاريخ المستخلص</label><input class="form-control" type="date" name="certificate_date" required value="<?= $value('certificate_date', date('Y-m-d')) ?>"></div><div class="col-md-4"><label class="form-label">الفترة من</label><input class="form-control" type="date" name="period_from" value="<?= $value('period_from') ?>"></div><div class="col-md-4"><label class="form-label">الفترة إلى</label><input class="form-control" type="date" name="period_to" value="<?= $value('period_to') ?>"></div><div class="col-md-8"><label class="form-label">ملاحظات</label><textarea class="form-control" name="notes" rows="2"><?= $value('notes') ?></textarea></div></div></div></div>
<?php if ($subcontract['pricing_method'] === 'boq'): ?>
<div class="alert alert-info">أدخل الكمية المنفذة حاليًا فقط. الكميات السابقة والأسعار والقيم يحسبها النظام من BOQ المعتمد.</div>
<div class="card mb-4"><div class="table-responsive"><table class="table table-vcenter"><thead><tr><th>البند</th><th>الوحدة</th><th>كمية العقد</th><th>السابقة</th><th style="min-width:150px">الحالية</th><th>التراكمية</th><th>السعر</th><th>القيمة الحالية</th><th>القيمة التراكمية</th></tr></thead><tbody><?php foreach ($items as $item): $previous = (string) ($item['live_previous_quantity'] ?? '0'); $remaining = max(0, (float) $item['contract_quantity'] - (float) $previous); ?><tr class="<?= $remaining == 0.0 ? 'table-warning' : '' ?>" data-progress-row data-previous="<?= e($previous) ?>" data-rate="<?= e($item['unit_rate']) ?>" data-contract="<?= e($item['contract_quantity']) ?>"><td><?= e($item['description_snapshot']) ?><?php if ($remaining == 0.0): ?><div class="text-warning small">تم استنفاد الكمية</div><?php endif; ?></td><td><?= e($item['unit_name_snapshot'] . (($item['unit_symbol_snapshot'] ?? '') !== '' ? ' (' . $item['unit_symbol_snapshot'] . ')' : '')) ?></td><td><?= e($item['contract_quantity']) ?></td><td><?= e($previous) ?></td><td><input class="form-control form-control-sm" data-current-quantity type="number" min="0" max="<?= e((string) $remaining) ?>" step="0.0001" name="quantities[<?= (int) $item['subcontract_boq_item_id'] ?>]" value="<?= e((string) $item['current_quantity']) ?>" <?= $remaining == 0.0 ? 'readonly' : '' ?>></td><td data-cumulative><?= e((string) ($item['live_cumulative_quantity'] ?? '0')) ?></td><td><?= e($item['unit_rate']) ?></td><td data-current-amount><?= e((string) ($item['live_current_amount'] ?? '0.00')) ?></td><td data-cumulative-amount><?= e((string) ($item['live_cumulative_amount'] ?? '0.00')) ?></td></tr><?php endforeach; ?></tbody></table></div></div>
<?php else: ?>
<div class="card mb-4"><div class="card-body"><div class="row g-3"><div class="col-md-3"><label class="form-label">قيمة العقد</label><input class="form-control" value="<?= e($subcontract['contract_value']) ?>" readonly></div><div class="col-md-3"><label class="form-label required">نسبة التقدم الحالية %</label><input class="form-control" type="number" name="current_progress_percentage" min="0" max="100" step="0.0001" required value="<?= $value('current_progress_percentage', '0') ?>"></div></div></div></div>
<?php endif; ?>
<div class="d-flex justify-content-end"><button class="btn btn-primary" type="submit">حفظ المسودة</button></div></form>
<script src="/assets/js/modules/subcontract-certificate-form.js" defer></script>
