<?php
declare(strict_types=1);
namespace App\Modules\Accounting\Repositories;
use App\Core\Database\Database;
use App\Core\Exceptions\BusinessRuleException;
use App\Modules\Accounting\DTOs\AccountData;
use App\Modules\Accounting\DTOs\JournalData;
final class AccountingRepository
{
 public function __construct(private readonly Database$db){}
 public function accounts():array{return$this->rows('SELECT a.*,p.account_code parent_code,p.name_ar parent_name FROM accounts a LEFT JOIN accounts p ON p.id=a.parent_id ORDER BY a.account_code');}
 public function account(int$id,bool$lock=false):?array{return$this->one('SELECT a.*,(SELECT COUNT(*) FROM accounts c WHERE c.parent_id=a.id) child_count FROM accounts a WHERE a.id=?'.($lock?' FOR UPDATE':''),[$id]);}
 public function saveAccount(AccountData$d,?int$id):int
 {
  if($id===null){$this->db->execute('INSERT INTO accounts(account_code,name_ar,name_en,parent_id,account_type,normal_balance,is_postable,is_control,is_active) VALUES(?,?,?,?,?,?,?,?,?)',[$d->code,$d->nameAr,$d->nameEn,$d->parentId,$d->type,$d->normalBalance,$d->isPostable,$d->isControl,$d->isActive]);return(int)$this->db->connection()->insert_id;}
  $existing=$this->account($id,true);
  if($existing!==null&&$this->hasPostedHistory($id)){
   $parent=$existing['parent_id']===null?null:(int)$existing['parent_id'];
   $changed=$d->code!==(string)$existing['account_code']||$d->type!==(string)$existing['account_type']||$d->normalBalance!==(string)$existing['normal_balance']||$d->parentId!==$parent||$d->isPostable!==(bool)$existing['is_postable']||$d->isControl!==(bool)$existing['is_control'];
   if($changed)throw new BusinessRuleException('لا يمكن تغيير خصائص الحساب الأساسية بعد وجود قيود مرحلة عليه.');
  }
  $this->db->execute('UPDATE accounts SET account_code=?,name_ar=?,name_en=?,parent_id=?,account_type=?,normal_balance=?,is_postable=?,is_control=?,is_active=? WHERE id=?',[$d->code,$d->nameAr,$d->nameEn,$d->parentId,$d->type,$d->normalBalance,$d->isPostable,$d->isControl,$d->isActive,$id]);return$id;
 }
 public function hasPostedHistory(int$id):bool{return$this->one('SELECT 1 found FROM journal_lines l JOIN journal_entries j ON j.id=l.journal_entry_id WHERE l.account_id=? AND j.status=\'posted\' LIMIT 1',[$id])!==null;}
 public function periods():array{return$this->rows('SELECT * FROM accounting_periods ORDER BY fiscal_year DESC,period_no');}
 public function yearExists(int$year):bool{return$this->one('SELECT id FROM accounting_periods WHERE fiscal_year=? LIMIT 1',[$year])!==null;}
 public function insertPeriod(int$year,int$period,string$start,string$end):void{$this->db->execute('INSERT INTO accounting_periods(fiscal_year,period_no,start_date,end_date) VALUES(?,?,?,?)',[$year,$period,$start,$end]);}
 public function setPeriodStatus(int$id,string$status):void{$this->db->execute('UPDATE accounting_periods SET status=? WHERE id=?',[$status,$id]);}
 public function openPeriod(string$date,bool$lock=false):?array{return$this->one('SELECT * FROM accounting_periods WHERE ? BETWEEN start_date AND end_date AND status=\'open\' LIMIT 1'.($lock?' FOR UPDATE':''),[$date]);}
 public function journals():array{return$this->rows('SELECT j.*,u.name created_by_name FROM journal_entries j JOIN users u ON u.id=j.created_by ORDER BY j.journal_date DESC,j.id DESC');}
 public function journal(int$id,bool$lock=false):?array{return$this->one('SELECT j.*,cu.name created_by_name,pu.name posted_by_name FROM journal_entries j JOIN users cu ON cu.id=j.created_by LEFT JOIN users pu ON pu.id=j.posted_by WHERE j.id=?'.($lock?' FOR UPDATE':''),[$id]);}
 public function journalLines(int$id,bool$lock=false):array{return$this->rows('SELECT l.*,a.account_code,a.name_ar account_name FROM journal_lines l JOIN accounts a ON a.id=l.account_id WHERE l.journal_entry_id=? ORDER BY l.sort_order,l.id'.($lock?' FOR UPDATE':''),[$id]);}
 public function createJournal(string$number,JournalData$d,int$user,?string$sourceType=null,?int$sourceId=null,?string$sourceReference=null):int{$this->db->execute('INSERT INTO journal_entries(journal_no,journal_date,description,reference,source_type,source_id,source_reference,created_by) VALUES(?,?,?,?,?,?,?,?)',[$number,$d->date,$d->description,$d->reference,$sourceType,$sourceId,$sourceReference,$user]);return(int)$this->db->connection()->insert_id;}
 public function updateJournal(int$id,JournalData$d):void{$this->db->execute('UPDATE journal_entries SET journal_date=?,description=?,reference=? WHERE id=? AND status=\'draft\' AND source_type IS NULL',[$d->date,$d->description,$d->reference,$id]);}
 public function replaceLines(int$id,array$lines):void{$this->db->execute('DELETE FROM journal_lines WHERE journal_entry_id=?',[$id]);foreach($lines as$l)$this->db->execute('INSERT INTO journal_lines(journal_entry_id,account_id,description,debit,credit,project_id,client_id,vendor_id,subcontract_id,employee_id,cost_code_id,sort_order) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)',[$id,$l['account_id'],$l['description'],$l['debit'],$l['credit'],$l['project_id'],$l['client_id'],$l['vendor_id'],$l['subcontract_id'],$l['employee_id'],$l['cost_code_id'],$l['sort_order']]);}
 public function journalSummary(int$id):array{return$this->one('SELECT CAST(COALESCE(SUM(debit),0) AS DECIMAL(18,2)) debit_total,CAST(COALESCE(SUM(credit),0) AS DECIMAL(18,2)) credit_total,COUNT(*) line_count,MIN((a.is_active=1 AND a.is_postable=1)) accounts_valid,MAX(a.is_control) has_control FROM journal_lines l JOIN accounts a ON a.id=l.account_id WHERE l.journal_entry_id=?',[$id])??[];}
 public function postJournal(int$id,int$user):void{$this->db->execute('UPDATE journal_entries SET status=\'posted\',posted_by=?,posted_at=NOW() WHERE id=? AND status=\'draft\'',[$user,$id]);}
 public function sourceExists(string$type,int$id):bool{return$this->one('SELECT id FROM journal_entries WHERE source_type=? AND source_id=? LIMIT 1',[$type,$id])!==null;}
 public function custodySettlementDimensions(int$id):?array{return$this->one('SELECT project_id,cost_code_id FROM employee_custody_settlements WHERE id=?',[$id]);}
 public function references():array{return['accounts'=>$this->rows('SELECT id,account_code,name_ar,is_control FROM accounts WHERE is_active=1 AND is_postable=1 ORDER BY account_code'),'projects'=>$this->rows('SELECT id,project_code,name FROM projects WHERE status<>\'cancelled\' ORDER BY project_code'),'clients'=>$this->rows('SELECT id,client_code,COALESCE(company_name,name) name FROM clients WHERE is_active=1 ORDER BY client_code'),'vendors'=>$this->rows('SELECT id,vendor_code,name FROM vendors WHERE is_active=1 ORDER BY vendor_code'),'subcontracts'=>$this->rows('SELECT id,subcontract_code FROM subcontracts WHERE status<>\'cancelled\' ORDER BY subcontract_code'),'employees'=>$this->rows('SELECT id,employee_code,name FROM employees WHERE is_active=1 ORDER BY employee_code'),'cost_codes'=>$this->rows('SELECT id,cost_code,name FROM cost_codes WHERE is_active=1 ORDER BY cost_code')];}
 public function setup():array{return$this->rows('SELECT s.mapping_key,s.account_id,a.account_code,a.name_ar,a.is_active,a.is_postable FROM accounting_setup s JOIN accounts a ON a.id=s.account_id ORDER BY s.mapping_key');}
 public function mapping(string$key,bool$lock=false):?array{return$this->one('SELECT s.mapping_key,a.* FROM accounting_setup s JOIN accounts a ON a.id=s.account_id WHERE s.mapping_key=?'.($lock?' FOR UPDATE':''),[$key]);}
 public function saveMapping(string$key,int$account):void{$this->db->execute('UPDATE accounting_setup SET account_id=? WHERE mapping_key=?',[$account,$key]);}
 public function fundingAccounts():array{return$this->rows('SELECT s.mapping_key,a.id,a.account_code,a.name_ar FROM accounting_setup s JOIN accounts a ON a.id=s.account_id WHERE s.mapping_key IN(\'cash_on_hand\',\'bank_account\') AND a.is_active=1 AND a.is_postable=1 ORDER BY s.mapping_key');}
 public function costCode(int$id):?array{return$this->one('SELECT * FROM cost_codes WHERE id=?',[$id]);}
 public function costCodeMappings():array{return$this->rows('SELECT c.id cost_code_id,c.cost_code,c.name cost_code_name,w.section_code,w.name section_name,m.account_id,a.account_code,a.name_ar account_name FROM cost_codes c JOIN work_sections w ON w.id=c.work_section_id LEFT JOIN accounting_cost_code_mappings m ON m.cost_code_id=c.id LEFT JOIN accounts a ON a.id=m.account_id WHERE c.is_active=1 AND w.is_active=1 ORDER BY w.section_code,c.cost_code');}
 public function costCodeMapping(int$id,bool$lock=false):?array{return$this->one('SELECT m.cost_code_id,a.* FROM accounting_cost_code_mappings m JOIN accounts a ON a.id=m.account_id WHERE m.cost_code_id=?'.($lock?' FOR UPDATE':''),[$id]);}
 public function saveCostCodeMapping(int$costCode,int$account):void{$this->db->execute('INSERT INTO accounting_cost_code_mappings(cost_code_id,account_id) VALUES(?,?) ON DUPLICATE KEY UPDATE account_id=VALUES(account_id)',[$costCode,$account]);}
 public function trialBalance(string$from,string$to):array{return$this->rows('SELECT a.account_code,a.name_ar,CAST(GREATEST(SUM(CASE WHEN j.journal_date<? THEN l.debit-l.credit ELSE 0 END),0) AS DECIMAL(18,2)) opening_debit,CAST(GREATEST(-SUM(CASE WHEN j.journal_date<? THEN l.debit-l.credit ELSE 0 END),0) AS DECIMAL(18,2)) opening_credit,CAST(SUM(CASE WHEN j.journal_date BETWEEN ? AND ? THEN l.debit ELSE 0 END) AS DECIMAL(18,2)) period_debit,CAST(SUM(CASE WHEN j.journal_date BETWEEN ? AND ? THEN l.credit ELSE 0 END) AS DECIMAL(18,2)) period_credit,CAST(GREATEST(SUM(CASE WHEN j.journal_date<=? THEN l.debit-l.credit ELSE 0 END),0) AS DECIMAL(18,2)) closing_debit,CAST(GREATEST(-SUM(CASE WHEN j.journal_date<=? THEN l.debit-l.credit ELSE 0 END),0) AS DECIMAL(18,2)) closing_credit FROM accounts a LEFT JOIN journal_lines l ON l.account_id=a.id LEFT JOIN journal_entries j ON j.id=l.journal_entry_id AND j.status=\'posted\' WHERE a.is_postable=1 GROUP BY a.id,a.account_code,a.name_ar ORDER BY a.account_code',[$from,$from,$from,$to,$from,$to,$to,$to]);}
 public function trialBalanceTotals(string$from,string$to):array{return$this->one('SELECT CAST(COALESCE(SUM(CASE WHEN j.journal_date<? THEN l.debit ELSE 0 END),0) AS DECIMAL(18,2)) opening_debit,CAST(COALESCE(SUM(CASE WHEN j.journal_date<? THEN l.credit ELSE 0 END),0) AS DECIMAL(18,2)) opening_credit,CAST(COALESCE(SUM(CASE WHEN j.journal_date BETWEEN ? AND ? THEN l.debit ELSE 0 END),0) AS DECIMAL(18,2)) period_debit,CAST(COALESCE(SUM(CASE WHEN j.journal_date BETWEEN ? AND ? THEN l.credit ELSE 0 END),0) AS DECIMAL(18,2)) period_credit,CAST(COALESCE(SUM(CASE WHEN j.journal_date<=? THEN l.debit ELSE 0 END),0) AS DECIMAL(18,2)) closing_debit,CAST(COALESCE(SUM(CASE WHEN j.journal_date<=? THEN l.credit ELSE 0 END),0) AS DECIMAL(18,2)) closing_credit FROM journal_lines l JOIN journal_entries j ON j.id=l.journal_entry_id AND j.status=\'posted\'',[$from,$from,$from,$to,$from,$to,$to,$to])??[];}
 public function trialBalanceDisplayTotals(string$from,string$to):array{return$this->one('SELECT CAST(SUM(opening_debit) AS DECIMAL(18,2)) opening_debit,CAST(SUM(opening_credit) AS DECIMAL(18,2)) opening_credit,CAST(SUM(period_debit) AS DECIMAL(18,2)) period_debit,CAST(SUM(period_credit) AS DECIMAL(18,2)) period_credit,CAST(SUM(closing_debit) AS DECIMAL(18,2)) closing_debit,CAST(SUM(closing_credit) AS DECIMAL(18,2)) closing_credit FROM(SELECT a.id,GREATEST(SUM(CASE WHEN j.journal_date<? THEN l.debit-l.credit ELSE 0 END),0) opening_debit,GREATEST(-SUM(CASE WHEN j.journal_date<? THEN l.debit-l.credit ELSE 0 END),0) opening_credit,SUM(CASE WHEN j.journal_date BETWEEN ? AND ? THEN l.debit ELSE 0 END) period_debit,SUM(CASE WHEN j.journal_date BETWEEN ? AND ? THEN l.credit ELSE 0 END) period_credit,GREATEST(SUM(CASE WHEN j.journal_date<=? THEN l.debit-l.credit ELSE 0 END),0) closing_debit,GREATEST(-SUM(CASE WHEN j.journal_date<=? THEN l.debit-l.credit ELSE 0 END),0) closing_credit FROM accounts a LEFT JOIN journal_lines l ON l.account_id=a.id LEFT JOIN journal_entries j ON j.id=l.journal_entry_id AND j.status=\'posted\' WHERE a.is_postable=1 GROUP BY a.id)b',[$from,$from,$from,$to,$from,$to,$to,$to])??[];}
 private function one(string$sql,array$params=[]):?array{$result=$this->db->execute($sql,$params);$row=$result instanceof \mysqli_result?$result->fetch_assoc():null;return is_array($row)?$row:null;}
 private function rows(string$sql,array$params=[]):array{$result=$this->db->execute($sql,$params);return$result instanceof \mysqli_result?$result->fetch_all(MYSQLI_ASSOC):[];}
}
