<?php
declare(strict_types=1);
namespace App\Modules\ProjectCosts\Repositories;
use App\Core\Database\Database;use App\Modules\ProjectCosts\DTOs\ProjectCostData;use App\Modules\ProjectCosts\DTOs\ProjectCostTableQuery;
final class ProjectCostRepository{
 public function __construct(private readonly Database $db){}
 public function project(int $id,bool $lock=false):?array{return $this->one('SELECT id,project_code,name,status FROM projects WHERE id=?'.($lock?' FOR UPDATE':''),[$id]);}
 public function costCode(int $id,bool $lock=false):?array{return $this->one('SELECT c.id,c.cost_code,c.name cost_code_name,c.is_active cost_code_active,w.id work_section_id,w.section_code,w.name work_section_name,w.is_active work_section_active FROM cost_codes c JOIN work_sections w ON w.id=c.work_section_id WHERE c.id=?'.($lock?' FOR UPDATE':''),[$id]);}
 public function vendor(int $id,bool $lock=false):?array{return $this->one('SELECT id,name,is_active FROM vendors WHERE id=?'.($lock?' FOR UPDATE':''),[$id]);}
 public function find(int $id,bool $lock=false):?array{$sql='SELECT x.*,p.project_code,p.name project_name,c.cost_code current_cost_code,c.name current_cost_code_name,w.section_code current_section_code,w.name current_section_name,v.name vendor_name,cu.name created_by_name,au.name approved_by_name,xu.name cancelled_by_name FROM project_actual_costs x JOIN projects p ON p.id=x.project_id JOIN cost_codes c ON c.id=x.cost_code_id JOIN work_sections w ON w.id=c.work_section_id LEFT JOIN vendors v ON v.id=x.vendor_id JOIN users cu ON cu.id=x.created_by LEFT JOIN users au ON au.id=x.approved_by LEFT JOIN users xu ON xu.id=x.cancelled_by WHERE x.id=?'.($lock?' FOR UPDATE':'').' LIMIT 1';return $this->one($sql,[$id]);}
 public function lockEntry(int $id):?array{return $this->one('SELECT * FROM project_actual_costs WHERE id=? FOR UPDATE',[$id]);}
 public function create(string $code,ProjectCostData $d,int $user):int{$this->db->execute("INSERT INTO project_actual_costs(cost_entry_code,project_id,cost_code_id,vendor_id,cost_date,description,reference_number,amount,source_type,created_by,notes) VALUES(?,?,?,?,?,?,?,?,'manual',?,?)",[$code,$d->projectId,$d->costCodeId,$d->vendorId,$d->costDate,$d->description,$d->referenceNumber,$d->amount,$user,$d->notes]);return (int)$this->db->connection()->insert_id;}
 public function update(int $id,ProjectCostData $d):void{$this->db->execute("UPDATE project_actual_costs SET project_id=?,cost_code_id=?,vendor_id=?,cost_date=?,description=?,reference_number=?,amount=?,notes=? WHERE id=? AND status='draft'",[$d->projectId,$d->costCodeId,$d->vendorId,$d->costDate,$d->description,$d->referenceNumber,$d->amount,$d->notes,$id]);}
 public function approve(int $id,int $user,array $m):void{$this->db->execute("UPDATE project_actual_costs SET work_section_code_snapshot=?,work_section_name_snapshot=?,cost_code_snapshot=?,cost_code_name_snapshot=?,status='approved',approved_at=NOW(),approved_by=? WHERE id=? AND status='draft'",[$m['section_code'],$m['work_section_name'],$m['cost_code'],$m['cost_code_name'],$user,$id]);$verified=$this->one('SELECT status,approved_by FROM project_actual_costs WHERE id=?',[$id]);if(($verified['status']??null)!=='approved'||(int)($verified['approved_by']??0)!==$user)throw new \RuntimeException('Approval update failed.');}
 public function cancel(int $id,int $user):void{$this->db->execute("UPDATE project_actual_costs SET status='cancelled',cancelled_at=NOW(),cancelled_by=? WHERE id=? AND status='draft'",[$user,$id]);$verified=$this->one('SELECT status,cancelled_by FROM project_actual_costs WHERE id=?',[$id]);if(($verified['status']??null)!=='cancelled'||(int)($verified['cancelled_by']??0)!==$user)throw new \RuntimeException('Cancellation update failed.');}
 public function total(int $project):string{return(string)($this->one("SELECT COALESCE(SUM(amount),0.00) total FROM project_actual_costs WHERE project_id=? AND status='approved'",[$project])['total']??'0.00');}
 public function byCostCode(int $project):array{return$this->rows("SELECT work_section_code_snapshot work_section_code,work_section_name_snapshot work_section_name,cost_code_snapshot cost_code,cost_code_name_snapshot cost_code_name,SUM(amount) total FROM project_actual_costs WHERE project_id=? AND status='approved' GROUP BY work_section_code_snapshot,work_section_name_snapshot,cost_code_snapshot,cost_code_name_snapshot ORDER BY work_section_code_snapshot,cost_code_snapshot",[$project]);}
 public function byWorkSection(int $project):array{return$this->rows("SELECT work_section_code_snapshot work_section_code,work_section_name_snapshot work_section_name,SUM(amount) total FROM project_actual_costs WHERE project_id=? AND status='approved' GROUP BY work_section_code_snapshot,work_section_name_snapshot ORDER BY work_section_code_snapshot",[$project]);}
 public function summary(int $project):array{return$this->one("SELECT COALESCE(SUM(CASE WHEN status='approved' THEN amount ELSE 0 END),0.00) approved_total,SUM(status='approved') approved_count,COALESCE(SUM(CASE WHEN status='draft' THEN amount ELSE 0 END),0.00) draft_total,SUM(status='draft') draft_count FROM project_actual_costs WHERE project_id=?",[$project])??[];}
 public function references():array{return['projects'=>$this->rows('SELECT id,project_code,name,status FROM projects ORDER BY project_code'),'codes'=>$this->rows('SELECT c.id,c.cost_code,c.name,w.id work_section_id,w.section_code,w.name section_name,c.is_active,w.is_active section_active FROM cost_codes c JOIN work_sections w ON w.id=c.work_section_id ORDER BY w.sort_order,c.sort_order'),'vendors'=>$this->rows('SELECT id,vendor_code,name,is_active FROM vendors ORDER BY name'),'sections'=>$this->rows('SELECT id,section_code,name FROM work_sections ORDER BY sort_order')];}
 public function dataTable(ProjectCostTableQuery $q):array{$w=[];$p=[];foreach(['x.project_id'=>$q->projectId,'ws.id'=>$q->workSectionId,'x.cost_code_id'=>$q->costCodeId,'x.vendor_id'=>$q->vendorId,'x.status'=>$q->status,'x.source_type'=>$q->sourceType]as$f=>$v)if($v!==null){$w[]="$f=?";$p[]=$v;}if($q->dateFrom){$w[]='x.cost_date>=?';$p[]=$q->dateFrom;}if($q->dateTo){$w[]='x.cost_date<=?';$p[]=$q->dateTo;}if($q->search!==''){$s='%'.$q->search.'%';$w[]='(x.cost_entry_code LIKE ? OR pr.name LIKE ? OR c.cost_code LIKE ? OR ws.section_code LIKE ? OR v.name LIKE ? OR x.description LIKE ? OR x.reference_number LIKE ?)';array_push($p,$s,$s,$s,$s,$s,$s,$s);}$where=$w?' WHERE '.implode(' AND ',$w):'';$from=' FROM project_actual_costs x JOIN projects pr ON pr.id=x.project_id JOIN cost_codes c ON c.id=x.cost_code_id JOIN work_sections ws ON ws.id=c.work_section_id LEFT JOIN vendors v ON v.id=x.vendor_id JOIN users cu ON cu.id=x.created_by LEFT JOIN users au ON au.id=x.approved_by';$total=$this->one('SELECT COUNT(*) total FROM project_actual_costs'.($q->projectId?' WHERE project_id=?':''),$q->projectId?[$q->projectId]:[]);$filtered=$this->one('SELECT COUNT(*) total'.$from.$where,$p);$sort=['cost_entry_code'=>'x.cost_entry_code','cost_date'=>'x.cost_date','project_name'=>'pr.name','section_code'=>'section_code','cost_code'=>'shown_cost_code','vendor_name'=>'v.name','description'=>'x.description','reference_number'=>'x.reference_number','amount'=>'x.amount','source_type'=>'x.source_type','status'=>'x.status','created_by_name'=>'cu.name','approved_by_name'=>'au.name'];$sql="SELECT x.id,x.cost_entry_code,x.cost_date,pr.name project_name,CASE WHEN x.status='approved' THEN x.work_section_code_snapshot ELSE ws.section_code END section_code,CASE WHEN x.status='approved' THEN x.work_section_name_snapshot ELSE ws.name END section_name,CASE WHEN x.status='approved' THEN x.cost_code_snapshot ELSE c.cost_code END shown_cost_code,CASE WHEN x.status='approved' THEN x.cost_code_name_snapshot ELSE c.name END cost_code_name,v.name vendor_name,x.description,x.reference_number,x.amount,x.source_type,x.status,cu.name created_by_name,au.name approved_by_name".$from.$where.' ORDER BY '.($sort[$q->sortColumn]??'x.cost_date').' '.$q->sortDirection.',x.id '.$q->sortDirection.' LIMIT ? OFFSET ?';$r=$this->db->execute($sql,[...$p,$q->length,$q->start]);return['recordsTotal'=>(int)($total['total']??0),'recordsFiltered'=>(int)($filtered['total']??0),'rows'=>$r instanceof \mysqli_result?$r->fetch_all(MYSQLI_ASSOC):[]];}
 private function one(string $sql,array $params=[]):?array{$r=$this->db->execute($sql,$params);$row=$r instanceof \mysqli_result?$r->fetch_assoc():null;return is_array($row)?$row:null;}
 private function rows(string $sql,array $params=[]):array{$r=$this->db->execute($sql,$params);return $r instanceof \mysqli_result?$r->fetch_all(MYSQLI_ASSOC):[];}
}
